### ISSUE TITLE
[Bug] Bundle category cannot be disabled if I set it to Reverse

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#100]
If I  the Game Categories -> Bundled is set to "Reverse (show only if not bundled)." (I think it is even default there) and then it is disabled - it shows "Not Bundled" in giveaways. So it cannot be disabled.
![game tags](https://cloud.githubusercontent.com/assets/2397851/26317709/a3812674-3f18-11e7-91f5-c3e4bcdc7cac.png)

**Comment by gizellos** [comment]
BTW I think you should also check if Bundle List Resync was done at least once and if it was not, then disable the bundle category.

Without the check with those bug the "Not Bundled" icon show for every GA and it must be quite confusing for new users that may even don't know that there is a resync for it.

**Comment by revilheart** [comment]
Can't quite make out that last sentence.

**Comment by gizellos** [comment]
That it is possible that the bug in OP caused the second issue. I don't know if there is the condition like "if resync was not done, then disable showing Bundle". If it is there, the first bug caused it, if it is not there, you should put it there.

**Comment by revilheart** [comment]
The bug should be fixed and I changed it not to be displayed if it wasn't synced yet.
