### ISSUE TITLE
[Enhancement] Show only selected genres in Game Categories

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#101]
I would really love if I could specify genres I want to show via Game Categories feature. For example, I would set that I want to only show Massive Multiplayer and Strategy. Each the genre could have set its own color. 

![specify game genres](https://cloud.githubusercontent.com/assets/2397851/26318644/1f26a648-3f1c-11e7-8ded-e5340b4166cd.png)

**Comment by revilheart** [comment]
I think each genre having its own color would be confusing, especially for users who have all categories enabled.

**Comment by gizellos** [comment]
I mean it only if one wanted to use it. Default state would be as it is now.

**Comment by ldeman** [comment]
that's a really large list of tags to have color options for though.
http://store.steampowered.com/tag/browse/#global_492 (left hand side)

**Comment by gizellos** [comment]
Ideman: you also don't understand that. If you chose only, for example, two tags, then you need just two colors. I don't mean to make all genres separate but only those you chose. So for example, I would choose only 1 genre and I would need only one color. 

It would be only for selected genres not for all. But the color is not so important. Important is to have the possibility to select the genres.

**Comment by revilheart** [comment]
Still, that's way too many genres and I would have to add options for each of them in the settings menu, which would make it extremely large. Maybe I can add a field to the Giveaway Filters feature where you can type names of genres and those that are not present are filtered out.

**Comment by revilheart** [comment]
Or I could add that field to the settings menu, that would work well, I think. I'll test some things.

**Comment by gizellos** [comment]
It would be enough just to add a text field and we could writ there the tags, divided by , or ;.

![user defined genres](https://cloud.githubusercontent.com/assets/2397851/26324574/9a23e024-3f33-11e7-97eb-d4a6ea2f34a4.png)

**Comment by gizellos** [comment]
With colors it could be made like this: there would be 1 text field and beside it, there would be the color picker button. Under it, there would be a button PLUS and it would add another text field under it.

**Comment by revilheart** [comment]
I added a genre filter to Giveaway Filters. I think that's the best solution, but it has no support for colors (sorry, allowing different colors for genres would just be a pain). I hope it's at least a bit better. :)

**Comment by gizellos** [comment]
Yeah, it's much better. It will help me a lot. Thanks a bunch. :)
