### ISSUE TITLE
[Enhancement] Make opening in new window optional

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#102]
I really hate when a website force me to open links in new windows/tabs. If I wanted to open a link in new window/tab I would use middle mouse button, shift key or select the link and select new window in the right-click-mouse-menu. But there is not a special mouse button, menu or key for opening in current tabs.

Please make it optional for the ESGST menu.

**Comment by revilheart** [comment]
Changed it.

**Comment by gizellos** [comment]
Thanks a lot.
