### ISSUE TITLE
[Bug] Redudant buttons in Create a new giveaway

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#103]
I am not sure if these two buttons are supposed to be there. It seems they are redudant.

![wrong buttons](https://cloud.githubusercontent.com/assets/2397851/26325145/0b2f3c08-3f36-11e7-9161-27336d6f4557.png)

**Comment by ldeman** [comment]
hmm. never noticed that one, but now that you mention it, i think it's been there a long while.  xD

**Comment by revilheart** [comment]
That actually came with v6. v5 first checked if there were any users in the page and then inserted the button. v6 inserts the button no matter what. I'll implement the v5 solution later.

**Comment by revilheart** [comment]
Removed them from pages where they shouldn't appear.
