### ISSUE TITLE
[Enhancement] More Filter Features

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#106]
i typed this up in the sg discussion but i think you'd rather have it here.

Exclude group giveaways
Exclude whitelist giveaways
Exclude pinned giveaways
Exclude region-restricted giveaways
Exclude multiple copy giveaways

what i mean by exclude is it would be an exclusion/exception to the filter.  when any of those exclusions are enabled, it allows for those to stay unfiltered and they become an exception to the filter.

for example if i were to only show level 3-9 giveaways, but i had those all enabled, i would still see level 0 giveaways that had more then 1 copy, the pinned giveaways regardless of level, the whitelist giveaways, etc. 

i hope i made it more clear for you.  thanks ^^

**Comment by revilheart** [comment]
Ah I see what you mean now. "Exclude" is a weird word for this. I'll use "Filter", as in "Filter group giveaways" adds group giveaways to the filter.

**Comment by gizellos** [comment]
In fact there are three possible combinations that would be good to have.

1. Apply filters even on group GAs on the main page
2. Don't  apply filters on group GAs on the main page
3. Don't show group GAs at all on the main page

Could you implement it all? I am the one who wants see only public giveaways on the main page.

**Comment by ldeman** [comment]
i think filter exceptions would be a little more clear for most people to understand.

Filter Exceptions:
✅Group
✅Whitelist
✅Multiple Copies over [2]   (have a box to specify how many copies triggers the exception)
✅Region Restriction

it could probably be a 3-way switch to additionally cover gizellos's suggestion, but i'm not sure what you'd label them to make sense.  maybe ✅=enable exception ❌=fully disable ◻️=inactive

**Comment by revilheart** [comment]
gizellos' suggestion can be done without the need for a 3-state checkbox:

1. Disable filter exception for group.
2. Enable filter exception for group.
3. Disable "Group".

**Comment by ldeman** [comment]
sounds good ^^

**Comment by gizellos** [comment]
Maybe like this?

Filter Exceptions:
✅Group
✅Whitelist
✅Multiple Copies over [2] (have a box to specify how many copies triggers the exception)
✅Region Restriction

Hide giveaways:
✅ Entered
✅ Group/Whitelist

**Comment by revilheart** [comment]
Oh but that would affect the group/whitelist page too. I'll see what I can do.

**Comment by revilheart** [comment]
There's no need for the hide giveaways section. It's already there. You just have to disable "Entered", "Group" and "Whitelist".

**Comment by ldeman** [comment]
they just showed an example how it would tie in with the existing feature. xD
i think that would look the cleanest too though personally. (gizellos's latest example)

**Comment by gizellos** [comment]
I know I suggested it like that because the the hiding entered giveaways could be in the same menu group. Do it like you want.

**Comment by revilheart** [comment]
Oh if you want me to just add "Hide giveaways:" to the top of the section and invert the checkboxes (enabled hides instead of showing) I can do that. I thought you wanted me to add another section.

**Comment by gizellos** [comment]
No, I don't need anything with the entered giveaways checkbox. Just those two things are the same kind of settings and it could be or even should be together. So instead the two things would be in two placed, they would be in one. I wrote about it like just about a bonus to the issue we are talking about. :)

**Comment by ldeman** [comment]
well if it's done like that then you can take the "hide giveaways" even further and also add filters for people who aren't even apart of this conversation such as.    (with full example)

Filter Exceptions:
⬜ Group/Whitelist
✔️ Multiple Copies over [2] (have a box to specify how many copies triggers the exception)
✔️ Region Restriction

Hide giveaways:
✔️ Entered
✔️ Group/Whitelist
⬜ Region Restriction  (something other people might want too)

**Comment by revilheart** [comment]
Actually I think I'll leave it the way it is. Because then I would have to add another section for "show only". The single section with the 3-state checkbox works better.

**Comment by ldeman** [comment]
okay, works for me still.  ^^

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Yes it seems to work and it looks good. Good work, thanks. :)

**Comment by ldeman** [comment]
sry about any confusion i might of given you on the sg discussion.  yes it all seems to work perfectly, except the copy counter can't be typed in, the arrows need to be used.

**Comment by ldeman** [comment]
shoot, there is one exception we forgot.
Wishlist
