### ISSUE TITLE
Option for disabling filtering on the group/WL page and Wishlist

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#107]
Please add an option to disable the filters on  [Group/WL page ](https://www.steamgifts.com/giveaways/search?type=group)and [Wishlist GA page.](https://www.steamgifts.com/giveaways/search?type=wishlist) I cannot see any giveaways there sincethe script applied the settings I set for public GAs.

**Comment by gizellos** [comment]
Or the settings could be saved for each the page individually. It would be even better.

**Comment by ldeman** [comment]
+1
i don't use this part of filtering personally, but it's certainly going to be wanted by many.  ^^

**Comment by revilheart** [comment]
Each of those pages have their own settings now.

**Comment by gizellos** [comment]
You rock!!! It's really wonderful. Thanks a lot. :)
