### ISSUE TITLE
[Bug] Syncing my own games never ends

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#110]
I use removing owned games entries together with normal sync. It stopped to work for me.  It freezes and never ends, although the indicator is spinning.

![2017-05-23_180647](https://cloud.githubusercontent.com/assets/2397851/26363947/fe509e16-3fe2-11e7-9582-75aec2e33621.png)

**Comment by revilheart** [comment]
Errors in the console?

**Comment by revilheart** [comment]
Nevermind, I got the error as well.

**Comment by revilheart** [comment]
Fixed
