### ISSUE TITLE
Only Bundled game category is shown while creating new giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#111]
I don't know if it is a bug or a feature but it seems that only Bundled game category is shown when a game for a new giveaway is chosen.

It's OK for me since I believe it is the only useful category on the page, but maybe you don't want it to be like this.

**Comment by revilheart** [comment]
Yep, it's supposed to be that way, since I don't really see the point of seeing other categories while creating a giveaway.
