### ISSUE TITLE
[Bug] ESGST has failed to load in any page on SG

### ISSUE THREAD

**Issue by luisfilipels** [revilheart/ESGST#114]
Here's the log, if interested:
`   ReferenceError: loadEsgst is not defined

    at Window.tms_106038ec_4f22_4829_ae0b_45efc65c43bd (eval at E_c (:3:114), <anonymous>:13426:5)
    at <anonymous>:2:297
    at eval (eval at E_c (:3:114), <anonymous>:3:1)
    at eval (eval at E_c (:3:114), <anonymous>:4:3)
    at Object.eval (eval at E_c (:3:114), <anonymous>:13443:6)
    at <anonymous>:2:297
    at Object.E_c (<anonymous>:3:112)
    at E (eval at exec_fn (:1:108), <anonymous>:57:175)
    at Object.create (eval at exec_fn (:1:108), <anonymous>:65:282)
    at z (eval at exec_fn (:1:108), <anonymous>:14:88)`

It just started happening today. Anything to do with the new update?

**Comment by revilheart** [comment]
What browser and script extension are you on?

**Comment by luisfilipels** [comment]
Vivaldi 1.9 and Tampermonkey

**Comment by revilheart** [comment]
Is it fixed in v6.Beta.3.2?

**Comment by gizellos** [comment]
I also had problems on Vivaldi with the newer versions. It was caused because I had two installations of ESGST in tampermonkey. Check tampermonkey if you have there just one ESGST.

**Comment by gizellos** [comment]
Well, Vivaldi doesn't want to loiad ESGST for me too now. 
`prebid.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/General/FixedHeader.v6.0.0.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/General/FixedMainPageHeading.v6.0.0.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/General/FixedFooter.v6.0.0.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/General/HiddenBlacklistStats.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/General/AccurateTimestamps.v6.0.0.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/General/PaginationNavigationOnTop.v6.0.0.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Giveaways/DeliveredGiftsNotifier.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Giveaways/PointsRefresher.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Giveaways/HiddenFeaturedContainer.v6.0.0.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Giveaways/AdvancedGiveawaySearch.v5.1.0.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Giveaways/PinnedGiveawaysButton.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Giveaways/GridView.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Giveaways/GiveawayGroupsPopup.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Giveaways/GiveawayTemplates.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Giveaways/StickiedGiveawayGroups.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Giveaways/GiveawayWinnersLink.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Giveaways/GiveawayErrorSearchLinks.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Giveaways/ArchiveSearcher.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Discussions/ActiveDiscussionsOnTop.v6.0.0.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Discussions/DiscussionsHighlighter.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Discussions/MainPostPopup.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Discussions/DiscussionEditDetector.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Commenting/CommentHistory.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Commenting/CommentTracker.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Commenting/ReplyBoxPopup.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Commenting/MultiReply.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/Commenting/ReplyMentionLink.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/AvatarPopout.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/UsernameHistory.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/UserNotes.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/RealWonSentCVLinks.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/UserGiveawaysData.v5.1.0.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/NotActivatedMultipleWinsChecker.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/NotReceivedFinder.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/SentWonRatio.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/LevelUpCalculator.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/SteamGiftsProfileButton.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/SteamTradesProfileButton.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/SharedGroupsChecker.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/WhitelistBlacklistHighlighter.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/UserTags.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/InboxWinnersHighlighter.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/GroupsHighlighter.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/GroupsStats.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/GamesHighlighter.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/GameTags.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) Tampermonkey: couldn't load @require from URL https://github.com/revilheart/ESGST/raw/master/Scripts/Features/UsersGroupsGames/MultiTag.v5.js
tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd
(unknown) ReferenceError: loadFixedHeader is not defined
    at loadEsgst (eval at E_c (:3:221), <anonymous>:411:19)
    at Window.tms_8031de9b_38d0_43a4_bbc5_66e449fe71cd (eval at E_c (:3:221), <anonymous>:14836:5)
    at <anonymous>:2:398
    at eg (eval at E_c (:3:221), <anonymous>:3:1)
    at eval (eval at E_c (:3:221), <anonymous>:4:3)
    at Object.eval (eval at E_c (:3:221), <anonymous>:14853:6)
    at <anonymous>:2:398
    at Object.E_c (<anonymous>:3:219)
    at E (eval at exec_fn (:1:108), <anonymous>:60:467)
    at Object.create (eval at exec_fn (:1:108), <anonymous>:69:51)
`

**Comment by luisfilipels** [comment]
It's working just fine now, thank you very much and good job!
