### ISSUE TITLE
[Enhancement] Trading Cards filter should apply also to Exceptions

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#115]
If I set the filter to show only giveaways with Trading Cards and I allow to show there also, for example, group or whitelist giveaways, it will show there also group and whitelist giveaways without trading cards. I think the trading cards should apply to the group or whitelist giveaways too.

**Comment by revilheart** [comment]
Hmm I don't know, then I would have to add exceptions for every single category.

**Comment by gizellos** [comment]
I don't know how you would have to do it, but I think this behaviour could be make in a universal way (I mean it that it could apply no matter the other settings, without exceptions) because if someone wants to see only trading cards giveaways, they don't care what else they set in the filters. Maybe you could first apply all the other filters and then to filter the results again for the trading cards. But IDK I didn't study the implementation of the filters. 

I think it is quite important behavior, because it is quite annoying when someone wants to see just giveaways with cards and they see also giveaways without cards.

If it is not so bad, please try to do it somehow.  I know you want to have clean code and to have there a gazillion exceptions is not good.

**Comment by revilheart** [comment]
Filtering by the others first, and then by categories, seems like a nice solution.

**Comment by revilheart** [comment]
Category filters are now applied to exceptions.

**Comment by gizellos** [comment]
Thanks a lot.
