### ISSUE TITLE
Real CV needs corrected

### ISSUE THREAD

**Issue by b1763021** [revilheart/ESGST#116]
There are multiple cases where a game that previously cost something and is now free to play. Steamgifts and sgtools have yet to address this issue. Having bought several games at full price and having given them away, it is extremely annoying to find myself being prohibited from giveaways that this miscalculation is preventing me from entering. This is a 15% CV calculation error in my case.

Simplest solution, that I can think of, would be to include a this list of games with a set price that overrides the location it is pulled from (assuming your using the information is from steamgifts or you are checking it yourselves) to calculate the real CV value.

**Comment by revilheart** [comment]
Shouldn't that be something to be fixed on SG/SGTools though? Me changing it in the script won't allow you to enter those giveaways

**Comment by revilheart** [comment]
Looks like cg changed it: https://www.steamgifts.com/discussion/e9zDo/change-log
