### ISSUE TITLE
[Enhancement] More user friendly Check for Updates

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#118]
The current system of checking for updates is not very user friendly. I suggest you to make a normal checking for updates such as in desktop apps. So you would click on the link in ESGST menu, a pop up (or pop out, I still cannot remember which is which, sorry) would appear, the script would  check if your version is up-to-date and it would either write you something like "ESGST is up-to-date" or something like "There is a newer version of ESGST."

If it is possible to force Tampermonkey/Greasemonkey via the script to update it, it would be even better, but the info about new version would be enough.

**Comment by revilheart** [comment]
Yep, I already intended on doing that.

**Comment by revilheart** [comment]
Let me know if it's better with the new update.

**Comment by gizellos** [comment]
It's very good. Works well. Thanks a lot. :)
