### ISSUE TITLE
[Enhancement] Notice about changes in new installed versions

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#119]
Unfortunately, Tampermonkey doesn't inform about updated scripts so it's quite hard to find out that there is a new version installed if it is installed automatically. What is more, even if I know there is a new version installed, it is not so easy to find the changes. 

Therefore I suggest this:
- If there is a new version installed, the script will temporally add a notice to the webpage. It could be something on the ESGST menu button. Maybe a small icon or text.
- In the menu, there will be another item - Changelog
- After clicking on the Changelog, a changelog will open in pop up/pop out

**Comment by revilheart** [comment]
Added something, let me know if it's a good solution.

**Comment by gizellos** [comment]
Yes, that's exactly what I meant. Good!
