### ISSUE TITLE
[Enhancement] Mark viewed Exclusive giveaways as viewed

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#121]
It would be good to know if I have already seen the giveaways or not. It would help either to add a small icons beside the links or make their font bold or something like  that. Viewed I mean just viewed in the  Exclusive Giveaways window. 

Of course there could be also an icon for entered giveaways as well or game categories.

**Comment by gizellos** [comment]
Also the level requirement would be nice.

**Comment by revilheart** [comment]
Let me know if it's better in the new update.

**Comment by gizellos** [comment]
It's good but it shows me Enter button even with games I already own.
