### ISSUE TITLE
Game categories aren't fully loading

### ISSUE THREAD

**Issue by robin3010** [revilheart/ESGST#123]
I can see only few random type of categories on a random GAs. I'm using Chrome, other scripts was disabled before testing, bundle list successfully synced few days ago.
I'm pretty sure, it's due to russian language on steam store, because "Steam Cloud" category seems to work correctly on all GAs and it's only one that not contains cyrillic symbols in russian steam store.

**Comment by revilheart** [comment]
The script should now retrieve data from the US store.
