### ISSUE TITLE
[Bug] Real CV Calculator will not stay enabled.

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#124]
i've turned it on literally 11 times now.  there doesn't seem to be any errors, and when i refresh after enable it is still enabled and it works, but then something within an hours time-frame or less causes it to disable all on its own.   only one single time was it possibly related to an update, all other times it did it within the same version.

(i kept track of it inside sg ever since the 4th time https://www.steamgifts.com/go/comment/lLilmlc )

**Comment by revilheart** [comment]
It was disabling it every time a giveaway was created, should be fixed.
