### ISSUE TITLE
[Enhancement] Suggestion to the exclusive giveaways feature

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#125]
the community has been almost entirely accepting too it, however i was just thinking it might actually be a hair safer if it were renamed to "Auto-Puzzle Creator / Auto-Puzzle Revealer"  or something a little closer to those lines.  it technically kind of is anyways, but it would be much safer against the gleam referall rules of
"content should not force users........  to perform an action for promotional..... Such actions include but are not limited to..... etc etc etc."

obviously it's just a recommendation/suggestion, it's your script, but with this there is no possible way anyone could claim it's to promote the script beyond the convenience suggestion.

**Comment by revilheart** [comment]
You really think there could be a problem?

**Comment by ldeman** [comment]
i would honestly think and hope not.  but if i thought about it, someone else could and try and spin it into that rule if they had for some reason gotten mad about the script.  i'd think support would look at it like a puzzle anyways, but i can't say for certain.

**Comment by judgegr** [comment]
Me too, I don't think this feature poses a threat, however, **Surprise Giveaways** might be a playful but safe alternative.

**Comment by ldeman** [comment]
yeah, that sounds great too.  and i'm fine with it personally, i just think the word exclusive brings a negative annotation along with it that is technically not even true in this case really anyways.

**Comment by revilheart** [comment]
Changed it to Giveaway Encrypter/Decrypter.

**Comment by ldeman** [comment]
it makes sense, it looks great, and it takes away any chance anyone could possibly have at spinning the feature into a rulebreak of any type.  ^^
thanks

**Comment by gizellos** [comment]
I am not sure if it is legal to make topic such as "GAs for ESGST user's only", anyway. When mere clicking on an action in gleam GAs is against rules, forcing people to install a script is probably too. I hope it is not like that, for sure.

**Comment by ldeman** [comment]
@gizellos yeah that was my fear too.  well the fear that it could be spun into that rule-break as well as it just being general frowned upon.  this namechange should take away all of that though.  ^^

**Comment by gizellos** [comment]
@ldeman I am afraid that different name doesn't change anything. But I hope it will be OK.

**Comment by ldeman** [comment]
@gizellos it suggests its a puzzle now which is perfect acceptable in peoples eyes, whereas before it suggested it was exclusive to only people that use the script.

basically if anyone were to report it now, support would look into it and see the words "encrypter/decrypter" and think "oh, well it's nothing more then a puzzle.  but if it were to of been reported when it said "exclusive giveaway" support would look at it as something that forces the download of this script in order to join them which would be teeter-tottering along the gleam update rules.
