### ISSUE TITLE
[Bug] Exclusive giveaway error

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#126]
Uncaught TypeError: Cannot read property 'remove' of undefined
    at Function.eval (eval at E_c (:3:221), <anonymous>:17900:35)
    at <anonymous>:2:398
    at eval (eval at exec_fn (:1:108), <anonymous>:30:494)

---

it can be seen on page one and two of https://www.steamgifts.com/discussion/UKov2/her-story-exclusive-to-fellow-esgst-users-more-gas-added/ but the feature works perfectly fine on page 3.

**Comment by gizellos** [comment]
I think there cannot be the / at the end of the address. It gets error 404 otherwise.

**Comment by revilheart** [comment]
I think I know what it is and it should be related to hidden giveaways. I'll fix it when I get home.

**Comment by ldeman** [comment]
okay, sounds good. thanks ^^

**Comment by revilheart** [comment]
Should be fixed.
