### ISSUE TITLE
[Enhancement] Remove the underline below icons and text in Exclusive GAs list

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#127]
The underline below icons and text  in the Exclusive GAs list doesn't look very well.  Below the GA link it is useless, below the icons it is ugly and bellow the entries and comments it is even double that is even uglier.

I suggest to remove the underline below the GA link and  icons and fix the double underline.

![2017-05-27_104213](https://cloud.githubusercontent.com/assets/2397851/26519945/ac7eb3f4-42c9-11e7-96ce-344657c06e9e.png)

**Comment by revilheart** [comment]
Done
