### ISSUE TITLE
[Enhancement]  Ability to Unmark comments as read

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#128]
that error last night that caused things to unmark themselves actually made me want the ability to be able to unmark certain things as read as a reminder to re-read things.  ive gotten in the habit of marking things read instantly as i read them, but then there are a few times after i've done so i practically facepalm myself thinking "why did i do that, it would of been better left unread".  ^^

**Comment by revilheart** [comment]
Where would that apply though? I mean, if you're read a comment, why unread it?

**Comment by ldeman** [comment]
just individual comments, where the icon is for marking read is a crossed out eye it could turn into an eye for an undo.  basically for the instances i want to re-read it again later it would make it easier to relocate.

**Comment by revilheart** [comment]
Added

**Comment by ldeman** [comment]
thanks again!  =)
