### ISSUE TITLE
[Bug] Different behavior of entered giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#129]
If I am not a random SG page and go to the main giveaway page and use the enter button on a giveaway -  the giveaway vanishes immediately. However if I enter another GA the giveaway just turn grey. It should behave the same.

But there is a question which behavior is the right. I would prefer just the turning gray, because the page doesn't have to rearrange, but some other people may prefer the immediate vanishing.

Maybe you could make an option to choose if we want it just turn gray (until manual reloading page) or we want it disappear immediately.

Check enclosed gif to see the vanishing GA.

![vanishing ga](https://cloud.githubusercontent.com/assets/2397851/26560397/73db9046-44b6-11e7-8e96-cba9114c2ed0.gif)

**Comment by gizellos** [comment]
Check this gif to see the grayed GAs.

![grey gas](https://cloud.githubusercontent.com/assets/2397851/26560432/e07e30fa-44b6-11e7-8ecd-78261539e50b.gif)

**Comment by revilheart** [comment]
Should be fixed.
