### ISSUE TITLE
[Enhancement] Add also user tags category

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#130]
Unfortunately, the Genre category is not enough very often. Games are often set just like indie or something general like this and it's information value is 0. :( Therefore I suggest to add also users tags as a game category.

![genre vs tags](https://cloud.githubusercontent.com/assets/2397851/26521967/98328dda-42f6-11e7-9e07-e52f38563575.png)

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Wow, cool! Thanks!
