### ISSUE TITLE
[Bug] Error while loading a group giveaway

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#131]
1 ESGST features failed to load: Giveaway Panel. Check the console for more info.

TypeError: Cannot read property 'textContent' of undefined
    at setGWCChance (eval at E_c (:3:221), <anonymous>:5269:31)
    at addGWCChance (eval at E_c (:3:221), <anonymous>:5302:5)
    at Object.loadGiveawayPanel [as load] (eval at E_c (:3:221), <anonymous>:5075:13)
    at loadFeatures (eval at E_c (:3:221), <anonymous>:1729:29)
    at loadEsgst (eval at E_c (:3:221), <anonymous>:1649:5)
    at Window.tms_b08b5eca_9bc9_4dfa_920d_ddaa37ae358e (eval at E_c (:3:221), <anonymous>:436:5)
    at <anonymous>:2:398
    at eval (eval at E_c (:3:221), <anonymous>:3:1)
    at eval (eval at E_c (:3:221), <anonymous>:4:3)
    at Object.eval (eval at E_c (:3:221), <anonymous>:19174:6)

---

i honestly have no idea what this one means at all, and since it's a group you're not in, linking it wouldn't do any good.  description is identical to several others that are not having this error though, so i think it's unrelated to anything said in the comment.

edit: i'm also not seeing any side effects from the error, all seems fine visually.

**Comment by ldeman** [comment]
oh, one side effect of it is the "giveaway win chance" is not being calculated.
also i should note it's not active yet (starts in 24hours), however there are 4 of them total, 2which work fully and do not throw that error with odds and all.  then 2 of them that error and do not show odds.

**Comment by revilheart** [comment]
Is there a difference between them? All of them are not active yet or just the one throwing the error?

**Comment by ldeman** [comment]
no that's what i find odd about it. all identical start time, same description, all made with a 5min period, all the same group.  yet only 2/4 throw the error.

**Comment by ldeman** [comment]
well.. they happen to be the 2 out of 4 i do not own.. i don't know if maybe that has something to do with it.

**Comment by ldeman** [comment]
the error went away when the giveaways went live/active.  so it has something to do with it being a future giveaway.

**Comment by ldeman** [comment]
yeah, found another group game i didn't own and started a few minutes later.  it had errors white it was still a "future giveaway" but then the error went away as soon as it was a live giveaway.
![peek 2017-05-29 12-01](https://cloud.githubusercontent.com/assets/10275898/26557393/c063fe44-4466-11e7-8672-41114e2a1cf3.gif)

**Comment by revilheart** [comment]
Should be fixed.

**Comment by ldeman** [comment]
nice! i'm not aware of any test giveaways for this one, but sounds great!  =)
