### ISSUE TITLE
[Enhancement] Remove Enter buttons for owned games in ESGST encrypted GAs list

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#132]
I can see the Enter buttons in ESGST encrypted GAs list even if I own the games. Could it be detected and changed to the "Exists in Account" stuff?

![2017-05-27_201331](https://cloud.githubusercontent.com/assets/2397851/26523498/21b9f3dc-4319-11e7-9905-d17493db75c6.png)

**Comment by revilheart** [comment]
Should not be a problem now, for any page.
