### ISSUE TITLE
[Bug]  Some discussions don't have Last page link in navigation

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#138]
Some pages don't have the Last page link in navigation. For example [this one.](https://www.steamgifts.com/discussion/eOYPH/positive-thread-giveaways)

If it is not possible to find the last page for the script, there is a hack you can use -  just the url has to end to _/search?page=99999_

**Comment by Royalgamer06** [comment]
You can actually find this feature in my extended navigation script for steamgifts:
https://greasyfork.org/en/scripts/20144-steamgifts-extended-navigation
But it would be cool if it can be merged into this script.

**Comment by gizellos** [comment]
@Royalgamer06 Thanks. Maybe you could make a pull request. :)

**Comment by revilheart** [comment]
Added
