### ISSUE TITLE
[Enhancement] Allow to delete checker caches without deleting user notes and tags

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#139]
I would like to use "Manage data" feature to delete checkers data but I cannot do it because I would also delete user notes and tags according to the fact they are all one option. Please separate it to three options.

BTW: is possible to show size of the options? My whole export has size 9.5 MB, it is too much. I would like to know what to reduce.

**Comment by ldeman** [comment]
additionally related to this, i'd love to delete all my checker cache except the known whitelist/blacklist users.  i've got something like 2k users that don't fit either category and i'd rather not rescan them over and over.  

my database is way to large and i want to clean it up, but i don't really want to lose the known wl/bl & tags/notes.

**Comment by revilheart** [comment]
Added. I'll look into the option to delete specific caches later.
