### ISSUE TITLE
[Enhancement]  Last Scan Info via tooltip hover

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#142]
lately i've just been re-checking users activation/multi-win every single time it will allow it, but going thru ~100giveaways or more a week i'm bound to run into repeats several times and end up scanning more then i should.   it would be very helpful to get the "Last Scanned on: xx-xx-2017" on the tooltip hover so i can determine whether it is really necessary to check users i already have scanned.  some of my scans are 6months old, and others are only 6hours old now.

**Comment by ldeman** [comment]
same could be useful for the wl/bl checker too.  ^^

**Comment by revilheart** [comment]
Added

**Comment by ldeman** [comment]
thanks for this, will be very helpful to save time and server bandwidth when it's unnecessary.  ^^
