### ISSUE TITLE
[Enhancement] Change hover color of visited links in thread list or remove it

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#143]
Threads that I haven't visit have black color and when I hover them, their color don't change. However visited threads have grey color and when I hover them, they color will change to black. 

It is not good because the behavior should be the same. They both should either use changing color via hover or they both shouldn't use it at all. But I don't write it just because of conventions.

My problem is that the hover color of visited links is the same color as unvisited links and when I get to a list of pages and my mouse cursor is on a visited link, the link has black color and it looks as if the link was unvisited. So the problem is that the color of hover visited links is the same as the color of unvisited links and it is often very confusing when I don't know when my cursor is on the link.

So please change the color of hover visited links to a different one. I would like dark grey. (And if you want, add a hover color for unvisited links too because of the conventions. Or remove the hover for  visited links. It's on you.)

![hover visited link](https://user-images.githubusercontent.com/2397851/26881471-c7d27db2-4b97-11e7-979f-ab1ef83e484a.png)

**Comment by revilheart** [comment]
I changed how visited discussions are seen, is it better?

**Comment by gizellos** [comment]
Yes it is better but I meant just to change the a:hover of the visited links. So all links would have a:hover, just visited and unvisited links would have different color of it. But it is ok like this. I just have to get used to the links without the hover effect. Thanks. :)

**Comment by gizellos** [comment]
Or maybe you could also add the hover effect. It would be even better because I like both the new background and link hover effect.

**Comment by ldeman** [comment]
there's a little bit of backstory on this one..  it was briefly changed for 1-2hours last night, but it didn't look all that great or work well with themes so revil undid this fix.  i did however come up with pretty much this same suggestion as an alt as well though.  ;)

>Or maybe you could also add the hover effect. It would be even better because I like both the new background and link hover effect.

pretty much what i said here also = https://www.steamgifts.com/go/comment/I2Frm4A

**Comment by revilheart** [comment]
You can currently enable the fade effect. I'll add an option to change the background in addition to the effect later.

**Comment by revilheart** [comment]
Hope it's how you guys want it now.

**Comment by gizellos** [comment]
You bet! It's wonderful now. Thanks!

**Comment by gizellos** [comment]
I am just not sure if the option "Fade out visited giveaways." do anything now. The forums seems to be the same no matter if I active it or not.
