### ISSUE TITLE
[Enhancement] Visualized  level progression in the main SG button

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#144]
There could be visualized level progression in the main SG button.

![level progression](https://user-images.githubusercontent.com/2397851/26993721-b6c17482-4d64-11e7-9517-1261004b3a66.png)

**Comment by ldeman** [comment]
+1
i could of used it ~9 levels ago tbh... but still, +1.  xD

**Comment by gizellos** [comment]
Ideman: Yeah, I personaly don't need either to since the level progress is so slow for me that I know very well my percentage. :D But it is cool. :)

**Comment by revilheart** [comment]
Done

**Comment by gizellos** [comment]
Cool, thanks. :)

**Comment by gizellos** [comment]
Could you please show it as if the two buttons were one? I mean the button + the dropdown. Because they look like one button visually. I know the implementation would be a bit more difficult, but it would be better because it would be less confusing.

![level visualize](https://user-images.githubusercontent.com/2397851/27001036-7a5cf870-4dc0-11e7-9b20-3c339487afc5.png)

**Comment by gizellos** [comment]
Or you can disable the hover effect for the left button and set it's color as it is the color for hovered button now. So it would look like this. The hover effect is not so important, anyway.

![2017-06-10_103037](https://user-images.githubusercontent.com/2397851/27001339-00fb33ea-4dc8-11e7-8e3c-91d49092f423.png)

**Comment by revilheart** [comment]
There's no easy way to do this, so I won't be implementing it for now.
