### ISSUE TITLE
[Bug] Recent Username Changes - some names are wrongly generated

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#145]
Some names have added " Add Tag" to the names and urls.

![2017-06-10_035435](https://user-images.githubusercontent.com/2397851/26999037-c55289b0-4d90-11e7-8fac-6c7468723800.png)

**Comment by revilheart** [comment]
Thanks for letting me know, but it's not a bug. The Username History feature now detects changes if you check someone's profile, so what probably happened is that someone checked those profiles while using a script that adds "Add Tag" to the name of the person and it messed the database. I just have to clean the database every now and then. Cleaned it right now.

**Comment by gizellos** [comment]
Ok, it works now. :)
