### ISSUE TITLE
[Bug] Entering GAs changes the size of the button where the level progress is

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#146]
It seems the newest version broke the button where the visualized level progres is. Its size is changing.  Check the gif.
![changing size of the button](https://user-images.githubusercontent.com/2397851/27004779-db532e3e-4e0f-11e7-94ca-459d383e15fa.gif)

**Comment by gizellos** [comment]
Every entering makes the button bigger.

**Comment by gizellos** [comment]
And the default size is bigger than it is supposed to be.

**Comment by revilheart** [comment]
Fixed
