### ISSUE TITLE
[Enhancement] Send the ESGST version when one comments on the ESGST thread

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#147]
I got quite an interesting idea. It could help you to solve some issues more easily. I mean an issues that was already fixed in a newer version than the user have.

So if one wrote a comment on ESGST SG forum, the the script would save also an info about their ESGST version and you could read it then.

It could save it like a hidden element like in the encrypted GAs and there would be an icon in every post (only) in the ESGST thread that would show you the version if you placed your cursor on it.

**Comment by ldeman** [comment]
even better would be if upon entry to the esgst thread it automatically cross-checked what the latest version is, and gives a popup warning "you are currently on an outdated version, please update to the latest version and insure the error still persists prior to reporting your issues."  then it'd save the headache of even telling them to update to begin with.  ^^

**Comment by gizellos** [comment]
Ideman: +1

**Comment by revilheart** [comment]
That's a nice idea.

**Comment by revilheart** [comment]
Implemented @Ideman's idea because it ensures all users have the latest version instead of me seeing each user's version and having to tell them update. And also I don't have to manipulate users' comments that way (I think people would not like me injecting hidden elements in their comments).
