### ISSUE TITLE
[Enhancement] Automatic checking for updates

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#149]
I would like to have the new versions as soon as possible and it is not possible with the minimal 6 hours checking in Tampermonkey.

Therefore I suggest to make an opinion to check for the updates more frequently in the background. There is just a question what interval it should be. I would like just maybe 5 minutes if it is possible (it would be good mainly because of hotfixes).

**Comment by ldeman** [comment]
i personally wouldn't want it to check that often, in fact i'm fine with tampermonkeys 1week default.  you can check manually as much as you want without any limitation.
![peek 2017-06-10 15-41](https://user-images.githubusercontent.com/10275898/27006197-86b6ee4a-4df3-11e7-9d2b-05f3b235b067.gif)

**Comment by revilheart** [comment]
That's a bad idea, it would generate too many requests, and the script is not that constantly updated. Sure, some days, it gets some updates close to one another, but it's not so frequent.
