### ISSUE TITLE
Font on the button with level progress keep changing

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#150]
Since the last update I sometimes can see different blurry font on the button with level progress. 

Edit: It seems to be there always when I enter ESGST settings. Maybe the problem is only there.

![bugged button](https://user-images.githubusercontent.com/2397851/27011568-5286dc4a-4ebe-11e7-866b-4fbefa51e4ca.png)

**Comment by gizellos** [comment]
I can see it always when I go to the RSGST settings.

**Comment by revilheart** [comment]
That's the normal color it has on the account page. Maybe you didn't notice it before because the button was lighter there, but it had to be removed so that the level could fill the entire button.

**Comment by revilheart** [comment]
I believe I can change it though.

**Comment by gizellos** [comment]
I see, then it is a bug of SG itself. Please change it. It looks terrible.

**Comment by revilheart** [comment]
Not a bug, really, try disabling the feature and you'll see that the button is much brighter in the account page because it's selected, which doesn't make the color look bad.

**Comment by gizellos** [comment]
I see but what is the sense of this different style just for one page? If it were on each page, I would understand.

**Comment by revilheart** [comment]
Because the page is selected. It's the same if you go to Discussions, for example. You will see that the Discussions button will be brighter and so will be its color.

**Comment by gizellos** [comment]
Aww, I see now. I just didn't notice it is also different. OK.

**Comment by revilheart** [comment]
Should be better now.
