### ISSUE TITLE
Giveaway Features Failed To Load

### ISSUE THREAD

**Issue by Ryahn** [revilheart/ESGST#151]
Version: 6.Beta.4.6
Console Log
```
GET https://cdn.steamgifts.com/js/prebid_v2.js net::ERR_BLOCKED_BY_CLIENT`
VM1281:1841 DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at getGiveawayInfo (eval at E_c (:3:221), <anonymous>:19219:36)
    at getGiveaways (eval at E_c (:3:221), <anonymous>:19129:24)
    at Object.loadGiveawayFeatures [as load] (eval at E_c (:3:221), <anonymous>:19117:21)
    at loadFeatures (eval at E_c (:3:221), <anonymous>:1833:33)
    at loadEsgst (eval at E_c (:3:221), <anonymous>:1796:9)
    at eval (eval at E_c (:3:221), <anonymous>:412:9)
    at Window.tms_e955d741_f640_4a27_845c_557669a65c79 (eval at E_c (:3:221), <anonymous>:20599:3)
    at <anonymous>:2:398
    at eval (eval at E_c (:3:221), <anonymous>:3:1)
    at eval (eval at E_c (:3:221), <anonymous>:4:3)```

If there is option I can turn of to prevent the error, I can do that.

**Comment by revilheart** [comment]
Are you using other scripts? Maybe a conflict?

**Comment by Ryahn** [comment]
It looks like the Group Identifier script was causing the conflict. Shame, as I like being able to see a list of the groups right on the GA than having to click a button. Thanks for the quick response.

**Comment by revilheart** [comment]
I'm not familiar with that script and I couldn't find it on SG to see if I can fix the conflict. Do you have a link to it?

**Comment by ldeman** [comment]
@revilheart https://github.com/Daerphen/sgscripts (specifically sggroupidentifier.user.js)
sg thread = https://www.steamgifts.com/discussion/SQ56V/

**Comment by Ryahn** [comment]
@ldeman Beat me to the punch. Gotta love being at work :P

**Comment by revilheart** [comment]
Yeah, doesn't look like I can fix this conflict, although I could see if I can implement this. It would have to request the groups on page load, which is something that I try to avoid on this script, but it wouldn't happen on every page and giveaway groups don't change, so it would only need to be requested once and cached forever.

**Comment by Ryahn** [comment]
That would be pretty cool. I know this is for another thing and I will make a new issue for it. But when you load games for their tags or categories (Bundled, Trading Cards, etc). Would it be possible to have it cached? I noticed it does take a minute to get started and complete loading on the page.

**Comment by revilheart** [comment]
They are cached, it taking a bit long to load the page is normal because it's loading the cache.

**Comment by revilheart** [comment]
Added the feature.
