### ISSUE TITLE
[Enhancement] Unmark All Comments Unread

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#152]
for the unmark all comments unread, does it really need to go thru page by page to remove them?  or could it just go into the cache and remove the description id & all associated comment ids without the need to go page by page?

that seems like a waste of bandwidth when it shouldn't even need to make requests to me. ;)

**Comment by revilheart** [comment]
Oh wow, how did I not think of that. *facepalm*

**Comment by revilheart** [comment]
Done

**Comment by ldeman** [comment]
thanks, that speeds up some of my cleanup work on closed out threads that don't matter anymore that i had highlighted and marked all read. ^^
