### ISSUE TITLE
[Bug] Discussions are wrongly formatted in Active Discussions if their title is long 

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#153]
Discussions are wrongly formatted in Active Discussions if their title is long. The title is on new line instead of the same as the star. It didn't occur before. It is a bug of a newer version.

![2017-06-12_145738](https://user-images.githubusercontent.com/2397851/27034889-a61de878-4f7f-11e7-9405-087bfe940e66.png)

**Comment by ldeman** [comment]
it's related to browser width.
![peek 2017-06-12 08-06](https://user-images.githubusercontent.com/10275898/27035215-26305328-4f46-11e7-954b-34d71994ab33.gif)

**Comment by gizellos** [comment]
It's possible but either way it didn't happen until today and my browser is still the same. :)

**Comment by ldeman** [comment]
no sorry, i know.  i was just saying that in case it helps revil to correct it.  ^^

**Comment by gizellos** [comment]
But it is possible that the reason why I didn't see it before is that the newest title of the topic is the longest one in history of the thread. :)

**Comment by gizellos** [comment]
U updated the title. It happens even if the discussion is not highlighted.  Therefoire I believe I would have noticed that before the new version since I look  on the Active Discussions very often.

![2017-06-12_164055](https://user-images.githubusercontent.com/2397851/27039405-27beafd0-4f8e-11e7-855a-cfc972c1daba.png)

**Comment by revilheart** [comment]
Fixed
