### ISSUE TITLE
[Enhancement] Hide giveaways without need to confirm

### ISSUE THREAD

**Issue by jaworek** [revilheart/ESGST#156]
Hi,

Could you add an option to hide all giveaways for a specific game without the need to confirm?
I used this feature in the AutoJoin plugin:
https://github.com/ge-ku/AutoJoin-for-SteamGifts

It would be a useful tool for people who want to hide a lot of games that are not interested in winning.

<img width="494" alt="screen shot 2017-06-12 at 21 25 36" src="https://user-images.githubusercontent.com/22678765/27051249-b223ebdc-4fb5-11e7-87c0-f3861df6b906.png">

**Comment by revilheart** [comment]
Added
