### ISSUE TITLE
[Bug] White color of font in list of groups in group giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#157]
There is white font on grey or light green background in the list of groups in group giveaways.  Therefore the text is not very visible. I guess there is supposed to be some the classic grey color as in the other places.

![2017-06-13_174610](https://user-images.githubusercontent.com/2397851/27092085-7f5f3744-5062-11e7-9613-7beab0a95ac9.png)

**Comment by revilheart** [comment]
The bug is that it shouldn't even appear there. :P

**Comment by gizellos** [comment]
Hehe, yes, it sounds reasonable. :D

**Comment by ldeman** [comment]
it's also oddly on the /winners/ page of giveaways.  i guess that makes sense as a winner, but as the gifter it's a little odd to see.

**Comment by revilheart** [comment]
Fixed
