### ISSUE TITLE
A group doesn't show for me in the Giveaway Grops Loader

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#158]
I don't know why but my most favorite group [Intense Intents In Tents](https://www.steamgifts.com/group/Gd3ux/superintenseintentsintentsgroup) doesn't show for me in the Giveaway Grops Loader. No errors in console.

![2017-06-13_180918](https://user-images.githubusercontent.com/2397851/27092396-7338648a-5063-11e7-82c2-2153db42d223.png)

PS: I resynced both SG and groups.

**Comment by ldeman** [comment]
yeah, in the older pop style its name didn't show either, only photo due to <> being in the title.
"<Intense Intents In Tents>"

**Comment by revilheart** [comment]
Should be fixed.
