### ISSUE TITLE
Sticked GA groups also in group list

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#16]
Hi, could you add support for sticked GA groups also to the [Group list?](https://www.steamgifts.com/account/steam/groups) It would be good because one wouldn't have to go to the "create giveaway section" to choose the groups.

**Comment by revilheart** [comment]
That I can't do because the groups aren't completely listed in that page, so every time you opened that page the script would have to request all pages looking for the groups you have stickied in order to bring them back to the beginning. It's easier and more practical to just use the search function.

**Comment by revilheart** [comment]
Or do you mean an option to simply sticky groups from that page?

**Comment by gizellos** [comment]
Yes just to simply sticky groups there. I think it is the right place for it, anyway.

**Comment by revilheart** [comment]
Ah I get it now. That would indeed be nice, but unfortunately it's not possible, because in order to sticky the groups, I need their `data-group-id`, and this information is not present in that page.

**Comment by ldeman** [comment]
is it possibly to just grab that entire box from a create page and make it a "manage group giveaway stickys" on the settings page, similarly to the way avatar popout works, as an alternative to going to the create page?

(i think the ultimate goal was to avoid the create page. unsure if that's sufficient for the goal if not.)

**Comment by revilheart** [comment]
Possible, yes, but I don't like the sound of that. It doesn't really make sense to me to have that ability outside of the create page, since it relates exclusively to creating giveaways.

**Comment by gizellos** [comment]
It's a pity but never mind, it is not problem.

**Comment by revilheart** [comment]
I actually might have found a way to do it, so re-opening this until the next version. :)

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
I can't see it. :-(::.

**Comment by revilheart** [comment]
I forgot to mention: it only works if you go to the giveaway creation page first. :)

**Comment by ldeman** [comment]
unimportant to me, however i noticed it's not friendly to groups starting with # and that might be important to someone.
![image](https://cloud.githubusercontent.com/assets/10275898/23591178/3c3cc660-01b2-11e7-8119-867e78b8177c.png)

**Comment by gizellos** [comment]
> forgot to mention: it only works if you go to the giveaway creation page first. :)

And do I have to just go or do I have to do something there? Because if just going there is enough, you could just load it in background after going to the group list and then refresh the group list. Theoretically...

**Comment by revilheart** [comment]
Wow, I never saw this last comment. Re-opening then, to fix the # bug.

**Comment by revilheart** [comment]
@ldeman Can you confirm if the "#" bug is still there?

**Comment by ldeman** [comment]
yes, it's still affected/bugged. (16.3)

**Comment by revilheart** [comment]
I don't really remember when I brought avatars to Giveaway Groups Popout back, but I think whatever I did there fixed the "#" bug. I joined that group to test and the button appears fine. Closing this, but would be nice to know if it's now working for you as well, just to make sure.

**Comment by ldeman** [comment]
yes, the #dani group bug is fixed now.  ^^

**Comment by revilheart** [comment]
Thanks for confirming. :)
