### ISSUE TITLE
[Bug] Comments Not Properly Registering

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#160]
opening a topic about it, it's kinda driven me nuts enough to at this point.  xD
(prior relative comments on ticket #147 )

here's a better example then my last gif.  you can see there are no comments according to the counter on /discussions page on a fresh refresh.  but then when visiting the most recent comment that "appears unedited", it shows there clearly was an unread message.

i put "appears unedited" in quote because it's still possible they edited it, but did so under the first 2min mark.  i'm wondering if it's either related to comments being edited or possibly something to do with the op comment somehow.  but either way, it makes the whole point of that counter kinda pointless if it's consistently wrong. =)

![peek 2017-06-13 17-12](https://user-images.githubusercontent.com/10275898/27107207-78b6f874-505c-11e7-9939-e64d76948124.gif)

**Comment by revilheart** [comment]
Is it happening only in a few threads or in all?

**Comment by ldeman** [comment]
honestly there are very few threads i follow close enough to keep it knocked down to 0 comments unread like the esgst thread, but i've seen it happen on at least a half dozen threads.  but it doesn't seem to happen on every single thread either.

**Comment by revilheart** [comment]
Can you do some debugging?

console.log(JSON.parse(GM_getValue(`comments`)).discussions[`TDyzv`].comments);

This should give you all comments from the script's discussions. Check for any irregularities. There should named objects with the comment ID for the amount of comments you have read and and additional object with no name that represents the OP.

**Comment by revilheart** [comment]
Also try this to get the number of read comments that the storage is marking:

```
console.log(Object.keys(JSON.parse(GM_getValue(`comments`)).discussions[`TDyzv`].comments).length);
```

**Comment by ldeman** [comment]
i think i highlighted the main things with mouse.
![peek 2017-06-13 21-52](https://user-images.githubusercontent.com/10275898/27113493-b71e1e00-5082-11e7-8efa-159aa0017e16.gif)

**Comment by revilheart** [comment]
That's what I don't get, everything looks fine. But it says 4347 when that page you're on says 4345, so that would be 4345 + 1 = 4346, not 4347. Can you maybe export that object and send it to me? I can compare it with mine to see if there's a comment that doesn't belong there. If there's no easy way to save it you can use

```
console.log(JSON.stringify(JSON.parse(GM_getValue(`comments`)).discussions[`TDyzv`].comments));
```

to get the text version and copy is a string.

**Comment by ldeman** [comment]
i think this is the string output = https://pastebin.com/yPAgd6iH

**Comment by ldeman** [comment]
and now it's even further off
(4346+1 vs 4349)
![screenshot from 2017-06-13 22-08-42](https://user-images.githubusercontent.com/10275898/27113838-15a692c0-5085-11e7-8673-e31c7f0932a0.png)
https://pastebin.com/r94FKSmA

**Comment by revilheart** [comment]
Ah, there appears to be two properties in your storage called "Count" (leftover from v5) and "undefined" (probably something went wrong trying to get the comment's ID). I'll find a way to purge them and make sure the ID is defined before saving.

**Comment by ldeman** [comment]
sounds great, thanks.  keep in mind it's not just the ESGST thread though, i guess i have several threads doing that.

**Comment by revilheart** [comment]
Let me know if fixed.

**Comment by ldeman** [comment]
much much better.  yes, that seems to of fixed it.  i'd of seen it already by now with the 3-4 comments i watched you make since i updated.  ^^

thank you very much.

**Comment by revilheart** [comment]
Did it fix from the discussions page or did you have to go inside the discussion?

**Comment by ldeman** [comment]
it fixed it from the discussions page view.  =)
i didn't bother checking console after that.

**Comment by revilheart** [comment]
Ah, that's odd, I wouldn't expect that to happen, since the first fix only seem to have applied to inside the discussion. But in any case, I pushed a second fix that should reinforce it from the discussions page.

**Comment by ldeman** [comment]
oh, honestly i think i refreshed the esgst page to read the update log, so that would of probably done it if that's what you mean.  then i went to the discussions page to check for the +1's to start rolling in again since they were rare on esgst thread for me.

but thanks, that 2nd fix should hopefully help to fix all my other threads that do that as well, without having to go inside each and every one.  ^^

**Comment by revilheart** [comment]
That explains it, but yeah, with the 2nd fix you should see the correct count for the others without having to enter them.

**Comment by ldeman** [comment]
excellent!  =)
thanks again
