### ISSUE TITLE
Error in SG pages

### ISSUE THREAD

**Issue by theanyelpes** [revilheart/ESGST#161]
Hi, usually, when I open Steamgifts page, or wishlist page, of groups page... I get this message "1 ESGST features failed to load: Giveaway Features. Check the console (F12) for errors and report them in the script's discussion/GitHub page." So I enter the console I get this:

TypeError: giveaway.panel is undefined
Traza de la pila:
getGiveawayInfo@file:///C:/Users/portatil/AppData/Roaming/Mozilla/Firefox/Profiles/agpjrgw3.default-1472465306527/gm_scripts/ESGST/ESGST.user.js:19399:13
getGiveaways@file:///C:/Users/portatil/AppData/Roaming/Mozilla/Firefox/Profiles/agpjrgw3.default-1472465306527/gm_scripts/ESGST/ESGST.user.js:19294:24
loadGiveawayFeatures@file:///C:/Users/portatil/AppData/Roaming/Mozilla/Firefox/Profiles/agpjrgw3.default-1472465306527/gm_scripts/ESGST/ESGST.user.js:19282:21
loadFeatures@file:///C:/Users/portatil/AppData/Roaming/Mozilla/Firefox/Profiles/agpjrgw3.default-1472465306527/gm_scripts/ESGST/ESGST.user.js:1575:25
loadEsgst@file:///C:/Users/portatil/AppData/Roaming/Mozilla/Firefox/Profiles/agpjrgw3.default-1472465306527/gm_scripts/ESGST/ESGST.user.js:1538:9
@file:///C:/Users/portatil/AppData/Roaming/Mozilla/Firefox/Profiles/agpjrgw3.default-1472465306527/gm_scripts/ESGST/ESGST.user.js:54:9
@file:///C:/Users/portatil/AppData/Roaming/Mozilla/Firefox/Profiles/agpjrgw3.default-1472465306527/gm_scripts/ESGST/ESGST.user.js:42:2

**Comment by revilheart** [comment]
Are you using other scripts?

**Comment by revilheart** [comment]
No answer for almost 2 weeks, so closing this. Feel free to reply if you see this and I'll re-open it.
