### ISSUE TITLE
Sent unsent gift feature sents two keys after a reroll of one GA w/ 2 copies

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#163]
It happened to me more times but it's kinda hard to test it again because I don't make giveaways with more copies too often.  What happened:

1. I made a GA with 2 copies of a game
2. I send both the keys via Sent unsent gift feature
3. One of the winners asked me to reroll
4. I took the key back and asked for the reroll
5. The copy was rerolled
6. I clicked to the button of Sent unsent gift feature
7. It sent two keys instead of the one

Unfortunately, I didn't check the keys so I don't know which keys it was.

**Comment by revilheart** [comment]
Is this the same issue reported on #69?

**Comment by gizellos** [comment]
I don't think so. The old issue was that it said the 1 gift was sent and 1 unsent. Now it sent two gifts to two people.

**Comment by gizellos** [comment]
It still happens. I had a GA that contained 3 keys and I rerolled 1 of them. Script sent all three keys instead just the one from the rerolled GA.

![2017-07-13_210519](https://user-images.githubusercontent.com/2397851/28183342-6a381524-680f-11e7-9134-f42f407f6fca.png)

**Comment by revilheart** [comment]
Can you try exporting your rerolls data to see if the rerolled giveaway is there?

**Comment by revilheart** [comment]
Is the issue that after rerolling a giveaway and using the sender, it still sends to the other winners? If so, that's not really a bug, I mean, if the gifts were already sent, re-sending them doesn't affect anything. But it would be a good idea to enhance the feature so that it detects already sent gifts and doesn't send them again.

**Comment by gizellos** [comment]
> Let me see if I understand this a bit better, is the issue that after rerolling a giveaway and using the sender, it still sends to the other winners?

Yes, exactly and the problem is that it is very confusing since you know that you have, for example, 1 unsent gift and I will write you that it sent 3 gifts.

Do you still need the rerolls data? The link to the GA is [here](https://www.steamgifts.com/giveaway/1FhPd/starter-pack-for-arcane-preraise) and the data are here:

`{"ESGST":"Data","Data":{"users":{"users":{}},"games":{"apps":{},"subs":{}},"Rerolls":["4613172","4615257","4656894","4664715","4664704"]}}`

**Comment by revilheart** [comment]
Nope, I know what it is now, will fix it in the next version, forgot to add it to the last one.

**Comment by revilheart** [comment]
Should be fixed, let me know if not.
