### ISSUE TITLE
[Bug] Disabled Enter button in created giveaways + 33 % chance to win

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#164]
I cannot reproduce this issue again to check the console or make a better screenshot. I went to created giveaways page and I saw disabled enter buttons and  each of the bugged rows had also chance to win 33.33 % there. Not every giveaways had it, though. Just some of them.

![created giveaways](https://user-images.githubusercontent.com/2397851/27139082-560bf484-5122-11e7-9034-e43589f05742.png)

**Comment by gizellos** [comment]
The first GA had about 169 entries and is for lvl 3 and the other about 223 entries and is also for lvl 3. So I don't know why 33.33 % anyway.

**Comment by revilheart** [comment]
I saw this happen once a while ago, but never again. I don't think it's still happening in recent versions. Let me know if you see it again, closing.

**Comment by gizellos** [comment]
Yes, I saw it just once. I will tell you if I see it again.

**Comment by gizellos** [comment]
It seems to be [this issue](https://www.steamgifts.com/discussion/TDyzv/userscript-esgst-v6beta122-new-features-giveaway-train-maker-last-page-link/search?page=33#gKSZoSe) that the user mentioned.
