### ISSUE TITLE
[Enhancement] Stop giveaway filters running away after clicking on an option there

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#165]
If I want to set, let's say, 2 options in giveaway filters, it is quite hard because after I click on one option, the content of the active window will run away and I have to scroll to the giveaway filters. Please fix the filters on one place when I am working with it. The reason is that it will show/hide a lot of giveaways and it will move with the page.

Possible solutions:

1.) Set delay until it will apply the last changed filter. For example, 1 second. So you click on an option and the filters won't apply for 1 seconds and you have time to click on another option. If you select the another the 1 second delay applies again. 

2.) Fix it to the place. So you click on anything and even if lots of giveaways is added the page is still scrolled to the same place.

![ga filters are running away](https://user-images.githubusercontent.com/2397851/27140850-dee7bf6e-5126-11e7-9c1d-254a7605d4c5.gif)

**Comment by revilheart** [comment]
I could add it before the pinned giveaways.

**Comment by revilheart** [comment]
Done

**Comment by gizellos** [comment]
Cool, thanks.
