### ISSUE TITLE
[Bug] Script doesn't show bookmarked giveaways after adding them

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#169]
If I add some giveaways to bookmarks, go to another page on SG, the bookmark icon appear, but after I try to load them, the list is empty. After some time/activity on SG it will show them, though.

No errors in console.

![bookmarked giveaways](https://user-images.githubusercontent.com/2397851/27147662-dce30324-513d-11e7-90b1-427a4ca30948.gif)

**Comment by gizellos** [comment]
Another thing, when I remove them after they show, I can see them next time even if they are not bookmarked anymore.

![2017-06-14_203640](https://user-images.githubusercontent.com/2397851/27148682-6c90ab68-5141-11e7-9b41-dc8e1d7b5b66.png)

**Comment by revilheart** [comment]
But did you reload the page after unbookmarking them?

**Comment by gizellos** [comment]
Sure thing, I was normally browsing SG.

**Comment by gizellos** [comment]
I just tried the issue in OP again and it is behaving quite random. I bookmarked 3 giveaways and make a few tests.

1. First time I tried it, it worked
2. Second time, it showed just 1 giveaway
3. Third time, it showed one  giveaway for a few milliseconds a then it was replaced by another giveaway.

I do it like this: 
1. I go to, for example, wishlist page and click on 3 stars of some giveaways to save them
2. I go to to the [main page,](https://www.steamgifts.com/) and click on the icon of bookmarked giveaways

**Comment by revilheart** [comment]
Did you check the console while performing those tests? Is this still happening? I haven't been able to reproduce this at all. And... do you mean bookmarks? Stars are from Entered Games Highlighter.

**Comment by gizellos** [comment]
Yes, I just tried it four times now and it didn't load any bookmarked giveaways although it knew about them since it showed the icon.

No errors in console at all. I also tried to wait a while after I added the GAs there but with the same result.

![2017-06-20_151811](https://user-images.githubusercontent.com/2397851/27335180-f0fa2774-55cb-11e7-8e77-02d10a1fc2e0.png)

**Comment by revilheart** [comment]
That's very odd. I don't think anybody else is experiencing this, or they haven't reported. I might need your help debugging it later.

**Comment by ldeman** [comment]
ive noticed you have to refresh the page you are on, then open the bookmarked giveaways in order for them to load.  just bookmarking and instantly loading the bookmarks up to insure they took doesn't work.

**Comment by gizellos** [comment]
No it is not a conflict, I just tried to disable all the other scripts. But I noticed it occurs only when I try to check the GAs on the main page. If I go, for example, to the forum, all the GAs loads normally.

**Comment by revilheart** [comment]
Ahh, I think maybe it's filtering the giveaways?

**Comment by gizellos** [comment]
I just wanted to write it. :D It's possible.

**Comment by ldeman** [comment]
yes, seems it is filtering the giveaways.

**Comment by gizellos** [comment]
So please add an opinion to exclude the decrypted GAs from filtering.

**Comment by revilheart** [comment]
It's a bug, I already fixed it and will push the update soon.

**Comment by revilheart** [comment]
Fixed
