### ISSUE TITLE
User defined replies

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#170]
I would like you to add use defined replies to the Comment Formatting Helper. The feature is even here on Github. It would be quite handy.

I would also like if I could post a random reply from a list of defined replies. You can see how I imagine it in the screenshot.

![2017-06-14_220447](https://user-images.githubusercontent.com/2397851/27152233-7f4d82c4-514d-11e7-8fc0-54a61c08cf3f.png)

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
That's pretty cool. Thank you very much for this. I just quickly tested it and it seem to work very well. :)
