### ISSUE TITLE
[Bug] sent giveaways data - Most given away: undefined

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#171]
All games in the statistics sent giveaways data -  Most given away are shown as undefined. No errors in console. I tried to check Clear cache option but it didn't help.

![2017-06-16_165005](https://user-images.githubusercontent.com/2397851/27231744-e3262870-52b3-11e7-934f-e386d481d873.png)

**Comment by revilheart** [comment]
Fixed
