### ISSUE TITLE
[Bug] Enter button for my own decrypted giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#172]
I just made 2 decrypted giveways on [this thread of mine](https://www.steamgifts.com/discussion/xuZnE/pildas-steam-level-100-celebration-train-lvl-3) and I can see enter button for one of them in the list of decrypted giveaways.

No errors in console.

![2017-06-16_193048](https://user-images.githubusercontent.com/2397851/27237847-ec975d18-52ca-11e7-9ec4-18c34e218be3.png)

**Comment by revilheart** [comment]
Is this still happening? I thought I had added something to prevent this.

**Comment by gizellos** [comment]
Yes, unfortunately.

**Comment by revilheart** [comment]
It shouldn't happen anymore for a while now. Can you confirm?

**Comment by gizellos** [comment]
Yes, it seems to work normally. I am closing this.
