### ISSUE TITLE
Endless scrolling doesn't run if the first page have just a few items

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#174]
This is a bug that you already solved many months ago and it is back now. When I go to a list of giveaways and the page 1 has only a few (for me 2 now) items, the endless scrolling doesn't run. It doesn't show the other pages no matter how I scroll. The items are filtered a lot, that's why there are just two.

![2017-06-17_093151](https://user-images.githubusercontent.com/2397851/27251124-4871862a-5340-11e7-85fc-a3a18d72ffca.png)

**Comment by gizellos** [comment]
Please look at this soon. It is very annoying bug. I can see this very often. :(

**Comment by revilheart** [comment]
A workaround until it's fixed: you can pause and resume Endless Scrolling and it should load the next page.

**Comment by revilheart** [comment]
Does this still happen? I cannot reproduce this, I can't even get my page to become so small it's not possible to scroll, even if I filter everything there's still room to scroll.

**Comment by gizellos** [comment]
Yes it still happen, at least yesterday it was still actual. Today I cannot see it because it seems that (some?) filters stopped to work correctly so I always see lots of giveaways. It's another issue, though.

**Comment by revilheart** [comment]
What filters specifically?

**Comment by gizellos** [comment]
I already made [an issue.](https://github.com/revilheart/ESGST/issues/359)

**Comment by revilheart** [comment]
I still cannot reproduce this. Do you get a scrollbar? Or is it not even possible to scroll?

**Comment by gizellos** [comment]
No scrollbar, it is on the contrary, the page gets short when it happens and the footer of SG is very high. But I am not able to reproduce this now either. Maybe it was fixed that you fixed the bug when genres was not filtered?

I will be optimist and close it for now. I hope I am right and it is really fixed. I will tell you if I see it again.

**Comment by revilheart** [comment]
Ok, I cannot even get the page to be that short, my screen might be too small compared to yours. :P

**Comment by gizellos** [comment]
Unfortunately, it is still issue. I just ca see it. No errors in console. 
![2017-08-21_211844](https://user-images.githubusercontent.com/2397851/29534507-8b5f48d8-86b6-11e7-8b27-d67f6dc84581.png)

**Comment by revilheart** [comment]
Ah, your screen gets too small because you hide the ads, I'll enable AdBlocker for SG to do some testing.

**Comment by revilheart** [comment]
Can you please add `console.log(window.scrollY, document.body.offsetHeight, window.innerHeight);` to the end of line 29047?

**Comment by gizellos** [comment]
Yeah, you are right. Do you want me to show you the results after the issue occurs or anytime? If anytime is ok, then it is this.
![2017-08-22_144509](https://user-images.githubusercontent.com/2397851/29566069-c427fe70-8748-11e7-9cc5-dfe9230999e0.png)

**Comment by revilheart** [comment]
When the issue occurs.

**Comment by gizellos** [comment]
Well, when it occurs, it doesn't show anything in console. :-O

I just tried it on the Recommended page.

**Comment by gizellos** [comment]
OK, I have it. It is 0 5734 960.

**Comment by gizellos** [comment]
The second number is always different, though. Last time I saw there 0 3994 960.

**Comment by revilheart** [comment]
I have a theory. Does it only happen if the page you're opening does not have a Game Categories cache yet? For example, when it happens, if you refresh the page does it then load the second page normally?

**Comment by gizellos** [comment]
It's possible. I just went to the main page and there was 0 results, I pressed F5 and page 2 was loaded, another F5 and even page 3 was loaded.

![ga page](https://user-images.githubusercontent.com/2397851/29747812-2f280c4a-8b06-11e7-9d1c-988d373d6749.png)

**Comment by revilheart** [comment]
Now it should definitely be fixed.

**Comment by gizellos** [comment]
It seems so but it broke the filters unfortunately. It is not filtering genres. I just tried these filters.

![2017-08-27_222056](https://user-images.githubusercontent.com/2397851/29753638-10bf1a26-8b76-11e7-81ea-3cff24410d7c.png)

Also the numbers of pages can get bugged. When I am at the top of the list of GA, I can see that I am on page 4.

![2017-08-27_222245](https://user-images.githubusercontent.com/2397851/29753644-44674632-8b76-11e7-8b88-f540bda44a57.png)

I have to go to bed now. I will try it more tomorrow.

**Comment by revilheart** [comment]
The filters should work correctly again.

I don't think the page is bugged. If your top of the page is also the bottom (the page has no scrolling bard) the last page will appear, that's normal.

**Comment by gizellos** [comment]
Yes, you are right. Thanks.
