### ISSUE TITLE
Automatic adding chosen encrypted giveaways to all comments

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#175]
I would like to automatically add chosen encrypted giveaways to all my new posts. It could work like this:

1. When I am creating a new private giveaway or editing it, I could check a checkbox something like "Hide this giveaway in all your posts."
2. When I send any post on SG, it will add/hide there also all active giveaways that I marked like this.
3. There could be also a possibility to temporary disable it in the comment helper. Maybe I could see a list of all encrypted giveaways I marked for it, but it is not necessary. 

Or it could be done like this:

1. When I click on the star in the format helper to add a new encrypted GA, there would be also the checkbox like "Hide this giveaway in all my posts." and it would add the GA I put there to the script DB.
2. Below the text field for entering the code, there would have to be the list of all active giveaways I encrypted and beside their names there also could be a button for disabling it for the specific giveaways.

**Comment by revilheart** [comment]
I believe using Saved Replies for this is better. You can save a reply with the list of giveaways and then use it on the posts you want. I don't like the idea of the script automatically adding content to your reply, so closing this.
