### ISSUE TITLE
[Bug] Rule Checker attempts old names instead of new names.

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#176]
i got a winner who i apparently have scanned with the rule checker in the past as a different name, and now attempting a new scan on it, it checks sgtools with their old name instead of the current name giving profile errors.

this particular person is already known in the namechange database as well.

**Comment by ldeman** [comment]
i've even cleared out my rule check results between the namechange, so that error must be from a different section of the storage.

**Comment by revilheart** [comment]
Should be fixed.

**Comment by ldeman** [comment]
yes, that seems to of done it for the user that triggered the issue at least.  ^^
