### ISSUE TITLE
[Enhancement] "Activate a key" button

### ISSUE THREAD

**Issue by Simvol8** [revilheart/ESGST#177]
Is it possible to add the button with this link: steam://open/activateproduct on this page: https://www.steamgifts.com/giveaways/won ?
Somewhere here: ![screenshot-1845](https://user-images.githubusercontent.com/29492815/27257374-9d620168-53dc-11e7-973b-007f6a25b00d.jpg)

**Comment by SquishedPotatoe** [comment]
@Simvol8 this is what i use to click the icon already present.
`document.addEventListener('copy', function(e) {
	if (/^[\d\w]{5}(\-[\d\w]{5}){2}$/.test(e.target.value)) {
		window.location.href = "steam://open/activateproduct";
	}
});`

**Comment by gizellos** [comment]
+1

**Comment by revilheart** [comment]
Added
