### ISSUE TITLE
Level Progress Visualizer - Estimated level progress after the end of all current GAs

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#181]
Especially lowbies could appreciate this feature. The Level Progress Visualizer would also visually show the estimated level progress after the end of all current GAs.

Info in numbers could be also added to the tooltip that tell us the exact percentage.

![estimated exp progress](https://user-images.githubusercontent.com/2397851/27332169-1aeda7a0-55c1-11e7-8fa5-78c9f075274d.png)

**Comment by revilheart** [comment]
Added
