### ISSUE TITLE
[Enhancement] Filter possible duplicates of Decrypted GAs while I am in Messages

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#184]
If someone answer me to two and more posts where I put a decrypted giveaways. The Decrypted giveaways list show me them separately in Messages. 

I suggest to remove the duplicates if there are some.

![2017-06-20_161059](https://user-images.githubusercontent.com/2397851/27337714-86c09aac-55d3-11e7-97c7-35299970936f.png)

**Comment by gizellos** [comment]
Or maybe removing the list from messages could be also a solution.

**Comment by revilheart** [comment]
Should not happen anymore.
