### ISSUE TITLE
[Bug] Goto first unread comment broken (6beta8.3)

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#185]
clicking it just gives a [Violation]

[Violation] 'click' handler took 199ms
[Violation] 'click' handler took 194ms
[Violation] 'click' handler took 240ms
[Violation] 'click' handler took 249ms
[Violation] 'click' handler took 225ms
[Violation] 'click' handler took 253ms
[Violation] 'click' handler took 256ms
[Violation] 'click' handler took 183ms
[Violation] 'click' handler took 228ms
[Violation] 'click' handler took 198ms
[Violation] 'click' handler took 168ms
[Violation] 'click' handler took 169ms
[Violation] 'click' handler took 165ms
[Violation] 'click' handler took 189ms
[Violation] 'click' handler took 169ms
[Violation] 'click' handler took 165ms
[Violation] 'setTimeout' handler took 291ms
[Violation] Forced reflow while executing JavaScript took 270ms

(each of the 'handler took' was a click attempt)

**Comment by ldeman** [comment]
ahh it works if the op is marked as read, but it's bugged from ignoring the op now.

**Comment by revilheart** [comment]
Should go correctly to the OP now. I'm not sure what those violation bugs are, let me know if they're still happening.

**Comment by ldeman** [comment]
thanks, that seems to of done it.  =)

and those weren't actual errors, just verbose console info that's not usually shown.   i had just noticed each click had added "1 items hidden by filters" so i changed the console to a verbose view to see those.
