### ISSUE TITLE
[Bug] Detection of up-top-date version on the ESGST topic is not working correctly

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#187]
I updated to the new version and went to the ESGST topic and it said me that I didn't have up-to-date version. After that I checked the version and it confirmed that I really had the current version.

![2017-06-21_211642](https://user-images.githubusercontent.com/2397851/27402525-365c661e-56c7-11e7-80ca-dcf5380fbe45.png)

**Comment by revilheart** [comment]
GitHub sometimes takes a few minutes to update the script, while the discussion is updated instantly, so not really a bug. What version are you on?

**Comment by gizellos** [comment]
I was the previous when it was actual. But now with the latest it seems to be OK. I am closing this.
