### ISSUE TITLE
[Bug] Categories doesn't work with Non-English.

### ISSUE THREAD

**Issue by kaoyusu** [revilheart/ESGST#189]
Categories's description is different on different languages. You could use id to identify categories or add &l=en to get English description.
http://store.steampowered.com/api/appdetails?appids=730&cc=us&filters=categories&l=cn
http://store.steampowered.com/api/appdetails?appids=730&cc=us&filters=categories&l=en

**Comment by revilheart** [comment]
Oh I thought cc=us already did that, will add it later.

**Comment by revilheart** [comment]
Are you sure that's the case though? I see no difference in those links.

**Comment by kaoyusu** [comment]
Yes, I'm sure cc=us doesn't work on my computer.
> {"730":{"success":true,"data":{"categories":[{"id":1,"description":"\u591a\u4eba"},{"id":22,"description":"Steam \u6210\u5c31"},{"id":28,"description":"\u5b8c\u5168\u652f\u6301\u63a7\u5236\u5668"},{"id":29,"description":"Steam \u96c6\u6362\u5f0f\u5361\u724c"},{"id":30,"description":"Steam \u521b\u610f\u5de5\u574a"},{"id":35,"description":"\u5e94\u7528\u5185\u8d2d\u4e70"},{"id":8,"description":"\u542f\u7528 Valve \u53cd\u4f5c\u5f0a\u4fdd\u62a4"},{"id":15,"description":"\u7edf\u8ba1"}]}}}

**Comment by revilheart** [comment]
Should work well now, let me know if not.
