### ISSUE TITLE
[Bug] Created filter is not working

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#190]
Created filter is not working for me. When I set it to hide the created giveaways, it normally shows them among the other GAs. When I set it to show only created GAs, it shows nothing.

I can is it in [Group GAs](https://www.steamgifts.com/giveaways/search?type=group) and I enclose filter options that were used.

No errors in the console.

![2017-06-24_224705](https://user-images.githubusercontent.com/2397851/27511856-194a5116-592f-11e7-8b42-96015d703b96.png)

**Comment by revilheart** [comment]
Is this still an issue?

**Comment by gizellos** [comment]
I cannot check it now but I think it is OK now. I am closing this and if it happens again, I will re-open it.
