### ISSUE TITLE
GA filters presets

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#192]
I would love to have the possibility to make my own presets of giveaway filters. It means that I would set some options in giveaway filters, save it using names and then I could quick switch between the them.

**Comment by gizellos** [comment]
![2017-07-10_182122](https://user-images.githubusercontent.com/2397851/28028502-033bb1d8-659d-11e7-8299-99950187950a.png)

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Very nice. It's very handy. Thanks for this and Quick disabling filters. :)
