### ISSUE TITLE
[Enhancement] ITAD data pull

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#194]
you've gotten me down to just 5scripts total that function on SG in any way, so i mine as well just list the last couple that haven't been suggested (afaik).  you're welcome to ofc deny any of these for any reason, i'll separate each of them into different "issues".

this being one of them.  it basically pulls bundle history & itad current known lowest price on giveaway pages.

![peek 2017-06-25 15-44](https://user-images.githubusercontent.com/10275898/27519618-4a0398a6-59bd-11e7-8f5b-3f91602beef4.gif)
(notice they link to the appropriate itad page also)

**Comment by gizellos** [comment]
Yeah, it would be great.

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Cool. Just there is type: everyone. I am not sure if everyone is correct. I am used to call them Public.
