### ISSUE TITLE
[Enhancement] Next/Back Hotkeys (for trains)

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#195]
i'm currently using a dirty version i hacked together that was generic to work with all websites, but would prefer more keywords and one less installed script.

example keywords wanted "Next, Forward, More, >, >>, >>>"  (and ofc the reverses of those & other common used ones i can't think of)

chunk of the dirty script so you get a better idea what i mean.
```

  //############## THESE CONTROL WHICH KEYS ARE USED ##############
  var prevAccessKey = ",";
  var nextAccessKey = ".";
  var prevInNewWindowKey = "<";
  var nextInNewWindowKey = ">";

  
  var allLinks, thisLink;
  var nex = /next/, fr = /forw/;
  var pre = /prev/, bac = /back/;
```

like the other suggestion, you're welcome to close/ignore if you want.  ;)

and actually the other 2 scripts are "SG Entered / Created / Won Giveaway Page" (suggested today already) & "RaChart™ Enhancer" (doesn't need further explanation, so not bothering with issue ticket)

---

edit:  now i see how easy it is to add more for myself after submitting, but it's not even a SG script so i'm sure others would want it.

**Comment by revilheart** [comment]
Added, but I'm going to have to ask for a bit more specifics about RaChart Enhancer. Is the Game Categories extension that I added to tables a while ago enough?

**Comment by gizellos** [comment]
It is enough for me for now. Just maybe you could also add the average price of cards (you could add it to giveaways as well).

**Comment by ldeman** [comment]
thanks for hotkeys.

and yes... if i actually turn on the tables category (now it is), it shows me "Owned" category, so technically that works just the same, and i can remove literally all other SG scripts.  idk when that one was introduced, it's one i actually overlooked.  =)

**Comment by ldeman** [comment]
does the "owned" tag go off of steam store login or api method though?  hoping api key if it exists in the field, as it's faster at catching newly owned content.

**Comment by revilheart** [comment]
Everything still works like before: the script tries through API first, if it's saved, and then uses store login (store login is always used because it provides ownership info about packages and some other games that are often missing from the API).

**Comment by ldeman** [comment]
excellent, thanks again!  =)

**Comment by ldeman** [comment]
first train i ran across to test has ">" as the next button and it doesn't seem to be an acceptable for the hotkeys.
https://www.steamgifts.com/discussion/enmwB/here-comes-the-train

**Comment by revilheart** [comment]
If you're not pressing the Ctrl key they should open in the same window.

**Comment by ldeman** [comment]
oh okay, my bad.  i misread the tooltip in settings was all.  =)
it's working just fine.  thanks again!
