### ISSUE TITLE
Missing help text in Manage data

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#196]
Some options show "Undefined" instead of the help text in Manage data.

![2017-06-26_160427](https://user-images.githubusercontent.com/2397851/27543187-c181f6f8-5a89-11e7-8f80-c4e80bd4fbf2.png)

**Comment by ldeman** [comment]
also has undefined inside sent giveaway data  (still or again, i can't remb if this was solved alrdy)

**Comment by gizellos** [comment]
Still.

**Comment by revilheart** [comment]
I removed the tooltips altogether because they were redundant themselves.
