### ISSUE TITLE
Giveaways tools - export, search & replace, and so on

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#197]
The idea is that in created giveaways, every active giveaway would have a checkbox (or you could choose them in another way) and we could choose giveaways we want to work with.

Then we  could choose what we want to do with them. I would like these features:

1. Export them to RachartTable
2. Export them to a list of links
3. Export them to text using my own format (something like the generated text to the trains)
4. Search and replace a text in them

It would look similar to the list of scripts in  Tampermonkey.

![2017-06-26_162715](https://user-images.githubusercontent.com/2397851/27544099-653a0f40-5a8c-11e7-8b59-0e05dfe1d086.png)

**Comment by revilheart** [comment]
Can you be a bit more specific about item 4? You mean replacing a text in their description?

**Comment by gizellos** [comment]
I wanted to use it mainly for bump links in every wagon in a train, so the giveaways descriptions would be, for example, "previous - bump - next" and I would replace the word bump for the link to the thread. Also I would use it for typos, so if there was sentence "Check my youutube channel" in every giveaway in a train, I would replace youutube with youtube.

So there would be two text fields search and replace. It would work the same as the classic Search and Replace function.

**Comment by revilheart** [comment]
Do you have an example of a RaChart table?

**Comment by gizellos** [comment]
Do you mean a up-to-date RaChart table? [Here,](https://www.steamgifts.com/discussion/LjFC6/indiegala-hump-day-bundle-43) for example. Just there would have to be another column with the link to the giveaways. I personally, would remove the bundled column and put the column instead.

**Comment by revilheart** [comment]
No, I mean just an example of a RaChart table, so I know how to export the giveaways. But that information isn't available on the created page (ratings, cards, bundled and retail price). Isn't there a simpler format?

**Comment by gizellos** [comment]
Do you mean a code? It could be like that, for example.

`Steam | Rating | Cards | Level | Points | Giveaway
:-|:-|:-|:-|:-|:-
[Draw Slasher](http://store.steampowered.com/app/418270/) | 76 % (4145) |  [Yes](http://www.steamcardexchange.net/index.php?gamepage-appid-384190)  | 4 | 15 | [Here](https://www.steamgifts.com/giveaway/mK9Ti/)`

There could be also toggles to activate each the column. 

I found an article about creating RaChart tables [here](https://www.steamgifts.com/discussion/KnfXs/how-to-create-a-giveaways-tablechart-in-a-few-clicks) and a table creator script [here.](https://www.steamgifts.com/discussion/dE8ro/userscript-giveaways-tablechart-creator-06) You can inspire there.

**Comment by revilheart** [comment]
You ignored what I said about ratings, cards, bundled and retail price information not being available in the created page though.

I added a feature called Giveaways Manager that lets you do most of what you want with this issue, but I didn't explicitly added a "Export to RaChart table" option. But you can use the custom format option and place the table format you want there.

Still, ratings, cards, bundled and retail price are not currently supported, because those would require requesting stuff.

**Comment by gizellos** [comment]
> You ignored what I said about ratings, cards, bundled and retail price information not being available in the created page though.

Yes, but they also were not on all the other pages and you added them there so I din't see a problem. Game categories in lists of giveaways produce hundreds or thousands requests per week and it is not a problem so I really don't understand why there could not be several other requests when someone needs them once a time. The functions for the requests already are in the script so using them should not be a problem for you, should it? They even wouldn't have to be cached or anything.

But it is ok as it is. I like it very much. Thanks.

**Comment by revilheart** [comment]
It's not about requests, it's about complexity. I'll have to rewrite the functions because they work in a specific way. And I said "not currently supported", I didn't say I wasn't going to implement it.
