### ISSUE TITLE
[Feature Request] Add "Sort by entries" and "Sort by points/cost" buttons

### ISSUE THREAD

**Issue by Ack0** [revilheart/ESGST#198]
I found this[1] script and it has two really cool sort functions: sort by entries and sort by points/cost.
Would be awesome if these could be added to ESGST.

[1] https://greasyfork.org/en/scripts/28791-heroboy-s-steamgifts-one-click-entry

**Comment by gizellos** [comment]
I think that filtering by chance does what you want, just it is much more accurate than filtering  by just entries.

**Comment by Ack0** [comment]
I know, but sort by points and entries are useful too.

**Comment by revilheart** [comment]
Added a Giveaways Sorter feature, you can now sort by a lot of different things.
