### ISSUE TITLE
[Bug] Send unsent gifts - a missing word in a link

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#199]
There is a link to [the winner giveaway page](https://www.steamgifts.com/giveaway/D3BHL/karakara/winners) beside the name of the winner. Text of the link is not a word but just an underlined empty space in brackets.

![2017-06-27_125911](https://user-images.githubusercontent.com/2397851/27584594-e58a96a4-5b38-11e7-80ea-34ca28c2ce10.png)

**Comment by ldeman** [comment]
i got this around 20mins ago also.
![screenshot from 2017-07-03 10-40-44](https://user-images.githubusercontent.com/10275898/27800385-d24f3b4e-5fde-11e7-954f-92f809b469df.png)

then shortly after that my sdd was being ate up, then a few moments later tampermokey had claimed something along the lines of "there were inconsistencies in the data and the extension database has been wiped".   it's not the first time i've seen this weird error before either.   at the time it looks as if all scripts have been completely wiped away, however the solution is to simply exit chrome fully properly, and allow the background process to take around 10mins to properly exit.  then once chrome is launched, everything is there and fixed.

but that leads me to believe there's a memory leak somewhere, and these issues are side-effects of said leak.

**Comment by revilheart** [comment]
Rewritting Unsent Gifts Sender is next in my queue after finishing to rewrite some user features I'm currently working on. Maybe I'll find the leak then.

**Comment by ldeman** [comment]
sounds great =)

**Comment by revilheart** [comment]
Fixed the missing word, let me know if you are still running into issues with it.
