### ISSUE TITLE
[Enhancement] A guide for the Train maker

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#200]
Please write a guide for the Train maker. It is quite confusing and I am really not so sure how it works. I screwed up 3 giveaways because it and without results.

**Comment by ldeman** [comment]
+1  it's probably really easy to use, but it looks rather complicated.

**Comment by revilheart** [comment]
I thought I wrote everything you need to know in the new giveaway page and the GitHub page, not sure what else I can add.

You simply fill the details of the giveaway and click on "Add Wagon". Then if you want the giveaways to be linked, you enabled "Connect wagons." and add the connection style to the description. When you're done, click "Create Train" and wait.

What confused you? And how were the 3 giveaways screwed?

**Comment by gizellos** [comment]
I screwed them because I filled the first giveaway, put the description there, clicked on add vagon (it showed number one in white color - this possibility is not mentioned in the description about the colors) and then clicked to Create Giveaway. Then tried it again with another game with adding "create train" in the beginning and the third one was another combination of the possibilities. 

I think I understand the principle now. However I think the game and the key(s) text fields are supposed to be empty after I click on "Add Vagon", are't them? It would make sense like this. 

> I thought I wrote everything 

You didn't write anything about how to use it. You just wrote which features this feature has.

The guide how to make a train could look like this - for example:

1 Enable "Connect wagons.
2. Fill the details of the giveaway and add the connection style to the description  (you can use templates for it).
3.  Click on "Add Wagon".
4. When you're done, click "Create Train" and wait.

**Comment by revilheart** [comment]
The colors are mentioned right below the trash icon:

> Wagons successfully created will turn green, wagons successfully connected will be strikethrough and wagons that were not successfully created will turn red.

The GitHub page specifies that to create a train, "Connect wagons." must be enabled and that each giveaway must be edited individually before adding it as a wagon. Hitting "Create Train" was pretty self explanatory for me. The GitHub page also has an image that exemplifies the creation of a train.

But I'll add a tooltip just in case someone else didn't understand the GitHub page and the instructions in the new giveaway page.

**Comment by gizellos** [comment]
> The colors are mentioned right below the trash icon

Sure, but the color was white and was not strikethrough. The info about white color is not there.

I think that it is also very confusing that feature called "Train Maker" can be used also for giveaways that are not in a train.  Because of it the interface is complicated and not all makes sense there for people who don't know how it works. For example the buttons "Create Train" and "Empty Train" - how can be there a button for creating or emptying a train when I disabled the option "Connect wagons."? I understand that it is for the case when you need to make just multiple giveaways but giveaways that are not connected cannot be called a train. 

I suggest to split this feature to two - one for creating trains and the other for creating multiple giveaways.

**Comment by revilheart** [comment]
Yes, but the white color is the default color, so there's no need to add info about it there.

Why would I split a feature in two, when the two separate features would do the exact same thing? That's what doesn't make any sense. If you don't want the giveaways to be linked, simply disable "Connect wagons." and that's it. What's so hard to understand about that? Just because it's still called "train", that makes the interface complicated? The definition of a train doesn't have to be literally applied here.

**Comment by revilheart** [comment]
I could just call the entire feature Giveaway Maker though, and change "Connect wagons." to "Create a train.". That would make more sense.

**Comment by revilheart** [comment]
Hope it's better now.

**Comment by gizellos** [comment]
It's better but what about "Multiple Giveaway Maker"?

**Comment by revilheart** [comment]
I think "multiple" is an unnecessary word. Giveaway Maker already lets you know that it's a mechanism to make giveaways. And I'd rather not rename the feature again.

**Comment by gizellos** [comment]
It's just about how it looks when you imagine the hierarchy of the page. The whole page [Create a new giveaway](https://www.steamgifts.com/giveaways/new) is in fact a Giveaway Maker. It could be called like that and it would be valid.

So now the hierarchy is like this: 
a giveaway maker page contains a tool called giveaway maker and a tool for creating single giveaways. 

I think the logical hierarchy can be only like this: 
a giveaway maker page contains a tool called multiple giveaway maker and a tool for creating single giveaways. 

But it is not so much important. It's OK if you don't change it.

**Comment by revilheart** [comment]
I disagree with that logic. "Maker" to me applies to tools, and the page isn't a tool, it's a page. So for me it goes like "a page to create giveaways has a tool called giveaway maker that can be used for creating multiple giveaways".
