### ISSUE TITLE
[Enhancement] Show my chance to win instead of their chance to win

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#202]
I suggest to show my chance to win a giveaway instead of the chance to win of users who entered the giveaway. I think just this way it makes sense since the info that I want to know is what would be my chance to win a GA if I entered.

So if there is a GA with 3 entries, the chance to win for me is 25 % and not 33,33 % as it shows now.  It would apply only for giveaways that I didn't enter - it would add +1 to the amount of entries in the formula. My own giveaways should have to be excluded since I cannot enter them anyway.

**Comment by revilheart** [comment]
Added
