### ISSUE TITLE
[Bug] If the screen is too width, scrolling removes buttons from the floating panel

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#203]
If the screen is too width, scrolling removes buttons from the floating panel. It is like that in ESGST settings. It works normally if I made the screen wider, though.

![missing buttons when scrolling](https://user-images.githubusercontent.com/2397851/27596773-d820cf06-5b60-11e7-842b-6613d265251f.gif)

**Comment by revilheart** [comment]
Are you in the latest version? Because it's working fine here.

**Comment by gizellos** [comment]
Yes I use use the latest one. I use resolution 1920/1080. The bigger width, the more buttons are  missing. It is because they move the the right side and disappear there. Check the gif.

![missing buttons when scrolling 02](https://user-images.githubusercontent.com/2397851/27599818-320c82d6-5b6a-11e7-8767-53c419d0f1d9.gif)

**Comment by gizellos** [comment]
It seems to be bugged for me also in discussions. Pagination and refresh and pause buttons are disappearing for me. :(

**Comment by gizellos** [comment]
> Fixed a style issue in Fixed Sidebar/Fixed Main Page Heading for changing-width sidebars/descriptions (closes #117).

Maybe this change broke it?

**Comment by revilheart** [comment]
It's definitely related to that change,  but I'm trying to understand why it's happening to you and not to me.

**Comment by revilheart** [comment]
Can you type "document.documentElement.clientWidth" in the console and tell me what number it outputs?

**Comment by gizellos** [comment]
1903

**Comment by gizellos** [comment]
I am not sure when it happens to me. I tried also disable uBlock and the other scripts and it is the same.

**Comment by revilheart** [comment]
I already found the issue.

**Comment by revilheart** [comment]
Fixed

**Comment by gizellos** [comment]
It works, thanks. :)
