### ISSUE TITLE
[Bug] Missing enter button in decrypted giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#204]
I found a decrypted GA [on the ESGST forum](https://www.steamgifts.com/discussion/TDyzv/userscript-esgst-v6beta143-new-features-createdenteredwon-giveaway-details-itad-info/search?page=33#E5h82ZH) and I noticed there was not the enter button. In console there are numbers like 80, 82, 107, and so on.

![2017-06-27_214711](https://user-images.githubusercontent.com/2397851/27606952-816510b0-5b82-11e7-855e-3c68a2558ec5.png)

**Comment by gizellos** [comment]
![2017-06-27_215023](https://user-images.githubusercontent.com/2397851/27606976-a0e4e6a4-5b82-11e7-91bc-b19d4b7b4241.png)

**Comment by revilheart** [comment]
Fixed
