### ISSUE TITLE
[Bug] Giveaway template with precise times adds an extra 24 hours

### ISSUE THREAD

**Issue by GOBsNotOnBoard** [revilheart/ESGST#205]
I just tried using a giveaway template for the first time, and unfortunately I didn't catch this bug until after I had created all of my giveaways. I created a giveaway from 7:30pm last night to 7:30am this morning and saved that as a template. The bug is that all the other giveaways that I applied the template to added an extra 24 hours, so they won't end until 7:30am tomorrow.

I just tested creating some more templates, and the bug seems to occur if I set the giveaway to run overnight but less than 24 hours long. It also occurs if I set the giveaway to 36 hours (i.e. the template runs for 60 hours). It doesn't occur if I set it to exactly 24 hours, though.

**Comment by ldeman** [comment]
is it maybe a precise end hour you're trying to end on?   i just created 5x (4 from template) 40hour long ones and didn't have that occur for me.  --  i'm wondering if it might have something to do with ending before or after noon, or maybe there is a specific hour that's triggering it to do that.

(started around 7:15-7:20am today / end time 11:00am 30th -6GMT)

**Comment by GOBsNotOnBoard** [comment]
I'm sure what the exact parameters are that trigger it, but I am using precise start and end times.

I just tested a few more that all triggered the bug:

start: 11pm today / end: 12am 6/29 - should be 1 hour long, but applying the template it ends 12am 6/30
start: 11am today / end: 12am 6/29 - 13 hours long, but template ends 12am 6/30
start: 11pm today / end: 12pm 6/29 - 13 hours long, but template ends 12pm 6/30

**Comment by ldeman** [comment]
sorry, i wasn't able to replicate any of those issues.  hopefully revil can still figure it out for ya though.  ;)

**Comment by revilheart** [comment]
> start: 11pm today / end: 12am 6/29 - should be 1 hour long, but applying the template it ends 12am 6/30

When did you create the giveaway? Because if you created the giveaway after 11pm today, then the giveaway obviously cannot start today, so the script will find the closest 11pm, which is tomorrow. Therefore the giveaway will run from 11pm tomorrow to 12am the day after tomorrow (30).

Are the giveaways adding 24 hours only to the end time? Because the expected behavior is that it adds that time to the start time as well.

If you want a giveaway to end exactly at the time and day you want, you have to disable precise start time if you create the giveaway after the time.

**Comment by GOBsNotOnBoard** [comment]
> When did you create the giveaway?
I created it around 9am today, so I wasn't trying to create it after the start time.

> Are the giveaways adding 24 hours only to the end time?
Yes, only the end time is adding 24 hours. The start time is unaffected.

**Comment by revilheart** [comment]
Ah, I was just able to reproduce it. Fixed.

**Comment by GOBsNotOnBoard** [comment]
It's still occurring for me.

**Comment by revilheart** [comment]
Are you sure you're using the latest version?

**Comment by GOBsNotOnBoard** [comment]
Lol. It might help if updated. Working now. Thanks!
