### ISSUE TITLE
[Bug] Different appearance of Highlighted Discussions

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#208]
If I am on the main SG page, Highlighted Discussions shows me more stuff that when I run it from the topics.

See the attached picture.

![highlighted discussion](https://user-images.githubusercontent.com/2397851/27696416-d26dbee2-5cf1-11e7-8e1e-53bcff21fb41.png)

**Comment by revilheart** [comment]
Should be fixed.
