### ISSUE TITLE
Button Create Giveaway is not working

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#211]
Button Create Giveaway is not working. When I click on it, it just refresh the page.

In console, there is this:

test
test1

**Comment by ldeman** [comment]
that's strange.  i just tested all 3x of them working just fine.  it does however refresh if all the information is not filled out.

tested top create, bottom create, create after review, & enabled giveaway maker for an additional create test (top create).

**Comment by gizellos** [comment]
I tested it 3 times as well. I used templates. Maybe that's the reason for it. I will try it again.

**Comment by gizellos** [comment]
It is really strange. It seems to be kinda random.

I tried today and it didn't work (the page even didn't refresh, just the text fields were emptied).
Then I tried it without templates and it worked well. So I though that templates broke it.
Then I tried it again with the same template and it worked normally.

**Comment by revilheart** [comment]
Was this maybe related to the date being outdated?

**Comment by gizellos** [comment]
I don't know but I think it is possible. I used the button a few times today and it worked well. I am closing this.
