### ISSUE TITLE
[Enhancement Upgrade] make last page link accurate

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#212]
rather then having it go to "page=999999999" have it calculate from the bottom comment count field divided by 25 rounded up to the nearest page number.  ;)

that bottom counter is raw comment count (25 per page), and the top counter is total comment count.

![screenshot from 2017-06-30 19-27-16](https://user-images.githubusercontent.com/10275898/27757692-73493764-5dca-11e7-93d6-a33efbeec4b0.png)

**Comment by gizellos** [comment]
I think the problem is that the script sometimes cannot know how many comments is there because it shows only first X pages. (you are on the last page so the script can read it, but if you were on page 1 and there were just first 5 pages, the script could not read it).

**Comment by ldeman** [comment]
no, look at the bottom green highlighted text across the very bottom of the page.  that counter is there even on page number 1.  it's simple math beyond that (the math shown inside of the calculator.

**Comment by gizellos** [comment]
Oh, you are right. I didn't know there is the information. Good you noticed that.

**Comment by revilheart** [comment]
Done

**Comment by ldeman** [comment]
very nice, thanks again.  ^^

**Comment by gizellos** [comment]
I am just fascinated that no one except Ideman noticed the sentence with the count of results. :D

**Comment by ldeman** [comment]
@gizellos that's why i was so confused as to why the site doesn't just do it.  i was told it was eating up system resources to simply figure out what the last page was.  well the serverside shouldn't be the one doing the calculations anyways, the server could of simply had the clientside do the math instead of fully removing the feature from 100+ page discussions...  i guess cg didn't want to bother though.
