### ISSUE TITLE
[Enhancement] add link to steamcardexchange to Trading Cards game category indicator

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#213]
Could you please add links to steamcardexchange to Trading Cards game category indicators? So for example the indicator for the game A bird Story would be link to [this page.](http://www.steamcardexchange.net/index.php?gamepage-appid-327410)

![2017-07-01_092407](https://user-images.githubusercontent.com/2397851/27760091-50bc27a4-5e3f-11e7-961d-03d8829bd175.png)

**Comment by revilheart** [comment]
Done
