### ISSUE TITLE
Giveaway creator was not able to create giveaways for train

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#215]
I tried to make a train, did everything like I was supposed to and it didn't create all 19
 giveaways (vagons were red). I don't know why and in console, there was just the two tests words (test and test 1 I think).

It was really a serious problem for me since I redeemed the keys from the bundle sites and deleted links to the bundles and serials from my serials text file.  Therefore I suggest this:

1. Find out and fix the bug that causes that
2. Try to log the reasons for failing creating giveaways and write it to the page after the attempt fails
3. If creating giveaways fails, let us to export the names of games + serials to a text file or something like that, so that we could copy/paste it to new giveaways.

![failed vagons](https://user-images.githubusercontent.com/2397851/27763104-e5a30cfa-5e7d-11e7-8636-4987618ac3ad.png)

**Comment by gizellos** [comment]
I tried it again and it I may know what the problem is. The problem may be the date of begining of the giveaways because if the time is earlier than the current time, the giveaways cannot be created. I suggest update the time of the start after one clicks on Create giveaways.

Please fix this ASAP since the feature is really cool and we cannot use it.

**Comment by revilheart** [comment]
Well, technically you can use it though, you just have to set the starting date for a few minutes later to make sure it starts after you click "Create Giveaways". I'll correct the time later.

**Comment by gizellos** [comment]
If I understand it correctly, without this "hack" with the time, it never can work for anyone. And using the hack is very annoying, because when I start to create the train, I don't know how much time it will take me so I have to set the time with some reserve to be sure that I will finish the making before the time and after creating the train I have to wait until the giveaways start so that I didn't post to the discussion giveaways that still haven't started (because it is not good). And no matter if I set the time manually clicking on the button Now or I use a template, the time will be always set earlier than I click on the button for creating the train.

So let's say, I start to create the train in 2 PM and because I don't know how much time it will take me I set the start of the giveaways to 2:40 PM. Because there were no complications, I was able to create the whole train in 2:20 PM and I have to wait 20 minutes to post the link to the train on the discussion.

Please look at it soon.

**Comment by revilheart** [comment]
Again, it's not a bug and this is not a "hack", the feature works perfectly fine for everyone. It's the same way if you were creating a giveaway individually: if you click to create it and the time you set has already passed it will give you an error asking you to correct the date. Exactly the same. I know in this case it's annoying because there's no way to correct the date (although you can export the train and then import it again with the correct date), but it's still not a bug, the feature is fully functional.

Implementing this might be a bit complicated, so I probably won't have time to look into it soon. In the meantime, you can perfectly use the import/export functions to come around that. And I doubt the creation process would take more than a few minutes with the new import function.

**Comment by gizellos** [comment]
I just did some tests and it seems that the problem is not exactly earlier time but earlier hour. So if I start to make a GA in, for example, 6:00:00 - I can finish it even in 6:59:59. However if I start to create a GA in 5:59:59 and I want to finish it in 6:00:00 it is not possible because the hour is lower. Kinda ridiculous but it's about SG itself and not your script of course and I know you know already it. :/

But the fixing of it seems to be, on the contrary, trivial, doesn't it? After I click on the ADD button, condition like this will execute: if the starting time < now, set starting time to now.

**Comment by revilheart** [comment]
The idea is trivial, but the implementation is not, because SG uses a specific format for dates, like Jul 15, 2017 8:23 am. So converting that format to a date and changing the hours/minutes is not trivial. I'll try something in the next version.

**Comment by revilheart** [comment]
Hm actually it's way simpler than I though, it will be up in the next version later today.

**Comment by gizellos** [comment]
OK I didn't know. Thanks.

**Comment by revilheart** [comment]
Done

**Comment by gizellos** [comment]
Nice, thanks a bunch. :)
