### ISSUE TITLE
[Bug] Not enough information to know if you are whitelisted

### ISSUE THREAD

**Issue by thischrisoliver** [revilheart/ESGST#217]
I've been having issues with the whitelist checker not detecting that a few different users had whitelisted me and instead giving me the following message:

"You are not blacklisted and there is not enough information to know if you are whitelisted by (1): [username]"

The first couple times this happened, I assumed it was because the whitelist giveaways that these users had created were also group giveaways (though I wasn't a member of the groups).

However, today it happened with a user that created a giveaway for just his whitelist. The attached screenshots show that I did enter the whitelist giveaway, but I'm still getting the "not enough information" message.

![](https://user-images.githubusercontent.com/22454900/27790334-0b360ad0-5fbe-11e7-9662-6b5498c8efc5.png)
![](https://user-images.githubusercontent.com/22454900/27790335-0b38c4d2-5fbe-11e7-809a-c2a39fc0f0c1.png)

**Comment by revilheart** [comment]
What happened? Did it fix itself?
