### ISSUE TITLE
[Feature Request] Hide entered giveaways

### ISSUE THREAD

**Issue by kostek00** [revilheart/ESGST#218]
Till today I had many scripts but I replaced them with your. One your does almost all that all of them. And that almost is one feature that I really liked in one of them. Hiding giveaways that I entered. It's really nice feature that helps quicker see your wishlist in SG.

After pressing enter button on SG page (not in ga page) it was hiding that ga. You might even extend that to have somewhere on page button that will show all entered ga and hide them when pressing again.

**Comment by gizellos** [comment]
You can hide and unhide them in giveaway filters settings.

**Comment by kostek00** [comment]
Oh, I see, I see. That function is in filters.
