### ISSUE TITLE
[Enhancement] Better order of loading game categories in GAs lists

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#219]
It seems that the game categories are not loading from the first GA to the last GA and because of it, it is quite slow because often the later games are loaded earlier than the first ones. Maybe you could virtually divide each page to more parts and load them progressively.

Let's imagine this GA list:

- GA 1
- GA 2
- GA 3
- GA 4
- GA 5
- GA 6
- GA 7
- GA 8
- GA 9
- GA 10
- GA 11
- GA 12

Now it works kinda random, so it can load like this: GA 3, GA 11, GA 1, GA 4, and so on.

If you divided it to, for example, 4 parts, it would first load GA 1 - GA 3 and when they are loaded it would start to load GAs 4 - 6, then 7 - 9 and then 10 - 12. The order of the GAs in the parts would be also random, but it would not be such a problem since the GAs were at least on a smaller place.

It is quite problem mainly with game genres/tags since their loading is the slowest one.

**Comment by revilheart** [comment]
Is this still a problem?

**Comment by gizellos** [comment]
I think it is not a problem anymore. I am closing this. Thanks.
