### ISSUE TITLE
[Enhancement] to scroll to the first comment when pagination is used

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#22]
Hello,
I already asked you about this on SG. It would be good the script scrolled the page to the first comment after using pagination. I think it always should be like this because, logically, when you are in a topic and you want to go to another page, you don't need to read the OP again, so it should take you to the beginning of the comments on the page you want to see. Or I could say that the pagination is there just for the comments so it should show only the comments.

It's OK if one use the hiding OP feature, but with this feature off, it kinda annoying to scroll with mouse to the first comment after every using the pagination.
![scroll page to the first comment](https://cloud.githubusercontent.com/assets/2397851/23471398/739417e6-fea9-11e6-881f-5fce8492a8c5.png)

**Comment by revilheart** [comment]
Yeah, I remember. I made that a functionality in Main Post Popup because of your suggestion. :) I'll see what I can do.

**Comment by gizellos** [comment]
If the Main Post Popup didn't execute on the first page, it may be enough. Maybe you could just add an option "exclude the first page in posts". BTW I just tried to enable the feature and it is not working for me. Try it if it is working for you.

**Comment by revilheart** [comment]
But it doesn't execute on the first page. Not if the main post is marked as read anyway, and it also detects main post edits, so it only hides the main post if you actually read it. Main Post Popup is working fine for me, what's happening?

**Comment by gizellos** [comment]
Ok, it seems it works, I didn't understand it well, before. But why even visiting the first page doesn't hide the OP when I go to another page? I think that if I am on a page where the OP is showed, the script should remember it and hide the OP when I visit page 2+.

**Comment by revilheart** [comment]
Visited doesn't equal read, and the OP is only hidden if it is read. I could add an option to hide it on first visit as well.

**Comment by gizellos** [comment]
But in this case it should be treated as equal, shouldn't it? It goes like this now: enter new Topic, see the OP, go to the page 2 and see the OP you already saw again. It doesn't make sense to me. 

It seems there are just two possibilities 1.) you haven't visited the thread and you 100% haven't seen the OP and therefore you want to see it 2.) you have visited the thread and 100% seen the OP and therefore you don't want to see it again.

Yes, the option would be nice.

**Comment by revilheart** [comment]
If you saw the OP why not just mark it as read?

I think there is also the possibility of visiting a thread and not reading the OP or reading only some part of it because you want to finish later. I do that often and wouldn't want it hiding the OP simply on first visit because of that.

I'll add it to the next version.

**Comment by revilheart** [comment]
Added the option. Let me know if it isn't enough.

**Comment by gizellos** [comment]
If you mean the option "Hide main post after first visit." - it works, but the scrolling would be much better anyway. It doesn't scroll at all and even with enabled feature "Main Post Popup" is the absence of the scrolling quite annoying because instead you would see the first comment after you used the pagination, you see textarea at the first place.

**Comment by gizellos** [comment]
This is what I mean, you would just have to make it more complicated since you load the data with the script. And you would have to use something like scrollTo('#target') function. So the script would normally load the data and then to scroll to the div with the word Page <number>

```
<div id="page-3">Page 3</div>
<a href="#page-2">Link to page 2 in the pagination</a>
post 1
post 2
post 3
....
<div id="page-4">Page 4</div>
post 1
post 2
post 3
....
```

**Comment by revilheart** [comment]
I'm a bit confused now. You mean scrolling to page 4 when clicking on that number in the pagination panel? It already does that.

**Comment by gizellos** [comment]
What it does now that it will just load the new page but it won't scroll the the page to the begining of the comments so what I see is the OP.

Check the gif.
![no scroll](https://cloud.githubusercontent.com/assets/2397851/23578762/7183af34-00de-11e7-9905-20f192c44da3.gif)

**Comment by revilheart** [comment]
Oh I thought just adding the option to Main Post Popup was okay for you, so I didn't add that feature. Will do it later.

**Comment by revilheart** [comment]
Forgot to come back to this. Re-opening it as a feature request, because adding an option to Main Post Popup is not doable.

**Comment by revilheart** [comment]
Added a feature that does this.
