### ISSUE TITLE
[Bug] Sync Groups  - high CPU and RAM usage

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#220]
I noticed that  ESGST sync takes 10 GB RAM, my processor i7 7700K is load to 25 % (whole 1 core) and it takes tens of minutes to finish the sync. It has a problem with syncing my  whitelist obviously. No errors in console. I use Google Chrome.

![2017-07-05_131436](https://user-images.githubusercontent.com/2397851/27862316-e907ec12-6184-11e7-8448-daa51c98655f.png)

**Comment by ldeman** [comment]
dayumn.  and i thought my occasional 2gb spikes were bad.   ^^

**Comment by revilheart** [comment]
Yeah, I tried syncing recently and had to restart my computer. I already tried something that optimized it a bit, and trying something now that should optimize it more.

**Comment by revilheart** [comment]
Let me know how it goes in the latest update.

**Comment by gizellos** [comment]
It works very well now. Thanks.

**Comment by ldeman** [comment]
+1  amazing work.. performance for the entire script was greatly improved with the 15+ update.  ^^

**Comment by revilheart** [comment]
Glad to hear it.
