### ISSUE TITLE
Add GA end time to Entered page?

### ISSUE THREAD

**Issue by jims9350** [revilheart/ESGST#221]
On the Entered GAs page, it says how many hours are left. Is there a way to add the actual time a GA will end?

Edit: Did I do this request correctly?

**Comment by ldeman** [comment]
is this not what you are looking for? https://github.com/rafaelgs18/ESGST#accurate-timestamps

and yes, issue ticket is perfect for issues/requests both. ;)

**Comment by jims9350** [comment]
Crap, did I seriously miss that? Sorry!

**Comment by gizellos** [comment]
The exact time can be shown also when you put your mouse cursor on the date. Maybe it is enough for you.
