### ISSUE TITLE
[Enhancement] Game categories and Created/Entered/Won Giveaway Details - Slow loading pages, very high CPU usage

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#222]
Nowadays loading pages is very  slow for me and the CPU usage is very often very high for a very long time. It is quite crazy and the website is not very usable since everything is slow and my CPU fun is loud very often.

The problematic features are mainly Game categories and Created/Entered/Won Giveaway Details. However I believe every page is much more hunger for CPU.

1. All pages where game categories are used are slow and the CPU usage is really high. I believe it is  higher than it is supposed to be.
2. Created/Entered/Won Giveaway Details are very slow. I will show you two gifs where you can compare the speed of the [Ruphine's script](https://www.steamgifts.com/discussion/CHaNe/userscript-shows-more-info-at-giveaways-entered-created-won-pages) and ESGST. The other script is several times faster than ESGST. There really must have be a problem with ESGST.

**Comment by gizellos** [comment]
OK so here is the Ruphine's script

![other script created gas](https://user-images.githubusercontent.com/2397851/27976601-895f2afc-6367-11e7-9348-87f0d363d6a7.gif)

**Comment by gizellos** [comment]
And here, sadly, ESGST. :(

![esgst created gas](https://user-images.githubusercontent.com/2397851/27976611-9aac661c-6367-11e7-9163-3ab57c1f04ed.gif)

**Comment by revilheart** [comment]
Already optimized it in the update I'm working on. I'll probably push it later today.

**Comment by revilheart** [comment]
Let me know how it goes in the latest update.

**Comment by gizellos** [comment]
It is even much faster than the other script. Good work! :)

**Comment by revilheart** [comment]
Nice!
