### ISSUE TITLE
Show only Awaiting Feedback GAs in Created Giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#223]
I would like to have a button that would hide all created giveaways except those that are still awaiting feedback.

**Comment by revilheart** [comment]
Do you have awaiting feedbacks? Can you give me the class name of the "Awaiting feedback..." element?

**Comment by gizellos** [comment]
Yes.

`<div class="table__column--width-small text-center"><i class="fa fa-question-circle"></i> Awaiting Feedback</div>`

**Comment by revilheart** [comment]
I decided to extend Giveaway Filters to the created/entered/won pages, which both covers this issue and could be useful in other scenarios. Hope that's a good solution for you.

**Comment by gizellos** [comment]
Yes it is very good, thanks.
