### ISSUE TITLE
[Enhancement] Check what people put to the encrypted giveaway text field

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#225]
I just saw that I man [put](https://www.steamgifts.com/discussion/JdK6x/the-ultimate-debate-29#nfNr8OF) /mCtxP/ to the text field for the encrypting giveaways and because of it, it shows the GA twice in the list of encrypted giveaways. 

It would be good to check the right format for the GA encrypting and don't allow to save incorrect stuff (for example to check if there are exactly 5 letters/numbers).

![2017-07-09_153353](https://user-images.githubusercontent.com/2397851/27994383-09a39026-64bd-11e7-88c2-43188c645249.png)
![2017-07-09_154123](https://user-images.githubusercontent.com/2397851/27994388-27ee3e0a-64bd-11e7-9df2-609dbd8ad049.png)

**Comment by revilheart** [comment]
Done
