### ISSUE TITLE
[Enhancement] link on entry popup

### ISSUE THREAD

**Issue by mmuh** [revilheart/ESGST#226]
Hey Rafael :)

I'd like to ask for a small enhancement of the entry popup.
Could you add a link to the GA itself in the popup, maybe under the "add comment" button or on the icon on top? Often i'd like to open the GA when i already entered and it's filtered out or if i see interesting descriptions.

[example](http://i.imgur.com/aJ8VNhy.png)

Thanks for all the work :)

**Comment by revilheart** [comment]
Done, added a link to the giveaway with the title of the game and a link to the creator.

**Comment by mmuh** [comment]
Thank you very much :)
