### ISSUE TITLE
[Bug] Check for whitelists on pages where it is not supposed to be

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#227]
I think I already made this Issue and it was solved in the end but I cannot find it so that I couldn't re-open it, so sorry.

The button Check for whitelists is again on pages where it is not supposed to be. I saw it here:

- Create a New Giveaway
- Created Giveaways
- Community Wishlist
- Hidden Giveaways
- Bundle List
- Create a new Discussion
- Comment formatting

Well, it seems to be everywhere.

**Comment by revilheart** [comment]
Yep, it's everywhere again, I'm aware of it.

**Comment by revilheart** [comment]
Should be fixed.
