### ISSUE TITLE
Show the decrypted giveaway stars in our edited posts without the need to refresh the page

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#228]
~~If I write a post and put there an encrypted giveaway, after I post it I cannot see the star in the post. I have to refresh the page to see the star.~~

~~Could you show it immediately after I post it?~~

I found out the problem is a bit else. If I edit a post of mine and I add an encrypted giveaway to it, the star icon doesn't appear in the post. I have to refresh the page to see it.

**Comment by gizellos** [comment]
It seems to work now. Therefore I closed this issue.

**Comment by revilheart** [comment]
Ok, glad to know it's sorted.

**Comment by gizellos** [comment]
Opened and updated OP.

**Comment by gizellos** [comment]
Please remove the "invalid" mark so that I wouldn't have to make a new issue. I changed the issue a bit and it is valid now.

**Comment by revilheart** [comment]
Should be fixed.
