### ISSUE TITLE
[Enhancement] Split the comment tracker into 2 separate features

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#229]
I already asked for it in[ another issue](https://github.com/revilheart/ESGST/issues/179) as off topic so I also have to write it officially. 

Please, split the comment tracker into 2 separate features so that I could turn off the read/unread posts feature and enable just visited topics feature.

BTW loading messages, posts, or list of topics is quite hungry for CPU. Is possible that the reason is the read/unread posts feature?

**Comment by revilheart** [comment]
I already did, check the changelog from Beta.15.0. :P There's a new feature called Giveaways/Discussions/Tickets/Trades Tracker that has the visited component from Comment Tracker.

I don't know, have you tried disabling it to see?

**Comment by gizellos** [comment]
Cool, I didn't notice although I read the changelog twice. Thanks a lot. 

BTW: if I enable the read/unread feature I cannot see it in Active Discussions. I don't mind it since I disabled it but people who use it sure miss it there.

**Comment by gizellos** [comment]
I think the user is right. Could you move it to a more general section?

![2017-07-10_170357](https://user-images.githubusercontent.com/2397851/28024748-da0df074-6591-11e7-98df-a6322b1c1d11.png)
