### ISSUE TITLE
[Bug] Visited threads are not marked as visited

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#230]
When I enter an unvisited thread, the thread is not marked as visited.

![visited topics](https://user-images.githubusercontent.com/2397851/28030603-b8b5247a-65a4-11e7-8b74-abf00f23e411.gif)

**Comment by gizellos** [comment]
It is only bugged if I disable comment tracker. Please fix this ASAP because it is really very frustrating  for me now. :(

**Comment by revilheart** [comment]
Fixed
