### ISSUE TITLE
[Bug] Comment history is not working for me

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#231]
Comment history is not working for me. I can't see it in the ESGST menu. It stopped to work with the last big update v6.Beta.15.0. I didn't change any settings except disabling the comment tracker (it shouldn't be a problem according to the help text of comment history feature).

![2017-07-10_215233](https://user-images.githubusercontent.com/2397851/28037594-1fd2d6b8-65bc-11e7-8e43-972d5ba43828.png)

**Comment by revilheart** [comment]
It's working, just not showing on the menu. Will be back in the next version.

**Comment by revilheart** [comment]
Should be back.
