### ISSUE TITLE
[BUG] Giveaway groups popup runs off screen for long group lists

### ISSUE THREAD

**Issue by GOBsNotOnBoard** [revilheart/ESGST#232]
I discovered today that when a giveaway is for a lot of groups, the giveaway groups popup runs off the screen, and I can never access the bottom of the popup (even if I scroll down) because it's in a fixed position on the page.

![screenshot 2017-07-11 09 32 38](https://user-images.githubusercontent.com/29752867/28072567-7dd3c8a2-6621-11e7-8bd4-95cbf354040f.png)

**Comment by revilheart** [comment]
Should be fixed.
