### ISSUE TITLE
[Bug] High CPU usage

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#235]
Nowadays, the CPU usage is too high. It is high so much that I even had to start to close SG page because my PC screams because of it (and it is not so easy sometimes because it can end stuck in memory).

All pages have this problem. Even the ones where there are not any people or giveaways. For example on [Guidelines](https://www.steamgifts.com/about/guidelines).

No errors in console.

In the attached file you can see it on the discussion list and then on the guideline page. 

Please look at the issue soon. 

![high cpu usage](https://user-images.githubusercontent.com/2397851/28133651-fae0c33e-6740-11e7-8324-82e4b1c1c63f.gif)

**Comment by gizellos** [comment]
It seems that you fixed it in the v6.Beta.16.2, right? Thanks a lot, it was really a nightmare. :)

**Comment by revilheart** [comment]
I optimized the locking system used to save stuff. If that fixed it, that's great. :)

**Comment by gizellos** [comment]
Yes, it seems to be fixed. I am closing this. :)
