### ISSUE TITLE
[Enhancement] Simpler train description formating

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#237]
To tell the truth I don't understand the formatting of train description at all. It seems to be too complicated.  For example, this:
[ESGST-P][P]Previous[P][ESGST-P][ESGST-S] [ESGST-S][ESGST-N][N]Next[N][ESGST-N] ([ESGST-C] of [ESGST-C])
Will be this:
Previous Next (2 of 10)

Why is it not possible to achieve the same result just with, for example, this?
[ESGST-P]Previous[ESGST-P] [ESGST-N]Next[ESGST-N] ([ESGST-C] of [ESGST-C])

It would make sense like this. I would be able to remember the tags. Now it is really hardcore to remember it and be able to orient in the text - be able to check if it is written correctly, and so on.

Please make it simpler if it is possible.

BTW is really [ESGST-C] for both the numbers? It would be fun if it was not, hehe.

**Comment by revilheart** [comment]
I explained everything there and the 3rd example explains it even better:

[ESGST-P]Go [P]back[P].[ESGST-P][ESGST-S] [ESGST-S][ESGST-N]Go [N]forward[N].[ESGST-N]

It will result in "Go [back](url). Go [forward](url).", so as you can see, [P]...[P] delimits the clickable link and the area around [P]...[P] delimits other text that the user might want to add before/after the link to customize it better. I could indeed remove "[ESGST-S][ESGST-S]" as I could use everything from the end of "[ESGST-P]" until the beginning of "[ESGST-N]" as separator, I'll do that later, but removing "[P][P]" would remove the ability to customize the texts like the 3rd example does. I could make the script detect if "[P][P]" is there and use the entire "[ESGST-P][ESGST-P]" area as the link if it's not, though, I think that would be the best solution.

Yes, it's [ESGST-C] for both of them.

**Comment by revilheart** [comment]
Simplified it, hope it's better now.

**Comment by gizellos** [comment]
Yes it is much better. I like mainly the slashes in the end tags. :)
