### ISSUE TITLE
Message about out-of-date version of ESGST is not centered

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#238]
The message about out-of-date version of ESGST is not centered. BTW It is quite funny that when I select the text, the window will center itself. :)

I suppose it is supposed to be centered and therefore I called it a bug and not and enhancement. :)

![left align](https://user-images.githubusercontent.com/2397851/28219384-11b02ef2-68bc-11e7-9d3e-f9a4a28a0a69.gif)

**Comment by revilheart** [comment]
I call "bug" something that does not work how it's supposed to be and causes errors/problems because of that. I would call this a "style" issue, as there are no problems at all in it opening on the side, it's only a matter of visuals.

**Comment by gizellos** [comment]
Yeah, you are right. I forgot about the style marker. I want to stop to use the text in brackets anyway. It's pointless when you mark it with the label in the end. And then it will be on you how you call it.

**Comment by revilheart** [comment]
Should be centered now.
