### ISSUE TITLE
Notification in tabs of ESGST github

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#239]
It sucks that github doesn't support notifications in tabs. Could you add it too the script for your repository (only)? No matter if it was just a number in brackets in tab text or changed favicon ico.

**Comment by revilheart** [comment]
Since this is completely unrelated to ESGST, I made another script for that: https://github.com/revilheart/GitHub-Notifier

**Comment by gizellos** [comment]
Cool. Thanks.
