### ISSUE TITLE
Sent unsent gifts doesn't work for gifts on page 2+

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#241]
I thought I already wrote this issue here but I cannot find it (maybe I wrote it just to the SG discussion).

If an unsent gift is on page 2 and more, the Sent unsent gift feature won't find the GA unless I scroll to it.

Could you fix it? If the SG says that I have some ended giveaways, the script should load the pages until it finds them all.

![2017-07-14_221702](https://user-images.githubusercontent.com/2397851/28230316-aecbf714-68e6-11e7-9945-4a4547e91bfd.png)

**Comment by revilheart** [comment]
Pretty sure you mentioned that in #69. I'm currently rewriting this feature, which should fix all issues related to it.

**Comment by revilheart** [comment]
But I'm not really sure how I can work around this. It could say that you have 25 unsent gifts for example, but all of them come from the same giveaway, so the script would continue loading all your created giveaways trying to find 25 unsent giveaways and it wouldn't find it.

**Comment by gizellos** [comment]
You memory is good. I thought you already rewrote it.

I think you could simple read the number of ended giveaways and load the page 1 as you do now. If the "Sent unsent gifts" sent the same number of keys as the number of ended GAs, it would not load the pages two and more. If it would send less keys, it would load the page two and again compared the numbers.

**Comment by revilheart** [comment]
I don't understand what you mean.

**Comment by gizellos** [comment]
If steamgifts says there are some ended unsent giveaways and the script cannot find an unsent giveaway, instead of writing " You have no unsent gifts.", it should load another page and try to find it again.

**Comment by revilheart** [comment]
That's not what I mean, I mean if you made a giveaway with multiple copies, the script would not be able to find the unsent gifts and keep searching until the very last page, which is both a waste of time and resources. The only thing I can do is make it keep searching until there are no more open giveaways, and maybe one page more after that.

**Comment by revilheart** [comment]
Should be fixed, let me know if not.
