### ISSUE TITLE
Endless "Waiting for a free request slot"

### ISSUE THREAD

**Issue by Mazayw** [revilheart/ESGST#243]
Thanks for the script!
When i try Sync Groups / Whitelist / Blacklist / Wishlist / Owned Games / Ignored Games i get endless "Waiting for a free request slot ..."
LAst version of Chrome/script/Tampermonkey
How can i fix it?

Screen:
![userscript esgst v6 beta 17 3 new features removed game redirecter next previous train hotkeys page 38](https://user-images.githubusercontent.com/20990494/28237205-9d5fbaea-6942-11e7-902f-24bc0a9b52d5.png)

**Comment by revilheart** [comment]
Try updating and trying again.

**Comment by Mazayw** [comment]
Thank you, now works excellent!

**Comment by revilheart** [comment]
Can you open the console (F12) and see if there are any errors?

**Comment by Mazayw** [comment]
When start checking:
Uncaught TypeError: node.getElementsByTagName is not a function
    at HTMLDocument.eval (eval at <anonymous> (:2:398), <anonymous>:47:21)
    at <anonymous>:2:398
    at b (<anonymous>:2:243)
    at HTMLDocument.t (eval at exec_fn (:1:108), <anonymous>:47:115)
    at Window.eval (eval at E_c (:3:221), <anonymous>:3144:44)
    at <anonymous>:2:398
    at e.string.k.function.c.(anonymous function) (eval at exec_fn (:1:108), <anonymous>:53:352)
(anonymous) @ VM371:47
(anonymous) @ VM323:2
b @ VM323:2
t @ VM344:47
(anonymous) @ VM372:3144
(anonymous) @ VM323:2
e.string.k.function.c.(anonymous function) @ VM344:53

**Comment by revilheart** [comment]
Are you using other scripts?

**Comment by Mazayw** [comment]
When only the ESGST is enabled, then log is clear, but script still does not work

**Comment by revilheart** [comment]
Should be fixed in the latest.

**Comment by Mazayw** [comment]
Thank you, now it works =)
