### ISSUE TITLE
Support for endless scrolling in the list of Dectypted giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#244]
It would be nice to have support for endless scrolling also in the list of Dectypted giveaways. 

The list getting bigger and bigger nowadays and it would be handy. Even now I have to click 3 times to the button more to see them all (although unfortunately most of them are my GAs).

**Comment by revilheart** [comment]
Well, they're ordered by ending time, so you cannot miss giveaways (you can just wait until the current ones end, and then check again).

**Comment by gizellos** [comment]
I know but if I need to check, for example, how many entries a newer GA of mine has, currently, I have to click 3 times on Load more than I can see the GA at the end. It's not a problem but if the implementation is not a problem, so why not, when almost all the other lists also supports endless scrolling. 

And the other lists, such as Highlighted Discussions and Comment History could have endless scrolling too because why not. Endless scrolling rocks.

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Cool, that will be much better. Nowadays, I am kinda spoiled with the endless scrolling. Thanks.
