### ISSUE TITLE
Not sure if Import Giveaways description is written correctly

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#245]
I don't understand a part of the Import Giveaways description at all. Is it written correctly? It looks like all the lines are reversed somehow. And I am not sure what is for the script and what is just a word in description. Or the description is ok and the syntax is complicated like that?

Here is what I don't understand with my commentary:

Here's an example of how the input should be with reverse position disabled:

Portal (why is there this line? Is it for the script or it is just a heading?)
Portal ABCDE-FGHIJ-KLMNO _(OK, I suppose this will create 1 giveaway with 1 key ABCDE-FGHIJ-KLMNO)_
Portal ABCDE-FGHIJ-PQRST _(OK, I suppose this will create 1 giveaway with 1 key ABCDE-FGHIJ-PQRST)_
Portal (2 Copies) _(here or on the lines bellow I would expect the 2 keys and there are no 2 keys but just one bellow this line)_
Portal ABCDE-FGHIJ-UVWXY (why is there this line? It will just create 1 giveaway with 1 key, it is the same example like the first two, isn't it?)

I would understand if it was like this, for example:

Portal ABCDE-FGHIJ-PQRST (this line will create 1 giveaway with 1 key)

Portal (2 Copies) _(this line + the two lines below will create 1 giveaway with 2 keys)_
ABCDE-FGHIJ-KLMNO
ABCDE-FGHIJ-UVWXY

![2017-07-15_113650](https://user-images.githubusercontent.com/2397851/28238343-efb5d22a-6951-11e7-9fbc-3a20d8008a86.png)

**Comment by revilheart** [comment]
Everything is explained in the text above the examples.

First line creates a gift giveaway for Portal.
Second line creates a key giveaway for Portal.
Third line creates another key giveaway for Portal.
Fourth line creates a gift giveaway for 2 copies of Portal.
Fifth line creates another key giveaway for Portal.

If "Group adjacent keys for the same game." is enabled:

First line creates a gift giveaway for Portal.
Second line is grouped with third line and creates giveaway for 2 keys of Portal.
Fourth line creates a gift giveaway for 2 copies of Portal.
Fifth line creates another key giveaway for Portal.

**Comment by gizellos** [comment]
Aww, I didn't realized the existence of gift GAs. And I also didn't understand the phrase "Group adjacent keys" - I thought it was something with steam groups. That's why it was so confusing for me. It makes sense for me now. Thanks.

**Comment by revilheart** [comment]
You can try putting something in the list and importing it to get familiar with it, the giveaways aren't immediately created when you import them, you still have to click "Create". :)

**Comment by gizellos** [comment]
I am going to test it soon. :) Then I would like to use just this for trains. I will just have to check all my new bought keys if their names are right, because some bundles sometimes provide a slightly different names and it could be a problem.

**Comment by revilheart** [comment]
The script automatically checks that for you and lets you know if a title is not found. You can then correct the title and continue to import easily.

**Comment by gizellos** [comment]
Then it is even better. You rock, thanks.

BTW I am planing to record a fast creating of a train and then I will show it to people. I will use importing and many wagons. Train which people would make several hours by hand or several tens of minutes with the sgchochoo script I will do within a minute or so. I think it will be quite shocking for people. :D

But first I have to record it, then to wait until all the GAs end and then I can show it to people (to wait until the keys are used).

**Comment by revilheart** [comment]
You can wait a bit if you want, I might push the next update with the time correction in a few hours.

**Comment by gizellos** [comment]
Yeah, it won't be so soon. First I want to try the importing and I created a new train yesterday. I will give you the link then so you can use the gif too if you need.

**Comment by revilheart** [comment]
Hmm are you sure this is how it behaves? I just tried creating a giveaway, added it with the time 11:23, waited 10 minutes and tried to create it, it created perfectly fine.

**Comment by revilheart** [comment]
Ah nevermind, it seems like SG auto corrects the date if it's late by a few minutes.

**Comment by gizellos** [comment]
> Hmm are you sure this is how it behaves?

I am not sure what you mean. If you mean the SG error from another issue, I chose the date 1 minute before the new hour and then I tried to create the GA 1 minute after the new hour. The word new is the important thing there. If you set there, for example 11:55 and tried to create it in 12:05 it would not create it.

**Comment by revilheart** [comment]
I set it to 11:23 and tried to create it on 11:26 and it corrected itself using SG's default tool. I believe if you create it in less than 5 minutes, SG automatically corrects it. But yeah, I was mentioning the other issue, got confused and thought it was this one. :P

**Comment by gizellos** [comment]
Ok, you are right. I just tried it again with disabled ESGST and it really worked even with the new hour. Then I don't know where the problem was when I tried it for the first time.
