### ISSUE TITLE
Double underline for groups in Giveaway Groups Loader 

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#247]
The groups written by the Giveaway Groups Loader have two underlines. I think it is not an intention.

![2017-07-15_132559](https://user-images.githubusercontent.com/2397851/28239018-84753144-6961-11e7-8fa8-a13124ba236b.png)
![2017-07-15_132535](https://user-images.githubusercontent.com/2397851/28239020-882167cc-6961-11e7-98f4-109ff98cc385.png)

**Comment by revilheart** [comment]
Fixed
