### ISSUE TITLE
Remove entries error

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#249]
When I Sync or do it manually , the remove entries feature doesn't write anything (there should be 0 entries in my case). There is an error in the console. It has been since  v6.Beta.17.4,

![2017-07-15_182738](https://user-images.githubusercontent.com/2397851/28240986-c0e2324c-698b-11e7-8bdd-e12f8ab4601c.png)

**Comment by revilheart** [comment]
Should be fixed.
