### ISSUE TITLE
Light version of filters in Decrypted Giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#252]
I would like to have a possibility to filter a bit the list of Decrypted giveaways.

For now, I would appreciate these:
- Hiding my own giveaways (3 ways like in the normal filters would be even better)
- Hiding owned games

When/If there are much more decrypted giveaways, more filters could be useful, but for now those would be enough.  

I create the GAs a lot and most of the GAs are mine or I own them and  so it is quite hard to orient among them when I see them so many. And when I need to see just the ones I can enter, it is very slow for me because I have to load also the tons of my own or owned GAs.

**Comment by gizellos** [comment]
Check this gif and you will see why I need it. :D
![decrypted giveaways list](https://user-images.githubusercontent.com/2397851/28245467-b7047600-6a07-11e7-9dbd-86fbe1846d3a.gif)

**Comment by revilheart** [comment]
The full filters are now available.

**Comment by gizellos** [comment]
Cool, just they are not working for me. :(If I use them, they filter the page bellow them (it means, when I am on wishlist, it filters wishlist).

BTW I hope it is not in fact filters but just settings. I meant it that filters filter already loaded results, they hide things there but it would be pointless here since you have full control what to show there. So for example, it would be bad if it loaded all the encrypted GAs and then it hid the ones I created - it would be slow. The settings would load just he ones I didn't created. Since it is not working for me, I don't know if it is really filters or the settings.
