### ISSUE TITLE
Redundant periods in Manage data

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#253]
I think there shouldn't be periods in the texts in Manage data section because the texts are not sentences.

![2017-07-16_193209](https://user-images.githubusercontent.com/2397851/28249820-830f1b38-6a5d-11e7-8a1d-55286e564e1b.png)

**Comment by revilheart** [comment]
If we're using that logic, then tooltips need to have periods because they are sentences. :P I'll add periods back to tooltips and remove the periods here, I also think "data" is redundant since it's obvious you're managing data.

**Comment by gizellos** [comment]
I just checked some tooltips and they have periods in case they are not ["undefined"](https://github.com/revilheart/ESGST/issues/196). :P

**Comment by revilheart** [comment]
Done
