### ISSUE TITLE
RaChart tables - check how many copies of a game I have delivered via giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#254]
I would like to have the possibility to check games in RaChart tables to know if I made giveaways for the games and if I did, how many copies I delivered. There could be both - single game checker or check all games checker.

It could also show (tooltip?) how many CV I would get for another copy. It is not necessary, though.

**Comment by gizellos** [comment]
As a bonus feature could be highlighting of games I already sent 5 copies of. :)

**Comment by revilheart** [comment]
Added, without highlighting option, but you can see the number of giveaways you already made, so I hope it's not necessary.
