### ISSUE TITLE
ESGST Sync: "Cannot set property 'textContent' of null"

### ISSUE THREAD

**Issue by Anxeal** [revilheart/ESGST#260]
On https://www.steamgifts.com/esgst-sync, the lines that contain `syncer.progress.lastElementChild.textContent` fail because `syncer.progess` is just a div, with only a text node, so `syncer.progess.lastElementChild` is `null` (i.e. no non-text-node child exists). Could be fixed by replacing `syncer.progress.lastElementChild.textContent` with `syncer.progress.textContent`.

_I'm not that good with pull requests so I'm leaving it here as an issue :v I hope you don't mind._

**Comment by revilheart** [comment]
Yeah, I feel like something so small doesn't really need a pull request, it's fine. :) Fixed.
