### ISSUE TITLE
Filters in Decrypted Giveaways are not working

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#262]
They are not working for me. :( If I use them, they filter the page bellow them (it means, when I am on wishlist, it filters wishlist).

BTW I hope they are not in fact filters but just settings. I meant it that filters filter already loaded results, they hide things there but it would be ineffective here since you have full control what to show there. So for example, it would be bad if it loaded all the encrypted GAs and then it hid the ones I created - it would be slow. The settings would load just he ones I didn't created. Since it is not working for me, I don't know if it is really filters or the settings.

Edit: it even rewrites the settings of filters on the page bellow.

**Comment by revilheart** [comment]
Try using it in a page that doesn't have filters, it should work there. I'll fix it later.

Currently it's just a filter, so it loads all and then filters them. It's currently more effective for Train Giveaways Extractor. I'll make modifications to make it load based on filters later.

**Comment by gizellos** [comment]
Ok, thanks, dude. :)

**Comment by revilheart** [comment]
Should now work properly.
