### ISSUE TITLE
Train extractor extracts another train

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#263]
[This topic](https://www.steamgifts.com/discussion/t11dh/level-8-celebration) contains two trains. One for lvl0+ and the other for lvl8+. When I extract the giveaways in the lvl0 train, it will show me the GAs from the train for lvl8+. It is the same for the lvl8+ train, it extracts the lvl0 GAs.

![2017-07-18_184423](https://user-images.githubusercontent.com/2397851/28329288-923cf6a6-6be9-11e7-8f2c-fd8a82004d3d.png)

**Comment by revilheart** [comment]
If the giveaways are linked in the description, then I can't do anything about it. You can use filters to filter out unwanted ones.

**Comment by revilheart** [comment]
Ah, nevermind, misread it, will do something about it later.

**Comment by revilheart** [comment]
Should now work properly.
