### ISSUE TITLE
[Bug] Unset Gift Sender + "check to insure they are still withing group"

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#264]
it's failing everyone that came in thru whitelist entry instead of group entry.

**Comment by revilheart** [comment]
Currently rewriting this feature. Hopefully I can finish today and all bugs related to it should be gone. :)

**Comment by ldeman** [comment]
sounds great =)

**Comment by revilheart** [comment]
Should be fixed, let me know if not.

**Comment by ldeman** [comment]
seems so, thanks.  ^^
