### ISSUE TITLE
Decrypted giveaways filters and Train Extractor filters  use the same settings

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#266]
Decrypted giveaways filters and Train Extractor filters use the same settings. Please separate them.

**Comment by revilheart** [comment]
Is that needed? I'd rather not have to add yet another group of settings to the filters. It's getting way too large (there already is main, wishlist, recommended, new, group, groups and now popup).

**Comment by gizellos** [comment]
I think it is not so needed - for now at least. I was just surprised when I tested the bump link feature on my train and I didn't see there my giveaways because they were hidden because of the settings I set in Decrypted giveaways settings. So I was not sure if it is on purpose or it is a bug.

I am closing this.

**Comment by revilheart** [comment]
I see. Ok, feel free to reopen if it becomes needed and I'll separate them.
