### ISSUE TITLE
Import Giveaways - auto detect of normal/reverse position

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#267]
Is it really necessary to have there manual selection for normal/reverse position in Importing giveaways? The keys looks always the same and a regular expression can recognize very easily (or recognize an URL to the key).  With the automatic detection we could even combine both - the normal and the reverse position.

**Comment by revilheart** [comment]
Done

**Comment by gizellos** [comment]
Yeah, it's cool. Thanks. :)
