### ISSUE TITLE
[Feature Request] Show new or missing games and groups

### ISSUE THREAD

**Issue by bowlby4** [revilheart/ESGST#268]
After syncing display any new or missing games and groups.

There was a script called [steamgifts.com sync tracker](https://greasyfork.org/en/scripts/5884-steamgifts-com-sync-tracker) that hasn't worked in a long time.

**Comment by revilheart** [comment]
Added, although the script is currently not designed to show game names, so when you sync you will see the app/sub ids with the links to the store.
