### ISSUE TITLE
Can't manage user tags

### ISSUE THREAD

**Issue by Isildion** [revilheart/ESGST#269]
In earlier script version on SG profile settings page was option to see all tagged users, and to manage it from there (option in upper right corner of the page, like "manage checked users caches" now. After preferences were moved to pop up window this option vanished, and trying to manage tags from "tag popup" redirects to SG profile settings.

**Comment by revilheart** [comment]
That feature was temporarily removed when there was a change in how tags are stored. It's been quite a while now, it wasn't when the settings were moved to popup. It will return when I get around to modifying it. I'll see if I can do it this or next week.

**Comment by Isildion** [comment]
Ok. Thanks for this information :D I thought it was the other way around.

**Comment by revilheart** [comment]
It's back.
