### ISSUE TITLE
One-Click Hide Giveaway Button sould not remove the game immediately[enhancement]

### ISSUE THREAD

**Issue by Gittino** [revilheart/ESGST#271]
Hi, I would like to propose an enhancement for the feature "One-Click Hide Giveaway Button". 
Currently when this feature is enabled and the "hide" icon is clicked the game is immediately removed from the list. The problem is that if the icon is pressed by error it is very difficult to know which game has just been hidden and restore it. I would suggest to enhance this feature so that when the icon is pressed the game remains grayed out in the giveaway list till the next refresh of the page. 
In this way if the icon is pressed by error is it possible to notice it to quickly restore the game.
Thanks

**Comment by revilheart** [comment]
Done

**Comment by Gittino** [comment]
Works perfectly! Thanks a lot
