### ISSUE TITLE
Don't highlight a new encrypted giveaway of mine

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#272]
The highlighting is very good but I think it doesn't have much sense to apply it if it finds my own games. In fact it is kinda annoying for me because I "have to" open the list so that the highlighting would disappear.

![2017-07-20_184123](https://user-images.githubusercontent.com/2397851/28428942-4b3434a2-6d7b-11e7-915d-24b1c1108e1d.png)

**Comment by revilheart** [comment]
Done. Although currently it only works for comments, if you add an encrypted giveaway to a discussion, the icon will still turn green.

**Comment by gizellos** [comment]
Nice, thanks.

BTW: if I encrypt a GA that didn't start yet, the GA won't show in the list of Decrypted GAs. Is it a bug or a feature?

**Comment by revilheart** [comment]
The giveaway will only show after it's started.

**Comment by gizellos** [comment]
And does the script remember the giveaways if the user doesn't visit the page with the giveaways again? I mean if the script will show it to them on any page. I hope so.

**Comment by revilheart** [comment]
Any page. When the giveaway starts, the icon will turn green.

**Comment by gizellos** [comment]
That's nice. I asked because I made some encrypted giveaways that haven't started yet by accident and I put them to the OP of my train and I was afraid that most of visitors would not see them.
