### ISSUE TITLE
Create Multiple Giveaways - View Results - add copy links for Encrypted GAs

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#276]
I would like to have copy links in the results of created giveaways for making encrypted giveaways.

(There could be also some other possibilities such as export to RaChart Table or copy all links, or creating encrypted GAs from all, but I already meant this in another issue long time before this create multiple giveaways feature)

**Comment by revilheart** [comment]
I've extended Giveaways Manager to Multiple Giveaways Creator.
