### ISSUE TITLE
Filters don't apply to the last GA before Load More button in Decrypted GAs

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#277]
Try it [here](https://www.steamgifts.com/discussion/2mTOT/) - if you use, for example, show only wishlisted games, it will show the last GA before the button **+ Load More** even if you don't have it in your wishlist. This GA is not filtered.
![decrypted giveaways list](https://user-images.githubusercontent.com/2397851/28475490-c34eafa4-6e4c-11e7-8312-96c208b34cd7.gif)

**Comment by gizellos** [comment]
BTW could it automatically apply the Load More button if all results are filtered?

**Comment by gizellos** [comment]
BTW: It would be good if it automatically loaded next page if all results are filtered.

**Comment by revilheart** [comment]
Someone else was having a similar problem, but they reported it's been fixed. Can you check if this is still happening.

**Comment by gizellos** [comment]
It seems to be OK now. I am closing this.
