### ISSUE TITLE
Fading visited discussions is not working in active discussions/deals

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#279]
As title says...

**Comment by revilheart** [comment]
You mean discussions?

**Comment by gizellos** [comment]
Yeah, sorry.

![2017-07-21_235246](https://user-images.githubusercontent.com/2397851/28483876-c0af5af0-6e6f-11e7-85d2-f74dfaa66509.png)

**Comment by revilheart** [comment]
Should be fixed.
