### ISSUE TITLE
[Bug] Error while trying to update cache

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#28]
![image](https://cloud.githubusercontent.com/assets/10275898/23550598/798d3f4a-ffd7-11e6-8c5e-6421e49d21e6.png)

edit: i managed to work my way past it by manually checking the user it showed being stuck on and the user after that.   now on scan 55 of 2948.   ^^
(the manual check of just the one user(s) didn't get stuck, strange....)

**Comment by revilheart** [comment]
As I suspected, it's because of an username change. That user used to be sirrozha. Will look into it.

**Comment by ldeman** [comment]
lol, i'm always running into those.  ^^
k, sounds good though.

**Comment by revilheart** [comment]
Have you ever ran into this issue again? I was never able to reproduce it and I don't think it was because of username change (you would probably have gotten the same error for me when I changed).

**Comment by ldeman** [comment]
no, i haven't ran into this one again.  i think it's all good now.

i go ahead and close it.  ^^
