### ISSUE TITLE
Entered GA winning chance

### ISSUE THREAD

**Issue by DeadXecuter** [revilheart/ESGST#281]
It says that the winning chance is a 100% for most of the GAs in the entered GA section. A few have a different value like 33.33333% or 25%. If only... :D

**Comment by gizellos** [comment]
The page is overaly broke.

![2017-07-22_013902](https://user-images.githubusercontent.com/2397851/28486063-a024fc36-6e7e-11e7-92fa-da2b7d013acb.png)

**Comment by revilheart** [comment]
Nothing looks broken to me in that image, is there something specific?

**Comment by DeadXecuter** [comment]
Well mine does show those percentages, posting a screenie 
![eukumuh](https://user-images.githubusercontent.com/30358946/28487892-5d448a58-6e9c-11e7-8212-63569f18c5f2.png)

**Comment by revilheart** [comment]
The order in yours is different, that might be the problem. Are you using other scripts?

**Comment by gizellos** [comment]
> Nothing looks broken to me in that image, is there something specific?

Yep, Type, Level and Chance/Ratio are switched. It was OK until yesterday or so. And the only other scripts I have enabled there are RaChart Enhancer and Linkies, but they haven't be updated for a century so they should not cause the problem.

**Comment by DeadXecuter** [comment]
You were right, I didn't have the winning page info enabled on ESGST and was using another script for the same purpose, upon disabling the other one and enabling the one in ESGST the percentages became what they were supposed to be

**Comment by revilheart** [comment]
Ah, that explains it. Closing it then.
