### ISSUE TITLE
SGTools - show notification when checking profile is complete

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#282]
I would like to see a notification when checking my profile is complete. Either changed icon in SGTools tab or changed text. The icon would be better, though.

The problem is that the more giveaways people win/sent, the more time SGtools need to check their profile. I tried to measure it a few minutes ago and it was 1 minute 15 seconds for me. I believe it can be even more if SGTools is being slowed down. It is rather annoying to be there and wait or go to another tab and think about it and try the tab to check if it is already done.

I asked about it the author of SGTools but they didn't respond to the post and I am not sure if they will do it.

**Comment by revilheart** [comment]
But doesn't the page have a loading icon while it's checking?

**Comment by gizellos** [comment]
It has but I cannot see it when I am on another page. The problem is that the checking is very long for users with lots of sent/won giveaways. I cannot afford to wait for it on the SGTools page.

**Comment by revilheart** [comment]
How can you not see the loading icon when on another page?  The icon stays in the tab.

**Comment by gizellos** [comment]
I thought you meant an icon on the page. I cannot see any different icon in the tab white there is checking. I can see only the normal SGT icon that is always the same. 

I would like to check it now and do a screenshot or gif, but I don't have any link to SGT GA. I will check it later.

**Comment by revilheart** [comment]
Ah, you mean checking a giveaway. I thought you meant checking a user.

**Comment by gizellos** [comment]
It depends how you call it. If I want to enter a giveaway, it will check me as a user.

**Comment by revilheart** [comment]
I meant checking a user for not activated/multiple wins.

**Comment by gizellos** [comment]
OK I see. I think it directly on the SGT pages. You can make it as another standalone script if you want. I wrote this issue when you added the steam redirecter to the script and it seemed that the script would have   also support for some other related pages.

**Comment by revilheart** [comment]
Yeah, I'll write another script, since it doesn't make sense to run ESGST on SGTools.

**Comment by gizellos** [comment]
Thanks. :)

**Comment by gizellos** [comment]
BTW I have never seen a loaded icon in the tab white ESGST was performing anything. If there is supposed to be a different icon while I am checking winners of a giveaway  with "Check for not activated / multiple wins:" feature, then I don't see it.

**Comment by revilheart** [comment]
No, I meant on SGTools.

**Comment by gizellos** [comment]
Ok, then it's fine. :)

**Comment by revilheart** [comment]
Done: https://github.com/revilheart/SGToolsNotifier

**Comment by gizellos** [comment]
Super, good work. Thanks a lot. :)
