### ISSUE TITLE
 Giveaway Groups Loader - Endless loading

### ISSUE THREAD

**Issue by Blackbird88** [revilheart/ESGST#283]
It just endlessly loads and doesn't mark the group. Latest Chrome with latest version.
Tried syncing the groups too.
![image](https://user-images.githubusercontent.com/4414625/28493231-32786f2a-6f13-11e7-9706-41a4641aa500.png)

**Comment by revilheart** [comment]
Check console.

**Comment by Blackbird88** [comment]
> Uncaught TypeError: Cannot read property 'textContent' of null
>     at getDiscussionInfo (eval at E_c (:3:221), <anonymous>:26068:46)
>     at getDiscussions (eval at E_c (:3:221), <anonymous>:26051:26)
>     at Array.loadDiscussionFeatures (eval at E_c (:3:221), <anonymous>:26036:23)
>     at loadEndlessFeatures (eval at E_c (:3:221), <anonymous>:26932:37)
>     at eval (eval at E_c (:3:221), <anonymous>:9220:29)
>     at Window.eval (eval at E_c (:3:221), <anonymous>:9262:33)
>     at <anonymous>:2:398
>     at e.string.k.function.c.(anonymous function) (eval at exec_fn (:1:108), <anonymous>:53:352)

**Comment by revilheart** [comment]
Thanks, will fix later.

**Comment by Blackbird88** [comment]
Oh and there's also another minor issue. The window isn't centered properly. When you click on the window however then it centers nicely.

**Comment by revilheart** [comment]
Fixed the bug. I'll look into the style issue some other time, as it's not that important.
