### ISSUE TITLE
No enter buttons - no GA filters - error in console

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#284]
I have quite serious problems with the latest version  v6.Beta.19.12.

I can't see filters and Enter buttons.

> ERROR: Execution of script 'ESGST' failed! Cannot read property 'getElementsByClassName' of null
> (anonymous)
> (unknown) TypeError: Cannot read property 'getElementsByClassName' of null
>     at updateUfCount (eval at E_c (:3:221), <anonymous>:21010:24)
>     at getDiscussionInfo (eval at E_c (:3:221), <anonymous>:26136:33)
>     at getDiscussions (eval at E_c (:3:221), <anonymous>:26098:26)
>     at loadDiscussionFeatures (eval at E_c (:3:221), <anonymous>:26083:23)
>     at loadEsgst (eval at E_c (:3:221), <anonymous>:3064:25)
>     at eval (eval at E_c (:3:221), <anonymous>:417:5)
>     at Window.tms_eafecfdb_d33e_4713_8f83_75a77d76d21c (eval at E_c (:3:221), <anonymous>:27243:3)
>     at <anonymous>:2:398
>     at eval (eval at E_c (:3:221), <anonymous>:3:1)
>     at eval (eval at E_c (:3:221), <anonymous>:4:3)

**Comment by revilheart** [comment]
Need more information, like where it happens.

**Comment by ldeman** [comment]
i think this issue was tied in with the same main page issue i was having until the newer latest update (19.13)

**Comment by revilheart** [comment]
This is related to User Filters though, I don't think it's tied to the other issue.

**Comment by ldeman** [comment]
it may not be actually.  when i had the main page issues i discovered it wasn't loading the group identifiers and % chance to win.  it may of just errored at a different point in the load-up, or a diff error all together.

**Comment by gizellos** [comment]
I saw it on the main page and wishlist page. I didn't try the other GAs pages. A while it is working normally and after a while it is bugged. Refreshes don't help it. 

Also active discussions/Deals are not at the top.

**Comment by gizellos** [comment]
I turn down GA filters and it seems work normally. But it can be just a coincidence.

**Comment by revilheart** [comment]
Do you have any user on the page filtered? Or maybe it's related to your other issue? Try to see if it only happens when a user you filtered is in the active discussions.

**Comment by gizellos** [comment]
No now I can see a filtered user in active discussions and the script is working correctly (although when the person emerged, the bug appeared, but after I refreshed the page, it started to work normally, so it was also just a coincidence).

**Comment by revilheart** [comment]
Not a coincidence, that was the error. Fixed.

**Comment by gizellos** [comment]
Cool, thanks.
