### ISSUE TITLE
[Bug] Remove entries sync button sticking

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#286]
the button itself isn't changing from "cancel" to done or complete or any status at all, it just stays even after completion.
![peek 2017-07-24 08-46](https://user-images.githubusercontent.com/10275898/28526429-25322596-704d-11e7-9923-cb8c48d5a5d3.gif)

**Comment by gizellos** [comment]
For me, the problem is that if I close it and want to leave the page, it asks me if I really want to leave the page. As if it was still running.

**Comment by revilheart** [comment]
Fixed
