### ISSUE TITLE
Send Unsent Gifts - unstyled?

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#287]
There are dots before each of the items. I suppose it's just unstyled tag li.

![2017-07-24_182252](https://user-images.githubusercontent.com/2397851/28533424-5d6ae65a-709d-11e7-9686-ff507e2c27d8.png)

**Comment by gizellos** [comment]
Damn I can see it here too. It seems to be an issue in my browser. I am closing this for now.

![2017-07-24_182604](https://user-images.githubusercontent.com/2397851/28533484-9011ee00-709d-11e7-93c7-f8a6b633eac8.png)

**Comment by revilheart** [comment]
All popups are currently with style issues, but since it's just a style issue they're not my priority at the moment.

**Comment by revilheart** [comment]
Fixed
