### ISSUE TITLE
Quick disabling filters

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#292]
I would like to have the possibility to quickly disable (all) filters. It would be in the filter settings.

**Comment by revilheart** [comment]
Can you be more specific? Disable them, as if the feature was disabled, or just toggle the features from "Enabled" to "Disabled"?

**Comment by gizellos** [comment]
Just toggle a checkbox. So the interface of the filters would still be there, just the filters wouldn't apply to the giveaways.

**Comment by revilheart** [comment]
Done
