### ISSUE TITLE
2.13 Giveaway Winning Ratio misstake

### ISSUE THREAD

**Issue by Sulizab** [revilheart/ESGST#296]
2.13 "Giveaway Winning Ratio" without advanced formula shows wrong. If before enter it maybe right, but after i'm enter it anyway shows one addition point. And it wrong.

Before enter - http://i.imgur.com/nlLe6yY.png
After - http://i.imgur.com/6F8fUTg.png

P.S. I'm sorry but dont found how to reopen ticket after you marked it as invalid.

**Comment by revilheart** [comment]
Well, that one was invalid, but this one is valid, will fix it later.

**Comment by revilheart** [comment]
Fixed
