### ISSUE TITLE
Giveaway info - additional information about active giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#297]
I would like to see how many giveaways of a game is currently running. It could be a number in brackets after the information how many copies of a game I have sent.

**Comment by revilheart** [comment]
All giveaways or just your giveaways? If all, that's never going to happen, the amount of requests necessary for that would be insane.

**Comment by gizellos** [comment]
Just my active giveaways of the game I am looking at. For example, when I look into a rachart table about some new bundle, I can read there that I already given away a game 3 times. But in fact, it is possible that I have some other copies of that game still active as giveaways.

So the info is now: How many copies of the game I have delivered + CV
And I would like to see: How many copies of the game I have delivered (How many copies of the game is active as a giveaway now) + CV

**Comment by revilheart** [comment]
Ah, ok.

**Comment by revilheart** [comment]
I actually added the active giveaways together, hope that's ok. So now it's (copies delivered + giveaways active) and then the CV, taking into account the active giveaways to calculate the CV as well.

**Comment by revilheart** [comment]
But if you want to see the actual number of active giveaways I can add that too.

**Comment by gizellos** [comment]
I think it is OK like that. Thanks.
