### ISSUE TITLE
Synch SteamGifts' Filtered List with Steam's Owned Games

### ISSUE THREAD

**Issue by Laurvin** [revilheart/ESGST#299]
Would it be easy to add an option to synch SteamGifts' [Filtered List](https://www.steamgifts.com/account/settings/giveaways/filters) with Steam's [Owned Games](http://store.steampowered.com/dynamicstore/userdata/) list so it removes games from the Filtered List when they are owned?

I have quite a few games that I put on the Filtered List that I now own (cause of Group Buys, etc.). It would reduce the list by quite a bit and make it more managable and worth going through.

Now I also get owned games that get the Hidden Games Enter Button Disabler treatment; it's correct they get the Disabler but it would be nicer if it just showed the default Exists in Account which it would if the lists were synched.

**Comment by revilheart** [comment]
Added

**Comment by Laurvin** [comment]
Thanks so much!

I went from 68 pages to 40. :D

**Comment by revilheart** [comment]
Nice xD

**Comment by Laurvin** [comment]
I discovered one problem that I fear is impossible to get around...

It correctly removes games like Wyatt Derp and North Side from the list (as I own them). However, cause of the Steam API changes, SteamGifts incorrectly thinks I do not own them and shows giveaways for them to me.

Catch 22...

**Comment by revilheart** [comment]
You can use Giveaway Filters which correctly detects your owned games and hides giveaways for them.

**Comment by Laurvin** [comment]
Damn, never thought of that. Perfect!
