### ISSUE TITLE
Send unsent gifts error

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#301]
Sadly it seems the feature is still bugged. I tried to send 15 games and it stopped to continue the task after a while with this error in console.

> Uncaught TypeError: Cannot read property 'winnerId' of undefined
>     at Window.checkUgsGifts (eval at E_c (:3:221), <anonymous>:11305:55)
>     at <anonymous>:2:398
 >    at e.string.k.function.c.(anonymous function) (eval at exec_fn (:1:108), <anonymous>:54:352)

![2017-07-28_193018](https://user-images.githubusercontent.com/2397851/28729038-4ab1facc-73cb-11e7-9649-6c89fde79d2f.png)

**Comment by gizellos** [comment]
BTW what is checked?

**Comment by revilheart** [comment]
Ah, yeah, I found a bug if all options are disabled. It might take a while until I release the next update, so if you want to temporarily fix it in the meantime, just find the line in the script that says "winner = winners[i]" and change it to "winner = winners[j]".

What do you mean, what is checked?

**Comment by revilheart** [comment]
Fixed
