### ISSUE TITLE
Info for Game Categories didn't load for all games

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#302]
Yesterday, I deleted Game Categories data so that it showed Game Genres without user-defined tags (I am not sure if it was necessary but it doesn't matter).

The data for Game Categories normally started to download on the main page and everything seemed to be normal. But then I went to Recommended page and found out that only one giveaway showed categories such as the genres and trading cards. Today, it is the same just I can see all the giveaways without the genres and trading cards info. 

It looks as if it stopped to download the data for the games that the script doesn't have saved. Is there a limit how many data can be downloaded per day or something like that?

![2017-07-29_205919](https://user-images.githubusercontent.com/2397851/28747550-fc2570b4-74a1-11e7-9cb4-e1c546b3e9b0.png)

**Comment by revilheart** [comment]
Steam has a limit, yes. That might be it.

**Comment by gizellos** [comment]
OK and does the script update it each time when it finds giveaways without the categories or it waits until x days passed since last updating the data?

**Comment by revilheart** [comment]
Only after 1 month if I recall.

**Comment by gizellos** [comment]
It is a lot, don't you think? I have the info just for a part of giveaways and I am not very happy about it. :(

**Comment by revilheart** [comment]
Nope, I don't think game information changes often. I'll make the feature update if the information is incomplete later.

**Comment by gizellos** [comment]
OK, thanks. :)

**Comment by revilheart** [comment]
Should now work as intended.
