### ISSUE TITLE
Expand filters bar blinks while I am scrolling

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#303]
Expand filters bar "blinks" while I am scrolling. You can see it in the gif.

![expand filters blinks](https://user-images.githubusercontent.com/2397851/28834660-2c8dcc86-76e3-11e7-8ca9-137d03a93e54.gif)

**Comment by revilheart** [comment]
I don't see anything blinking.

**Comment by gizellos** [comment]
It has violet color. It slides down from the top of the bar.

**Comment by revilheart** [comment]
Sorry, I'm not seeing it.

**Comment by ldeman** [comment]
i'm not seeing flashing, but the scrolling is a little rough (or it's the gif).  i'd try playing with the amount of lines it scrolls (try lowering it imo).
 
![image](https://user-images.githubusercontent.com/10275898/28836061-23d2fc28-76ad-11e7-8cc3-fc174d914ec5.png)

**Comment by gizellos** [comment]
It's very strange. It may be a bug of rendering just for me. I can see it very clearly when it is moving but when I want to see just 1 frame from the gif, it is not there. I am closing it for now. 

Ideman: I roll just 3 lines and you 9. I am not the one who uses a rough settings for it. :) Looks ok for me, maybe it is just the GIF.

**Comment by ldeman** [comment]
that was just a generic mouse setting page from the internet.  i'm actually in linux atm, so i just found an image off google images to show you.  =)

**Comment by gizellos** [comment]
I already know where the problem is! My monitor does it. I tried it on my secondary monitor and it is normal there.

**Comment by gizellos** [comment]
Ideman: OK, dude, hehe. :)

**Comment by revilheart** [comment]
Ok

**Comment by gizellos** [comment]
Just for you to know what I was talking about.

![ezgif-2-f20684ce3d](https://user-images.githubusercontent.com/2397851/28837176-227576aa-76ec-11e7-9d1b-280e06d464cf.gif)

**Comment by revilheart** [comment]
Ah yeah, now I can perfectly see it. Weird that it's the only element affected in the screen.
