### ISSUE TITLE
Pop up box to reply to the giveaway when win the key

### ISSUE THREAD

**Issue by Mazayw** [revilheart/ESGST#305]
Please add a pop up box to reply to the giveaway when win the key to say "Thank you!" or something else

**Comment by revilheart** [comment]
Please be more specific. When you get the message that you won a giveaway? Or on the won page when you mark a giveaway as received?

**Comment by Mazayw** [comment]
On the won page when you mark a giveaway as received?

**Comment by ldeman** [comment]
huhhh...  simple yet elegant....  love the idea.  =)

**Comment by revilheart** [comment]
Was that a question or a confirmation?

**Comment by ldeman** [comment]
![image](https://user-images.githubusercontent.com/10275898/28995988-95266416-79bc-11e7-8f78-948c8c75366b.png)

**Comment by Mazayw** [comment]
It was demand. Sorry for the typo ;)

**Comment by gizellos** [comment]
+1

**Comment by revilheart** [comment]
Added
