### ISSUE TITLE
Multiple issues when using Firefox Containers

### ISSUE THREAD

**Issue by olloff** [revilheart/ESGST#306]
Hi.

Seems to be ESGST and [Firefox Contextual identity (Containers) feature](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers) not working very well together.
Issues are include but seems to be not limited by:

- [ESGST not respect user level in Endless Scroll mode](https://i.imgur.com/xBF3cTW.png). 
First page loaded correctly, but any async reloaded or loaded subsequently pages are not.

- [Can't enter or leave giveaway using popup](https://i.imgur.com/ZejjPkP.png). 
Entering or leaving giveaway through GA pages is working tho. There is one corresponding line in browser console.
`05:29:28.492 SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data  ESGST.user.js:9688:28`

I believe this could be happening because of Greasemonkey way of storing values and executing XHR.
But can you, please, look into it? Maybe you can find a simpler solution.

BTW thanks for awesome userscript, that's a huge one!

**Comment by revilheart** [comment]
As far as I know, there's nothing I can do about this, since as you mentioned, it's a Greasemonkey issue. I'd suggest going for Tampermonkey or Violentmonkey for Firefox.

**Comment by olloff** [comment]
It's... not exactly an Greasemonkey issue, its more like alltogether. And yes, I already tested Tampermonkey and will continue trying to find different solution.

Seems to be, none of userscript handlers are ready for container isolation (which, afaik present in Chrome too but in a slightly different way). Userscripts like yours are free to choose where to store: in LocalStorage (context-sensitive) or using native functions like gm_setvalue/gm_getvalue.
As you choose second path, your script ignores container isolation which (I believe so) leads to bad behavior with container isolation.
So that's where scary part begins. I'm sure its desired behavior for GM/TM authors as it encourages userscript authors to choose way their script works.

A little disclaimer, I can't really prove my point so I can be horribly worng about those errors.
If i can ask, could you, please, give another thought on that problem? I'm not begging for immediate solution and willing to help you with my time.

**Comment by revilheart** [comment]
Well, if you tested on Tampermonkey and it worked, then it is a Greasemonkey issue, and you can solve it by using Tampermonkey.

My script cannot use local storage as I need the data available across different domains, so like I told you, I don't think there's anything I can do about this. If you have any ideas, I'm happy to hear them, but I need the data available across different domains, and GM_setValue/GM_getValue offers that, and since it works well with Tampermonkey, Greasemonkey isn't my priority.

**Comment by olloff** [comment]
> tested on Tampermonkey and it worked
Sorry, I'll try to be more clear. It's not work with Tampermonkey. There is a couple of other extensions I'd like to test and if one of them works properly, I'll inform you.

Well, I hear you. I hope extension developers can propose some workarounds, though I doubt that could be possible without your participation.

**Comment by revilheart** [comment]
Sorry, I don't understand. It doesn't work with Tampermonkey?

Again, I'm not reluctant to participate, I'm just not sure that there's anything I can do.

**Comment by revilheart** [comment]
I'll see if I can migrate to local storage.

**Comment by olloff** [comment]
> It doesn't work with Tampermonkey?

It works with the errors described earlier. Most of the features are fine either on GM or TM.

> migrate to local storage.

Thanks a lot. But that would be a little premature. Can I assist you to find exact source of the problem? 

I'm trying to figure why ajax.php ain't return any response. First I thought its normal behavior for containered tabs, but appears it isn't - jquery post with payload xsrf_token=819590e31238faebafa7eed326086b8f&do=entry_insert&code=LLJ9l&game_id=7502 returns correct response.

**Comment by revilheart** [comment]
Sorry, this is not my priority at the moment.

**Comment by olloff** [comment]
Well, ok, I hope you find time for this lately.
Cheers!

**Comment by revilheart** [comment]
Hi, I have a theory as to why it happens. If I read correctly, each container has their own cookies, right? So that means each container has their own PHPSESSID, correct? I believe Tampermonkey/Greasemonkey aren't designed to deal with that, which results in them making requests with a PHPSESSID that is not the PHPSESSID of the current container, resulting in a null response from SG. I might be wrong, but that seems to be the most logical explanation.

**Comment by olloff** [comment]
@revilheart This is reasonable explanation indeed, but i believe its not the all case. 
This corresponds with my previous findings: once SG logged in without container, first described bug (ESGST not respect user level in Endless Scroll mode) is no longer present.

I test it by logging in separately within container, without container and in private mode within one browser instance (current Firefox Nightly 57.0a1) under one steam login:
- every SG session got different PHPSESSID;
- within container bug is present;
- without container bug is absent;
- in private mode bug is absent.

I'm not expecting SG instance in private mode to behave same as container tab, bc it got no access to IndexedDB or LocalStorage at all. But I'm still not sure, if gm_setvalue can be reached while in private mode, see https://github.com/greasemonkey/greasemonkey/issues/2199#issuecomment-211446366

But in similar situation other userscripts tending to behave different: SG++ while launched in container tab: for example, has no similar issues in endless scroll mode and though it uses different method to "quick enter" giveaways (it loads page in frame instead of utilizing api of SG), there is no signs it trying to load page with different PHPSESSID. I'm pretty weak in JS and not familiar with ESGST arch, but I'm not sure its clearly a Greasemonkey/Tampermonkey issue.

**Comment by revilheart** [comment]
Sorry, I didn't fully understand your reply. I just did some more tests. The PHPSESSID being requested by Greasemonkey when inside of a container is indeed different than the PHPSESSID of the container, so I'm quite sure the issue is not with the script.

I do plan on replacing all requests to the same domain with Javascript's Fetch API, leaving GM_xmlhttpRequest only for cross-origin requests. That should reduce the problem, and it's the only thing I can do on my side as far as I know, just like I've already moved most of the script's storage to localStorage.

**Comment by olloff** [comment]
@revilheart Sorry, my English is pretty dull, so I'm not the best in explaining complex problems.
I'm just stating, that I test your ESGST along with different script and got all different results whereas variables like PHPSESSID were the same. 
I noticed you use localStorage now and will definitely test newer versions. Please let me know if I can help you either way. Even memes. Especially memes!

**Comment by revilheart** [comment]
All same-origin requests in the script are now made through the Fetch API, I believe you'll able to enter giveaways fine now, not sure about the level filters, haven't tested it.

**Comment by olloff** [comment]
Aaand.... it actually works! Both issues seem to be fixed now.
Thanks, you're magician!

**Comment by revilheart** [comment]
Well, what I did was simply a workaround, Greasemonkey/Tampermonkey devs still need to fix it on their end, but glad to know it worked. :)

**Comment by olloff** [comment]
Was about to create ticket to greasemonkey/greasemonkey by myself but you got me even here )
Thanks again!
