### ISSUE TITLE
Scan people in whitelist and show some info about them in the list of whitelisted people

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#307]
I would like to have a function that would show me these additional pieces of information in the whitelist:

- Contributor Level
- Ratio
- Sent/Won values
- Last Online

It would be also great if I could sort it with this additional info.

**Comment by revilheart** [comment]
This is too complex and not a priority for me, so it might be a while until it's implemented.

**Comment by gizellos** [comment]
Yeah, it's OK. I still have some free slots for whitelists so I can wait. :)

**Comment by revilheart** [comment]
Added
