### ISSUE TITLE
Show the default presets only on pages the presets are for

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#308]
It would be good to show the default presets only on pages the presets are for. So for example, DefaultWishlist would be shown only on the wishlist page.

**Comment by revilheart** [comment]
You mean in the popup? I don't see any purpose of that, sorry. Plus those are only default presets, you can rename them, delete them, etc... And there might be people who want to share the same preset across different pages, so not implementing this.

**Comment by gizellos** [comment]
The purpose is that you really don't need to see the default presets for the other pages. It would be much clearer without it. So if I am, for example, on wishlist page, there are 5 presets more that it is needed. The lists are chaotic because of it. And no, I cannot rename them because it would not help the problem at all, they would still be there. There is not a problem with their names. The problem is that they shown on places where no one needs them. So no matter how I rename the presets, I will never need to have, for example, preset for groups on wishlist page.

Check the picture. It's a screenshot of my wishlist page. All the crossed presets are useless on the particular page and I will never use them there. I need just 3 presets there, the default one and the two I made. Why do I have to have there the 5 ones?

![presets](https://user-images.githubusercontent.com/2397851/28994554-23912e02-79d1-11e7-8622-9ede299f9b42.png)

**Comment by revilheart** [comment]
You can't speak for everyone. I'm sure some people would like to share presets across different pages and it would just be way too complicated to hide those specific presets, so I still don't see the purpose and am still not implementing it. Just drag the presets you use to the top.

**Comment by gizellos** [comment]
No, I like the idea of sharing presets across different pages too. I am talking only about the default presets that was generated by the script. I doubt that people will ever use preset called DefaultGroup for any other pages than for group GAs. If they wanted to use it on more pages, they would make a new presets with a name that fits more to its purpose. This is how it should be used and not to use type specific names for something else.

My suggestion is this: If a preset that was generated by the script is not renamed, show it only on the page for that it was generated. If the preset was renamed, show it everywhere.

People who want to have the list clear will be satisfied (I believe there is more of them) and users who want to use some specific presets for different pages will rename them to a name that fits more its purpose and will be satisfied as well.

**Comment by revilheart** [comment]
Sorry, I'm still not implementing this. The best thing you can do, like I suggested, is move the default presets to the bottom.

**Comment by gizellos** [comment]
OK and what about if every preset had a switch that would enable/disable the sharing? It could be enabled by default (so that you were satisfied). It could be handy overaly, not only because of this issue.

> ...is to move the default presets to the bottom

I didn't know it supports drag and drop too, that's cool! Or I can delete all the default presets and make new ones with more universal names. I suppose they won't create again, right?

**Comment by revilheart** [comment]
Too complex, I'm not doing that either.

Yes, you can rename/delete all default presets if you want, they work just like any other preset. But if you delete a default preset you have to apply another preset to the page, otherwise it will be recreated.

**Comment by gizellos** [comment]
OK, no problem. I deleted all the default presets and kept there just my own ones. It looks and works good. :)

![2017-08-07_005944](https://user-images.githubusercontent.com/2397851/29007836-fd049dd2-7b0b-11e7-93ad-32362fbc822a.png)

**Comment by revilheart** [comment]
Perfect :)
