### ISSUE TITLE
Button for loading new messages

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#311]
I often just refresh the Message page to read the new messages while I am browsing some other web pages. The problem is that with every refreshing the script has to be applied to the whole page and it is quite CPU consuming and slower that it could be.

I suggest a button that would draw new messages to the message page. So technically, it would download the page on the background, cut out the new messages, draw them on the page and applied the script stuff just to the new content + changed the dates of all the other messages (because only the date changes).

This solution could be applied also to some other pages, such as discussions or GA.

**Comment by revilheart** [comment]
I don't like this idea, it's too complex. Why not just refresh the page with Endless Scrolling? That way only the comments will be refreshed.

**Comment by gizellos** [comment]
Because of speed when I need to read new comments while I am on the comments page. The comments are the stuff that slows down the loading the page. If there is, for example, 1 new comment, the script has to process again the whole page which is slow.

I would use it when I am doing something outside SG (for example, I am watching a movie) and I see that I have one unread comment. With this I could read it in a much shorter time.

But it is just an enhancement, it's nothing critical and I don't need it so badly.

**Comment by revilheart** [comment]
I'd rather enhance the script than add this feature. And I am enhancing the script to make it less consuming, but it's a process that takes time.

**Comment by gizellos** [comment]
Yeah. I just hope the script really can be optimized. Do you already know the ways how to make it faster?

**Comment by revilheart** [comment]
Well, in terms of memory consumption, I already moved some of the data to localStorage, which appears to make the script a lot faster, and at least d3m4n said the script is no longer crashing for him and he can now open a lot more tabs without slowing down the browser. I have more plans to reduce memory usage and optimize how the features are loaded (the way some features are currently loaded is not optimal).
