### ISSUE TITLE
Allow rename presets

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#313]
Please allow to rename presets in View/apply presets.

**Comment by revilheart** [comment]
To rename a preset, apply it and rename it in the input field, just like with Giveaway Templates.

**Comment by gizellos** [comment]
It is not so easy like in the templates. :(

If I have one preset applied to more pages I cannot do that, because the preset is not renamed but just one new is created and I would have to change the preset in all the pages. It is quite annoying.

**Comment by revilheart** [comment]
Ok, will see to enhancing it later.

**Comment by gizellos** [comment]
Thanks. 👍

**Comment by revilheart** [comment]
Should be better now.

**Comment by gizellos** [comment]
Yeah, you bet! Thanks. :)
