### ISSUE TITLE
Clear caches in Check for whitelists/blacklist checker - is it still needed?

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#316]
I think there was some issue earlier and that's why you added there the option Clear caches. Is the checkbox still needed? I would remove it if it isn't. People can clear the cache in Manage Data page.

**Comment by revilheart** [comment]
Maybe they want to clear the cache of some users and not all. It's a helpful option.

**Comment by gizellos** [comment]
But why would they do it? I don't understand. The results will be in both cases the same, won't be?

**Comment by revilheart** [comment]
Of course not, in one you're clearing the cache of only the users you're checking,in the other you're clearing **all** cache.

**Comment by gizellos** [comment]
I meant that no matter if I delete the cache or not, the results will be the same. If they whitelisted me and I won't delete the cache, the result will be that they whitelisted me. If they whitelisted me and I will delete the cache, the result will be that they whitelisted me. The same is in cases when they didn't whitelisted me. 

Example:

Let's imagine these users that already were checked and the script has data with the info:

User A - whitelisted me
User B - didn't whitelisted me
User C - whitelisted me

I won't delete the cache and use the check for whitelists feature. The results are:

User A - whitelisted me
User B - didn't whitelisted me
User C - whitelisted me

I will delete the cache and use the check for whitelists feature. The results are the same, just the scanning took longer:

User A - whitelisted me
User B - didn't whitelisted me
User C - whitelisted me

So I don't understand why would anyone delete the cache to achieve the same results for longer time. Maybe the problem why I don't understand that is that I don't understand why it is slower with the deleted cache, because it looks that the script always check the users and it doesn't look like it uses the cache for anything.

**Comment by revilheart** [comment]
The clear cache option is for cases where a problem might have occurred and the script didn't detect the result correctly, therefore being a helpful option.

**Comment by gizellos** [comment]
> The clear cache option is for cases where a problem might have occurred and the script didn't detect the result correctly

Yes but then we are at the very beginning of this issue. Is it still needed? I know there was some problems with the feature after it was created and the option to clear cache helped to some people, but it seems that the feature works well now and the option already might be not necessary there. 

I don't read the whole SG discussion for  the script so I don't know if there are still people who complain about something that can be fixed with the clearing cache. Maybe there are, I don't know. I just know there were some issues with the feature that you solved in updates but these issues couldn't be fixed by clearing the cache, you had to fix them in the script.

**Comment by revilheart** [comment]
What is the harm in keeping the option there, needed or not? It's a useful option. I don't understand where you're coming from.

**Comment by gizellos** [comment]
The harm is that some users can enable it by accident and they will lose some of their data. It's no big deal if it can help to some other users to fix a problem. I just thought you might forgotten to remove it after the feature started to be reliable.

**Comment by revilheart** [comment]
No, they will not lose some of their data, the data will simply be cleared and retrieved again. I also find it hard for someone to enable an option by accident, there's a clear tooltip saying what it does. I would say the feature is far from reliable and it will go through a lot of changes soon.
