### ISSUE TITLE
Added styles getting undefined values

### ISSUE THREAD

**Issue by Anxeal** [revilheart/ESGST#318]
**Bug:** At Line 66, `addStyle()` is called way before settings are loaded, which causes the added styles to have `undefined` as opposed to color values.

**Fix:** Call `addStyles()` after settings are loaded.

I just love to see my game categories in color :v

**Comment by revilheart** [comment]
Just fixed it in 6.24. :)

**Comment by Anxeal** [comment]
Oh :o You uploaded as I was testing and typing :v

Great job with fast development 👍
