### ISSUE TITLE
[Feature Request] Visability of Multi-Copy GAs and new filter option

### ISSUE THREAD

**Issue by Sildorian** [revilheart/ESGST#322]
Heya,

as this script seems to be nearing perfection, there are still two things I´m missing:

**Better visability of Multi-Copy-Giveaways**
When I´m scrolling though the SG-lists, I am mostly focused on the games themselfes and the entry-levels and I too often overlook the (10 Copies) etc.. it would be great to be able to make this more visable, maybe with bold-text and/or color.. bold and red would be my favourite ;)

**Exception-Filter for high winning chance**
The giveaway-filters are awesome! What I would love to see is an additional exception-filter like "min. XX% winning-chance with max. XX minutes left". This way I could (for example) have an exception for all giveaways that still have at least an 1% winning chance when they are ending in under 10 minutes.

I hope these things can be added. 
Cheers and thanks for all the great work! 👍

**Comment by revilheart** [comment]
The new advanced exception tool should allow you to do that, and I've also added a "Minutes To End" filter and a feature "Giveaway Copies Highlighter" to highlight multi-copy giveaways.

**Comment by Sildorian** [comment]
Awesome, exactly what I hoped for and more :)
