### ISSUE TITLE
Add Sent giveaways to Sync

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#323]
It seems that the Sync feature doesn't sync the sent giveaways so the giveaway info is not up-to-date. I suggest to sync it too.

![2017-08-08_211440](https://user-images.githubusercontent.com/2397851/29090047-b1c634b0-7c7e-11e7-9c64-b2c30ab3cda4.png)

**Comment by revilheart** [comment]
No, you can update your giveaway data by re-scanning your profile with User Giveaways Data.

**Comment by gizellos** [comment]
Sure but it is not much comfortable. :(

**Comment by gizellos** [comment]
There are many features that need to sync and the sync feature can sync everything except this one. I don't understand why you have a problem to add it there.

**Comment by revilheart** [comment]
I don't have a problem, I have other plans to keep giveaway data updated that will not involve syncing, so I'd rather not waste my time adding it to the sync, when that would be only temporary until I implement my other plan. Just be patient.

**Comment by gizellos** [comment]
OK, it sounds good. Thanks. :)
