### ISSUE TITLE
Set the minimal chance to win to 0.01 in chance to win indicator

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#324]
The chance to win is sometimes 0 %. I suggest to set the minimal chance to 0.01 %. I understand that mathematically the chance is sometimes nearer to 0 than 0.01 but chance 0 % looks odd. It literary says that you cannot win it. 0.01 may be not so accurate but it says you can win at least.

![2017-08-08_213840](https://user-images.githubusercontent.com/2397851/29091109-22c76690-7c82-11e7-99fd-b117e0ec2825.png)

**Comment by revilheart** [comment]
Done
