### ISSUE TITLE
The new box for Source is too high

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#326]
The new box (button) for Source in Decrypted giveaways list is too high. It looks ugly. I suggest to do it with the same height as the boxes beside it.

Check the attached zoomed screenshot.

![2017-08-10_135011](https://user-images.githubusercontent.com/2397851/29169227-265ce5b2-7dd3-11e7-8e5e-446391fee579.png)

**Comment by revilheart** [comment]
It's not new, it's a style issue that came from Grid View. Fixed.
