### ISSUE TITLE
Progressive saving unfinished giveaways in Create Multiple Giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#327]
I was making a train and I had 90+ giveaways there. Then I closed the page by accident and all was lost. Sure, it was only my fault and I know that I could use Import Giveaways function, that is safe, instead. 

However, anyway, it would be good if the script progressively saved the progress of creating multiple giveaways. It would be saved temporary until the giveaways are successfully created or the Empty button is clicked on.

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Thanks for all.
