### ISSUE TITLE
Confirmation window when one tries to leave the Create Giveaways page with giveaways in queue

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#328]
It would be good to show a confirmation window if someone tries to leave the Create Giveaways page with unfinished giveaways in queue.

**Comment by gizellos** [comment]
This feature could partially solve the [problem with unwanted closing the page.](https://github.com/revilheart/ESGST/issues/327) It would not help in cases when a computer freeze or is turned off because of lack of electricity, for example.

**Comment by revilheart** [comment]
Done
