### ISSUE TITLE
Endless loop before the Send Unsent  Gifts checking is finished

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#329]
When I tried to send some finished giveaways, the number of sent keys didn't update and it got endless loop before the checking was finished. All keys were sent, though.

![2017-08-10_191329](https://user-images.githubusercontent.com/2397851/29182797-73fd5d60-7e00-11e7-9772-5b1b00dd1bc1.png)

**Comment by gizellos** [comment]
I am sorry I screw up the screenshot and the error in the console is not whole.

**Comment by revilheart** [comment]
Can you find `esgst_winners` in your localStorage?

**Comment by gizellos** [comment]
I didn't find it after updating to the newest version. I will see if it will help in about 3 hours when a few of my giveaways end. I will write then.

**Comment by gizellos** [comment]
I sent 5 gifts without problems. It seems you fixed it successfully. I am closing this.
