### ISSUE TITLE
Search cd-keys used in my giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#331]
Sometimes I have a cd-key for a game and I am not sure if I used it in a giveaway or not.

I would like a function that can search cd-keys that I used in my giveaways.

**Comment by gizellos** [comment]
We could use just search in browser if the keys were visible on the created giveaway page. We would just search for the game and clicked on a button that would show the keys on the page. Then we would just use CTRL + F to find them. So just to add the button "show cd-keys".

**Comment by revilheart** [comment]
I'm confused by what you want.

**Comment by gizellos** [comment]
There would be button that would show the keys instead of the links "View". 

![2017-08-13_155802](https://user-images.githubusercontent.com/2397851/29254173-dc673a9c-808f-11e7-9b5f-a0a8b398bfe8.png)

**Comment by revilheart** [comment]
Made something different, hope it's better.

**Comment by gizellos** [comment]
Cool, it's very good. Could you please also add the option stop after finding first key?

**Comment by revilheart** [comment]
That's a bit complicated because it looks for assigned keys and active giveaways clearly haven't been assigned yet, I'll see what I can do later.

**Comment by revilheart** [comment]
Added it.
