### ISSUE TITLE
Different position of Highlighted giveaways item in menu

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#333]
I use [SG Linkies](https://www.steamgifts.com/discussion/D0hoX/) user script and ESGST stopped to show the Highlighted giveaways item in the right place, although the SG Linkies Script was not updated recently.

On all giveaways list pages, the item shown at the bottom of the menu which is not right. On all the other pages it works normal as before.

Maybe the code is not correct on the main page and that's why it occurs. It worked fine until now (not sure which new version exactly broke it). I also noticed a strange grey area while the Featured Container is been hidden. It may be related to it.

Can you fix it?

Here you can see the strange grey area:
![2017-08-12_033256](https://user-images.githubusercontent.com/2397851/29236775-e9683e56-7f10-11e7-9733-af1dbd93c1c2.png)

Here you can see the normal state:
![2017-08-12_033042](https://user-images.githubusercontent.com/2397851/29236777-e96cebae-7f10-11e7-990c-03ebe9d05dff.png)

Here you can see when it is bugged:
![2017-08-12_033015](https://user-images.githubusercontent.com/2397851/29236776-e96c9726-7f10-11e7-9f2f-464c45fee9a4.png)

**Comment by gizellos** [comment]
Here is a video of the Hidden Featured Container. It seems to be also much slower than before.
![hidden featured container](https://user-images.githubusercontent.com/2397851/29236876-cc27e9d4-7f12-11e7-80db-492c9a53523e.gif)

**Comment by revilheart** [comment]
Script conflicts aren't bugs and also not a priority. Try changing the order that the scripts run.

**Comment by revilheart** [comment]
And there's nothing strange about the grey area, it's supposed to be there. You're probably only noticing it now because it's taking longer to load the page, but not sure what I can do about that either.

**Comment by gizellos** [comment]
I am afraid that the pages are generated badly and and it is not a conflict. The SG menu is supposed to be the same on all pages but it is not the same. Or more precisely it was the same until a new update of ESGST. The other script just helped to reveal a possible problem. If a page is generated badly, the browser can have problems to draw it and it can be this case.

**Comment by revilheart** [comment]
The pages are generated the same way they've always been, nothing has changed in that.

**Comment by gizellos** [comment]
It's strange. I will try to contact the author of the other script if they can do anything with that.
