### ISSUE TITLE
Endless Exporting data

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#335]
I selected everything and clicked on Export. The exporting is endless.

There is this in console:

```
Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at manageData (eval at E_c (:3:221), <anonymous>:28110:52)
    at set.toggle (eval at E_c (:3:221), <anonymous>:4954:17)
```

I have the newest version v6.Beta.26.0.

**Comment by revilheart** [comment]
Does clicking the error take you to an exact line in the script?

**Comment by gizellos** [comment]
Unfortunately, it doesn't.

**Comment by revilheart** [comment]
I'm afraid the only way to find the source is then for you to uncheck each option at a time and try exporting, until you find the option that's causing it.

**Comment by gizellos** [comment]
Yeah, I will do it. I will do it more clever though. I will divide it to two halves and I will find which the half it is in, then I will divide the one half to  other two halves, and so on. It should be easy.

**Comment by revilheart** [comment]
Sounds great, that's how binary searches are made. :)

**Comment by gizellos** [comment]
I have it. It is ST Comment History. I don't have enabled ST features in the script so maybe that's the reason.

**Comment by revilheart** [comment]
Should be fixed.

**Comment by gizellos** [comment]
Yep, it works, thanks. BTW maybe it would be better if the option " ST Comment History" of one has "[ST]  Enable ESGST for SteamTrades." disabled.
