### ISSUE TITLE
Train extractor - block hidden games

### ISSUE THREAD

**Issue by martelsmother** [revilheart/ESGST#338]
Games marked hidden do not display as such in the train extractor. Having a red button, similar to on the general giveaway page, would be useful.

**Comment by revilheart** [comment]
Yes, they do. You have to sync through the settings menu.

**Comment by martelsmother** [comment]
I've tried the auto sync and a manual sync. Perhaps I'm misunderstanding what I'm supposed to do. The green "Enter" button still shows as that (instead of a red "Hidden" button) in the train extractor menu.

**Comment by revilheart** [comment]
It previously only showed for people who had Game Categories enabled. I've made it not show the enter button at all in the latest version.
