### ISSUE TITLE
Don't show ?-? in GA templates when precise time is not used

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#339]
I don't use precise time in my templates and I have to look at the ?-? in the GA template list. Please don't show it if  both the precise time checkers are not checked. It is not needed there.

![2017-08-14_135610](https://user-images.githubusercontent.com/2397851/29270873-fd4b6d50-80f8-11e7-90dc-f58fab71a460.png)

**Comment by revilheart** [comment]
Done

**Comment by gizellos** [comment]
Looks good, thanks.
