### ISSUE TITLE
"Full CV", "Reduced CV" and "No CV" categories doesn't show themself

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#340]
I enabled all "Full CV", "Reduced CV" and "No CV" categories and I cannot see there on the place where they should be seen. They are not even in list of categories.

It works for me in the secondary Vivaldi browser, though. I don't know what helpful info I could tell you. There are no errors in the console. Before the update I had disabled the bundles/non bundled categories. I synced all in ESGST sync, I wiped the storage. And I changed the order of the categories before the update that brought the that feature.

![2017-08-14_233651](https://user-images.githubusercontent.com/2397851/29293083-f2a5ba12-8149-11e7-9dde-fb1b904aca32.png)

**Comment by revilheart** [comment]
Try in the latest.

**Comment by gizellos** [comment]
Yeah, it works. Thanks.
