### ISSUE TITLE
[Feature Request] Ideas for Train Extractor

### ISSUE THREAD

**Issue by Marabon** [revilheart/ESGST#341]
Hey, thank you for this great script and all your hard work on it!

I have two ideas for the train extractor.

1. Would it be possible to summarize the amount of Points needed to join all GAs in a train?
Something like this: http://i.imgur.com/i9Qmsjz.png

2. Is there any way to have join buttons added to the extracted list of GAs?
Something like this: http://i.imgur.com/nXD2AJY.png

Hope these haven't been requested before, I tried searching around but didn't see anything similar to these suggestions.

Thanks in advance!

**Comment by gizellos** [comment]
The join buttons are there, you just have to activate them in ESGST Settings. It's "Enter/Leave Giveaway Button".

**Comment by Marabon** [comment]
Ah, so they are. I'm using another extension which has the ability to auto-join stuff as well. That's why I must've not enabled that feature.

Don't suppose you've considered such a feature in this script? Would kinda remove the need for that other one :)

Anyways, a summarize of the train Points needed would be handy :)

**Comment by revilheart** [comment]
Added both.
