### ISSUE TITLE
Missing background on some reviews game categories

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#343]
Some giveaways have missing background of their reviews game categories.  For example, [this one.](https://www.steamgifts.com/giveaway/C76WI/destroyer-invasion)

It's since v6.Beta.26.4 or v6.Beta.26.3. No errors in console.

Edit: here is the html of one problematic review. There is some undefined stuff - it may be the problem.

`<a class="esgst-gc esgst-gc-rating esgst-gc-rating-?" href="http://store.steampowered.com/app/560400" title="79% (104 Reviews)"><i class="fa fa-undefined"></i> 79% (104 Reviews)</a>`

![2017-08-15_034732](https://user-images.githubusercontent.com/2397851/29299079-8037cf74-816c-11e7-920a-616816d0db6d.png)

**Comment by gizellos** [comment]
It's kinda strange since because it doesn't have problems with all three reviews colors. 
![2017-08-15_034827](https://user-images.githubusercontent.com/2397851/29299111-b4fee3d2-816c-11e7-8e0f-0354960f5adb.png)

**Comment by revilheart** [comment]
Currently fixed. There could be more in the future, but it's something I have to maintain in the Google Sheet, so no need to open more issues about it.
