### ISSUE TITLE
[Feature Request] Shortcut Keys

### ISSUE THREAD

**Issue by mmuh** [revilheart/ESGST#348]
Hey Rafael,

i've been using the shortcut key script, but unfortunately it's not fully compatible with your script (e.g. popups, modified reply boxes, inbox reply), so i wanted to ask you if you would add the function to yours :)

Below is the original scripts feature list, i personally use all but the next/last page ones. 

On the main page or giveaway list search results:
Ctrl + E: focus on the search box
Ctrl + Right: next page
Ctrl + Left: previous page

On a giveaway:
Ctrl + E: enter the giveaway
Ctrl + Shift + E: remove your entry

On a comment, support or discussion page:
Ctrl + Space: focus on the "new comment" text area
Ctrl + Enter: submit your comment
Alt + R or Alt + R: Insert the name of the user to whom you typing a reply
Alt + O: Insert the name of the user who created this discussion or giveaway

edit: additional a shortcut for filter on/off would be a nice one that acts inside a GA as put game on filter  list and ctrl + enter to confirm the popup

**Comment by revilheart** [comment]
>> additional a shortcut for filter on/off would be a nice one that acts inside a GA as put game on filter list and ctrl + enter to confirm the popup

I don't understand anything in this sentence, can you make it clearer?

**Comment by revilheart** [comment]
asd

**Comment by mmuh** [comment]
Oops sorry, i wrote that very chaotic. What i meant was one or multiple shortcuts for the filtering actions.

http://i.imgur.com/xdGsa7u.png
alt + q (e.g.)  On Main/Search/TrainExtractor: Turn  filters on/off (1)
alt + q Inside GA: Hide game (2, put on SG hidden games list)  
alt + shift + q inside GA: hide single GA (3)

On "Would you like to hide all giveaways for $game" popup. enter or alt + q = yes, esc = close

**Comment by revilheart** [comment]
Added

**Comment by mmuh** [comment]
Thank you very much once again Rafael :)
