### ISSUE TITLE
[Bug] Flakey SGTools Highlights

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#35]
i noticed several users aren't highlighting at all and then i saw this incorrect highlight and was able to get it to happen twice (second time i started the gif) -- semi-large gif and i wasn't able to replicate the incorrect highlight within the shot, but as you can see it's not even highlighting them at all instead.
![peek 2017-03-04 18-18](https://cloud.githubusercontent.com/assets/10275898/23583347/989a4406-0107-11e7-9cf9-28a8d980d243.gif)

**Comment by revilheart** [comment]
You sure that person has no multiple wins? I can only see "0 not activated wins", but that doesn't guarantee they don't have multiple wins.

**Comment by revilheart** [comment]
I can see the names are becoming bold though, so it might be an issue with the color and the dark theme.

**Comment by ldeman** [comment]
sorry, yeah, they are clean. i cut-off the gif too short.  but on top of that, notice ambidot loses his green after a refresh also and it doesn't come back with all those refreshes.. so it's both showing correct for some users, and incorrect for others, or not working at all.

https://www.steamgifts.com/user/quijote3000
![screenshot from 2017-03-04 18-31-20](https://cloud.githubusercontent.com/assets/10275898/23583392/d7f6d924-0108-11e7-9607-f9f4826c8038.png)

**Comment by revilheart** [comment]
Yep, I just did some tests with the dark theme and getting the same issue as well. Will try to find the source of it.

**Comment by ldeman** [comment]
well, not just in dark theme.  i was just about to agree but i found another instance without it. 
![image](https://cloud.githubusercontent.com/assets/10275898/23583425/bbdea982-0109-11e7-9fda-44a3330e075a.png)

**Comment by revilheart** [comment]
Got it, my color is being overwritten by the dark theme. Squished will have to fix this on his side. `table__column__secondary-link` has a color with an `!important` tag, so it replaces my color. That at least explains it not showing up in some cases. I'll look into the scenario of it actually showing the wrong color.

**Comment by revilheart** [comment]
Can you right click on the link and inspect it and take a screenshot of the element window?

**Comment by ldeman** [comment]
anything need opened up or this enough? 
![screenshot from 2017-03-04 18-41-59](https://cloud.githubusercontent.com/assets/10275898/23583444/53e84da0-010a-11e7-8e9f-6e03bc44623c.png)

**Comment by revilheart** [comment]
Yeah, it's actually injecting the wrong class, so colors mixup doesn't seem to be the issue. It would be great if you could find this line in the script:

```
Name = (User.NAMWC.Results.None || (User.NAMWC.Results.Activated && User.NAMWC.Results.NotMultiple)) ? "NAMWCPositive" : "NAMWCNegative";
```

And add `console.log(User.NAMWC.Results);` at the end of it to see what's stored in the results.

**Comment by ldeman** [comment]
Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotActivated: 0, Unknown: false, NotMultiple: true, Multiple: 0}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: false, NotMultiple: false, NotActivated: 0, Multiple: 0, Unknown: true}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}Activated: trueMultiple: 0NotActivated: 0NotMultiple: trueUnknown: false__proto__: Object
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {Activated: true, NotMultiple: true, NotActivated: 0, Multiple: 0, Unknown: false}
VM2932:4631 Object {}
VM2932:4631 Object {Activated: true, NotActivated: 0, Unknown: false, NotMultiple: true, Multiple: 0}



also i realized the dark issue doesn't seem to occur if i make dark theme load before rhSGST in tampermonkey load order. (for this test it was still disabled though)

**Comment by revilheart** [comment]
There you go: `Activated: false, NotMultiple: false, NotActivated: 0, Multiple: 0, Unknown: true`. For some reason it saved false to both Activated and NotMultiple even though there are actually 0 occurrences for both of them. Does re-checking them fixes it?

**Comment by revilheart** [comment]
Wait, that's actually a private profile.

**Comment by ldeman** [comment]
yeah, i'm getting both is why.. 
![screenshot from 2017-03-04 18-58-10](https://cloud.githubusercontent.com/assets/10275898/23583521/8d3166c6-010c-11e7-9e2d-60cff7f60433.png)

**Comment by revilheart** [comment]
Yeah, private profiles can't be checked for not activated wins so they are considered with not activated wins. I'll have to change the title to "has ? not activated wins" to avoid confusion.

But that still doesn't explain the other case, because his profile wasn't private.

**Comment by ldeman** [comment]
no, but a recheck on the other case did fix theirs.

and the load order only fixes the issue with dark theme on the /discussions page, within an actual /discussion it still doesn't work properly due to that.  so squished will still have to fix that.

so tbh, i'm not sure if any of it is actually a bug on your end at all.

**Comment by revilheart** [comment]
Do you remember if you checked these members before v4.0? It's possible that it's still not detecting those old results correctly, I'll have to do some testing. Also, would you prefer that the users with private profiles showed up with a different color, like yellow? I don't think it's right to show them up as green.

**Comment by ldeman** [comment]
not only is it possible, it is extremely likely.  90% of my results are from day1 when there was multi-scanning.  i scanned 4-5 groups and a few pages of my sent games (currently 1000 users in the sgtools scans)

yes though, i think yellow for private profiles / steam community down would be best.

**Comment by revilheart** [comment]
Changed it to grey because yellow was not looking good, at least on default theme.

**Comment by ldeman** [comment]
that looks good to me, and i think now this one can be closed really too now if i'm not mistaking. the only part left i think was squished's dark theme compatibility on his end.

i'll leave it open for you to close in case i'm mistaking.

thanks again

**Comment by revilheart** [comment]
Well, there's still the bug about the results from versions prior to v4.0, I still have to look into that.

**Comment by ldeman** [comment]
i think this one has worked itself out by now, or tbh is rather insignificant anymore (anything that old needs a rescan anyways).  you're welcome to close it if you want though.  xD

**Comment by revilheart** [comment]
Yeah, the script no longer offers support for most stuff from v4 anyway.
