### ISSUE TITLE
Popups are not wide enough for their content

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#350]
There are a lot of popups that are not wide enough for their content. It's a new issue.

![2017-08-15_225028](https://user-images.githubusercontent.com/2397851/29335850-470008de-820c-11e7-901b-66ff58023f0c.png)
![2017-08-15_224942](https://user-images.githubusercontent.com/2397851/29335851-47098bde-820c-11e7-9e31-1180d34112f8.png)
![2017-08-15_230221](https://user-images.githubusercontent.com/2397851/29336385-e47595ba-820d-11e7-823d-a95957ae3c60.png)

**Comment by revilheart** [comment]
*Popups. Popouts are the ones that pop out of the element, either above or below it, popups are the ones that pop up in the screen.

**Comment by gizellos** [comment]
Yeah, thanks. I am not able to remember that. :(

**Comment by revilheart** [comment]
Should be fixed.

**Comment by gizellos** [comment]
It works, thanks.
