### ISSUE TITLE
Error in console on giveaway pages

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#352]
I was on the main SG page and I noticed that most of pages didn't have game categories tags for the giveaways. So I checked console and I saw there this:

```
VM387:24826 
Uncaught TypeError: Cannot read property '348310' of null
    at eval (eval at E_c (:3:221), <anonymous>:24826:30)
    at Function.onload (eval at E_c (:3:221), <anonymous>:4842:21)
    at <anonymous>:2:398
    at eval (eval at exec_fn (:1:108), <anonymous>:31:494)
```

After a few minutes I tried it again and everything worked and the error was not there.

![2017-08-16_184733](https://user-images.githubusercontent.com/2397851/29375285-b7d41426-82b4-11e7-9c6d-69cedb50f2ff.png)

**Comment by revilheart** [comment]
It's because you made too many requests to the Steam store in a short amount of time. I've added something that prevents the bug from happening in the future.

**Comment by gizellos** [comment]
Yes I did a lot of requests but I didn't expect any problems because I thought the giveaways already had the data in a cache. I believe that the script already downloaded the data for most of the games yesterday or the day before. Isn't there a problem with caching?

**Comment by revilheart** [comment]
The cache is now 24-hour long to prevent the data from becoming too large and also updating the rating count.

**Comment by gizellos** [comment]
It is too little in my opinion I would set it to at least a week.  And it should be set separately for every the game (if I understand it correctly, now the whole cache is deleted once a day, right?).

**Comment by revilheart** [comment]
I'll set to 1 week in the next update, but it could lead to a large storage for users that make too many requests, and the cache is stored in localStorage, which is limited. No, it should not be separated for each game.

**Comment by gizellos** [comment]
If it is not separate, the games that are in the cache just short time are unnecessarily deleted and that's a pity. That's why I think it. But I suppose that if it was so easy, you would do it. 

BTW: what about making an additional storage from user's google drive? Is it possible and usable? So by default, the used storage would be the same as now and people could activate also secondary storage on their google drive.

**Comment by revilheart** [comment]
Ok, I get your point, will make it separate in the next version.

Don't know if possible, but I'm not doing that, I'm trying to reduce the script's storage, not increase it.
