### ISSUE TITLE
Sometimes space cat does not appear when winning giveaways.

### ISSUE THREAD

**Issue by revilheart** [revilheart/ESGST#353]
[Source](https://www.steamgifts.com/go/comment/6vqIuo2)

**Cause:** Most likely the fact that pages are being fetched all the time when using the script, and the space cat might be in one of those pages, therefore being lost in the process.

**Solution:** Look for the space cat popup when fetching every SG page. What to look for:

```
<div class="popup popup--gift-received">
    <img src="https://cdn.steamgifts.com/img/winner/animated/1.gif">
    ...
</div>
```

**Comment by gizellos** [comment]
I have this problem also with the "One of your giveaways ended" popup.

**Comment by revilheart** [comment]
Ah, that one is easier to test because I can just make a fake giveaway and wait 1 hour. Thanks for reporting it.

**Comment by revilheart** [comment]
@gizellos Could you please give me the class of the "One of your giveaways ended" popup when one of your giveaways end? I don't think giveaways ended with 0 entries give the popup so I am unable to test it. I'm thinking it could be "popup--giveaway-ended", but I'm not sure.

**Comment by gizellos** [comment]
Yes in an hour. I just hope it will show to me.

**Comment by gizellos** [comment]
Unfortunately, it didn't show. :/

**Comment by revilheart** [comment]
Ok, no problem.

**Comment by gizellos** [comment]
The whole code is this:

```
<div class="popup popup--gift-sent" style="left: 698.89px; position: absolute; top: 288.5px; z-index: 9999; opacity: 1; display: block;">
				<i class="popup__icon fa fa-gift"></i>
				<p class="popup__heading"><span class="popup__heading__bold">One of your giveaways has ended.</span><br>Thanks for sharing with us!</p>
				<a href="/giveaways/created" class="form__submit-button"><i class="fa fa-arrow-circle-right"></i> View Winner and Send Gift</a>
				<p class="popup__actions">
					<span class="b-close">Close</span>
				</p>
			</div>
```

**Comment by revilheart** [comment]
I've added the class to the last update. Do you have any giveaways ending soon that we can test?

**Comment by gizellos** [comment]
Tomorrow I will try it. But its behavior was kinda random so I am not sure if one or two testing will be enough. We will see. :)

**Comment by revilheart** [comment]
It's not random at all, all you have to do is: when a giveaway is about to end you don't load a single other SG page and you wait until about 1 minute after the giveaway ended to click on "Refresh current page" on Endless Scrolling. That should trigger it.

I'm currently entered on a few good chance giveaways, so I might test it myself.

**Comment by revilheart** [comment]
Appears to be working, as confirmed [here](https://www.steamgifts.com/go/comment/7hMgOLB), so closing this.
