### ISSUE TITLE
Allow to send all giveaways directly from the "One of your giveaways ended" popup

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#354]
It would be good if we could use the "Send unsent gifts" feature directly from the "One of your giveaways ended" popup. Maybe the "Send unsent gifts" popup could replace the "One of your giveaways ended" popup.

**Comment by revilheart** [comment]
I don't like this idea. If the popup was to be closed, you wouldn't be able to open it again, and to add the Unsent Gifts Sender button in the main page wouldn't make sense. It's better to keep it the way it is.
