### ISSUE TITLE
Gridview enter/leave buttons.

### ISSUE THREAD

**Issue by Sulizab** [revilheart/ESGST#356]
With turned on 15.1 feature this buttons hidden on gridview popups.

15.1. [SG] - [NEW] Only enable for popups.

**Comment by Sulizab** [comment]
For now it working in reverse mode, or i misunderstand something?

**Comment by revilheart** [comment]
It's working correctly, with the option enabled it only shows in popups. Grid View isn't a popup. Giveaways Encrypter/Decrypter and Train Giveaways Extractor are popups.

**Comment by Sulizab** [comment]
Then i move mouse on any GA it open popup window without enter/leave button! Or this is not popup?
