### ISSUE TITLE
Filters doesn't apply to the first page until I scroll to second one

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#359]
This is a new issue since. Filters doesn't apply to the first page until I scroll to second one. Then the scrolling reach the second page, I can see there a big lag and then the filters apply to the first one. And it is like this with all the other pages so I have to reach the third page so that it would apply to the second page, fourth page for applying to the third page and so on.

I tested it with filter (show only RPG genre).

**Comment by revilheart** [comment]
Are there errors in the console. It's filtering fine for me.

**Comment by gizellos** [comment]
No, just 403 status because of ESGST icom. 

`Failed to load resource: the server responded with a status of 403 (Forbidden) - esgstIcon.ico `

I just made a gif of the issue. You can see there that the game categories are already downloaded but the filter doesn't filter them on the page 1 until I reach page 2. All GAs with RPG genres should not be there.

[Here](https://ibb.co/igmYuv) is the gif.

**Comment by revilheart** [comment]
There are 26 giveaways filtered. You said "filters don't apply". You didn't say "genre filters don't apply".

**Comment by gizellos** [comment]
Yes, sorry. Not filters overaly but just some part of them. Genres and Rating in my case.

**Comment by revilheart** [comment]
Should be fixed.

**Comment by gizellos** [comment]
Yes, it works well. Thanks.
