### ISSUE TITLE
Bug; Hidden Blacklist Stats not working.

### ISSUE THREAD

**Issue by Laurvin** [revilheart/ESGST#362]
I have this feature enabled but still see the red line for blacklists on the [Stats page](https://www.steamgifts.com/stats/personal/community).

**Comment by revilheart** [comment]
Do you have other scripts that could be conflicting? Or errors in the console? It works fine for me.

**Comment by Laurvin** [comment]
Turns out there is an error in the console:

> jQuery.Deferred exception: chart_options is not defined loadHbs/<@file:///<snipped file location>ESGST/ESGST.user.js:6152:17
> j@file:///<snipped file location>ESGST/jquery.min.js:2:29997
> g/</k<@file:///<snipped file location>ESGST/jquery.min.js:2:30313
> checkLock@file:///<snipped file location>ESGST/ESGST.user.js:4544:13
> createLock@file:///<snipped file location>ESGST/ESGST.user.js:4537:9
> loadGed@file:///<snipped file location>ESGST/ESGST.user.js:8154:9
> loadFeatures@file:///<snipped file location>ESGST/ESGST.user.js:3198:13
> loadEsgst@file:///<snipped file location>ESGST/ESGST.user.js:2707:29
> @file:///<snipped file location>ESGST/ESGST.user.js:39:5
> @file:///<snipped file location>ESGST/ESGST.user.js:36:2
>  undefined

I'm using Firefox/Greasemonkey and the rest of the script works just fine.

**Comment by revilheart** [comment]
Should be fixed.
