### ISSUE TITLE
Opening attached images in popups

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#364]
It would be good if attached images were opened in popups.

**Comment by revilheart** [comment]
They are. Or they should be, where are they not?

**Comment by gizellos** [comment]
For me they just normally open. I just tried it on [this page.](https://www.steamgifts.com/discussion/fFJnR/pilda-lvl-8-and-2k-sent-celebration-train-lvl-3) The picture in the OP do it the same as the picture by Mully.

**Comment by revilheart** [comment]
Ah, I thought you were talking about something else. I guess I can add that, although I don't really see the point or usability of it.

**Comment by gizellos** [comment]
The point  is the same as images in popups anywhere else. You don't have to load the page again when you go back from the image to the SG page, it is easier to close the image because you just have to click anywhere outside the image instead of clicking on the back button and if you implement there also back/next buttons, then it is much easier to see all attached images.

**Comment by revilheart** [comment]
Added
