### ISSUE TITLE
Error message instead of changelog

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#366]
I wanted to see the changelog and I got this error message:

```
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
Error 503 Backend is unhealthy
Backend is unhealthy
Guru Mediation:
Details: cache-hhn1525-HHN 1503323192 4003999724
Varnish cache server
```

No errors in the console except the esgstIcon.ico  error.

![2017-08-21_154652](https://user-images.githubusercontent.com/2397851/29522065-3f2a3ce4-8688-11e7-8b7b-2a93c89cc56d.png)

**Comment by revilheart** [comment]
Probably something in GitHub.
