### ISSUE TITLE
Estimated level after all my giveaways end is not working

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#367]
I created a bundled giveaway for 3 points and it shows me 8.07 (8.7).  I synced all and it didn't help. Before I created the giveaway, it showed me the same (there was just 1 bundled giveaway for 2 points, but it was created before the new function).

When I had, for example level 8.02, it showed me 8.02 (8.2), when 8.03 it showed me 8.02 (8.3).  Do you see the similarity? Well, the giveaways were created before the new feature so it was supposed to not work with the giveaways, but I would expect so that the script would not show anything instead  of the meaningless number.

**Comment by revilheart** [comment]
I'm confused, so were the giveaways created before or after the feature?

**Comment by revilheart** [comment]
Does the projected bar appear correctly? If so, the feature is working, but is not showing the correct tooltip.

**Comment by gizellos** [comment]
1. I created a GA for 2 points.
2. I updated ESGST to the version with the feature (and it showed something like 8.02 (8.2))
3. I created a GA for 3 points and it shows me 8.07 (8.7). 

But you can forget about the first giveaway since it was created before the feature. I wrote it just because I expected to see there just 8.02 or 8.02 (8.02) when there was any created giveaway after the update to the version (and it was not supposed to work).

I am not sure if I can see the projected bar because the CV for the 3 points GA is not much. It's from 8.07 to 8.07. So I cannot see it there. I would have to make more giveaways so that the level would be at least 8.08 to see it.

![2017-08-21_172300](https://user-images.githubusercontent.com/2397851/29526561-699e6082-8696-11e7-8a56-231f6bbcabed.png)

**Comment by revilheart** [comment]
Yeah, then the feature is working fine. It's just because instead of adding a 0 to the 7, so it's shown as 8.07, it's being shown as 8.7. I'll fix the tooltip in the next version.

**Comment by revilheart** [comment]
Should be fixed.
