### ISSUE TITLE
Duplicate games in Sent Giveaways Data

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#368]
I checked [this user](https://www.steamgifts.com/user/LastM) and I found there a lot of duplicate games.

![2017-08-22_214747](https://user-images.githubusercontent.com/2397851/29584347-ba2e89bc-8783-11e7-97dd-a68615e8a14a.png)

**Comment by revilheart** [comment]
Fixed, use the "clear cache" option to correct it.
