### ISSUE TITLE
Highlight user defined genres and put them to the beginning of the list of genres in Game Categories

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#369]
I use Game Categories - Genres and in fact, the only genre I am interested in is mostly RPG. I would like to have the possibility to highlight this genre and put to the beginning of the list of genres (because it can be hidden in tooltip and it is more easy to find if it is at the beginning, anyway).

In ideal case, every the user defined genre could have set its own color of the highlight (the highlight would be just font color). One color for any defined tags, would be enough too, though.

**Comment by revilheart** [comment]
I thought you had said that the genre filter was enough when you requested this in the past?

**Comment by gizellos** [comment]
I don't know what I said before.  However this would work also in tables. It is not filter related.

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Thanks. :)
