### ISSUE TITLE
The plus button in Genres settings doesn't do anything except moving all the text by a few pixels

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#371]
I am not sure what the plus button is there for. If I click on it, all the text in settings just moves by a few pixels.

![genres sub options](https://user-images.githubusercontent.com/2397851/29668398-581f6c4c-88e0-11e7-800c-92814f2c8b74.gif)

**Comment by revilheart** [comment]
It's not supposed to do anything, it's a tooltip.

**Comment by gizellos** [comment]
I think it is kinda confusing. The sign plus is mostly used for a button that reveal a hidden content.

**Comment by ldeman** [comment]
in this instance it's just to identify the possibility of hidden content.  (depending on settings)

**Comment by revilheart** [comment]
Buttons are clickable, when you hover over the icon the mouse cursor stays as default, so I don't think it's that confusing. I don't know what other icon I could use to represent it.

**Comment by revilheart** [comment]
Changed it to an ellipsis.

**Comment by gizellos** [comment]
I think even the plus would be Ok if it was visible only when the options are packed. But the moving when I click on it is strange, anyway. It behaves like a button even with the default cursor.

**Comment by revilheart** [comment]
The moving when you click on it is just the popup readjusting its size, it happens every time you click a popup. I think the current way is the best way. Changing the icon when it's packed/unpacked would be too complex.

**Comment by gizellos** [comment]
Ok, no problem.
