### ISSUE TITLE
Importing giveaways is broken

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#372]
Importing giveaways is broken because of these reasons:

1. The popup is not wide enough so 99 % of games are on two rows and it is very hard to orient there
2. The popup is so high, that the button for importing is not visible
3. the beginning of the texterea shows keys that are not the first ones in the list so they cannot be edited

![no visible button](https://user-images.githubusercontent.com/2397851/29677603-e7ade422-88fb-11e7-934a-af5a2c5c1aa7.png)
![hidden keys](https://user-images.githubusercontent.com/2397851/29677611-ec08d324-88fb-11e7-94e8-0cca8e1148b6.png)

**Comment by revilheart** [comment]
Click on the popup and it should readjust itself, making the button visible.

**Comment by revilheart** [comment]
Also, you can use arrow keys to move upwards in the text area. So nothing is broken, it just needs some style enhancement.

**Comment by revilheart** [comment]
Should be better now.
