### ISSUE TITLE
If I check for whitelists only, there is also info about blacklists

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#374]
If I check for whitelists only (with deactivated Show blacklist information), there is also info about blacklists. I would like to not see it there the B-word at all. So instead of the sentence "You are neither whitelisted nor blacklisted by" I would like to see there "You are not whitelisted by" and instead of "You are not blacklisted and there is not enough information to know if you are whitelisted by" I would like to see there "There is not enough information to know if you are whitelisted by".

**Comment by revilheart** [comment]
Done
