### ISSUE TITLE
I can't see encrypted giveaways that I posted before they began

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#375]
I asked about this a while ago but it seems it is not working.

I made [a train](https://www.steamgifts.com/discussion/dIA6I/) and accidentally I put there 3 encrypted giveaways that hadn't started at that time.

The 3 giveaways already started and I cannot see them in the list of Encrypted giveaways. They are not in both - in the topic and anywhere else.

I am afraid that people who entered the topic before the giveaways started cannot see them now. One of them has 1 entry so there is someone who can see them.

**Comment by revilheart** [comment]
Weird, they appeared fine for me, and I had visited that thread before.

**Comment by revilheart** [comment]
I fixed it by allowing giveaways that have not started yet to appear normally. If the user doesn't want to see giveaways that have not started yet they can just use the filter anyway.

**Comment by gizellos** [comment]
Thank you. Maybe it was an issue only for me as an creator. Thanks for fixing it and thanks also for the other features you just implemented. :)
