### ISSUE TITLE
Shortcut keys in textarea.

### ISSUE THREAD

**Issue by Laurvin** [revilheart/ESGST#377]
Assuming the default for "Go to the next page" is Ctrl + arrowright then this and the other Ctrl + arrow shortcut keys are a problem on Firefox.

I was creating a post in the default comment box at the bottom of the page and pressed Ctrl + arrow left to move the cursor back one word. However, this is apparently overriden by the shortcut keys set by ESGST and it loaded the previous page, making me lose all the text in my post.

Is there a way for them not to fire when the focus is on a input or textarea? Otherwise, I would suggest changing the defaults.

**Comment by revilheart** [comment]
They should not fire inside a text area, it looks like this is happening only in Firefox.

**Comment by revilheart** [comment]
Nevermind, I found an issue.

**Comment by revilheart** [comment]
Fixed
