### ISSUE TITLE
Giveaways tools doesn't generate encrypted GAs correctly

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#379]
Stars for encrypted giveaways are not shown in comments and I am not sure if the GAs are detected at all.

**Comment by revilheart** [comment]
Which comments?

**Comment by gizellos** [comment]
Comments where I put some encrypted giveaways to.

**Comment by revilheart** [comment]
If it's the latest comment you made in the ESGST thread, there's a bug in giveaways generated by Giveaway Manager where it's not adding "ESGST-" to the beginning of the encrypted code. I'll fix that later, but you'll have to edit your comments manually to make them appear.

**Comment by gizellos** [comment]
Aha, you are right, the giveaways are generated there. OK. :)

**Comment by gizellos** [comment]
Should I rename this issue?

**Comment by revilheart** [comment]
Up to you, I'll fix it shortly.

**Comment by revilheart** [comment]
Should be fixed.
