### ISSUE TITLE
[Enhancement] Refresh "Not enough points" also inside GAs

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#38]
When I am inside a giveaway, don't have enough points for it and I will get the points finally. The "Not enough points" button doesn't refresh. Please refresh it too.

![2017-03-05_171153](https://cloud.githubusercontent.com/assets/2397851/23589058/206b0888-01c7-11e7-880b-f00eb7490353.png)

**Comment by revilheart** [comment]
It would be a pain to implement something like this, and I don't think it's worth it, you can easily refresh the giveaway page when you see that you now have enough points. So I won't implement this, sorry.
