### ISSUE TITLE
Error in console while syncing 

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#380]
Syncing cannot be finished because it is stuck on Owned/Wishlisted/Ignored Games. Maybe an issue with alt account?

```
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at continueGameSync (eval at E_c (:3:221), <anonymous>:5159:35)
    at Function.onload (eval at E_c (:3:221), <anonymous>:5584:21)
    at <anonymous>:2:398
    at eval (eval at exec_fn (:1:108), <anonymous>:31:494)
```

**Comment by revilheart** [comment]
Did you set up an alt account? And a Steam API Key?

**Comment by gizellos** [comment]
Yes, I did and I tried to the the sync after it. Also the categories stuff for the all account is not displayed correctly.

![2017-08-26_222006](https://user-images.githubusercontent.com/2397851/29744808-d9176b74-8aac-11e7-957e-ddcc76876e90.png)

**Comment by revilheart** [comment]
Did you fill all the fields correctly?

**Comment by gizellos** [comment]
I just filled the key and the nickname. I suppose the key is also the Steam API Key, right?

![2017-08-26_222527](https://user-images.githubusercontent.com/2397851/29744855-9dd711e4-8aad-11e7-81ca-e95da7f4b684.png)

**Comment by revilheart** [comment]
The first field is Steam ID, not API Key, API  Key is to be put in the last section of the settings menu. Steam ID is the one that comes after "/profiles/". You have to fill icon, label, color and background.

**Comment by gizellos** [comment]
Works well, thanks.
