### ISSUE TITLE
Editable giveaways in Multiple giveaways creator

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#381]
It would be nice if I could click to a giveaway indicator and it would fill all the fields in the page so that I could edit the giveaway.

I mean the stuff in the attached image.
![2017-08-26_224448](https://user-images.githubusercontent.com/2397851/29744977-88d2b9b2-8ab0-11e7-9049-9f543295dd78.png)

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
That was pretty fast. Thanks.
