### ISSUE TITLE
Exclude ended giveaways from sorting in entered giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#382]
I think ended giveaways should be excluded from the results of sorting entered giveaways. I just used sorting by chance and there were even giveaways that already ended. 

![2017-08-27_205008](https://user-images.githubusercontent.com/2397851/29753050-8c37316e-8b69-11e7-9bfa-35408f2b67ec.png)

**Comment by revilheart** [comment]
Would be too complex. If one doesn't want to see ended giveaways they can just use the filters.
