### ISSUE TITLE
Scroll to Top breaks the toolbar

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#383]
If I scroll down and then to click on the button Scroll to Top, the toolbar will break.  No errors in console. It's because of the bigger navigation I think.

![2017-08-28_155110](https://user-images.githubusercontent.com/2397851/29776378-ba82f130-8c08-11e7-89d7-640a30ae9f2b.png)

**Comment by gizellos** [comment]
Also it shouldn't show page 11 but page 1 or 2.

**Comment by revilheart** [comment]
Nothing I can do about it, as far as I know, it's because there isn't room to show everything. Are you at the end of the page? Because if you are then it's normal to show page 11.

**Comment by gizellos** [comment]
> Nothing I can do about it, as far as I know, it's because there isn't room to show everything.

I disabled the multitag functions so no problem for me but poor people who want to use them. You could divide the row of buttons to two rows of the buttons in cases there is no room for them.

> Are you at the end of the page? Because if you are then it's normal to show page 11.

It's not normal. I am at the beginning of the page.  I am on page 1 and  it has to show page 1. It shows the number of loaded pages instead of the current page. 

It was like that before and it works like that with disabled filters even now. So it seems the filtering confuse it somehow.

Also I just noticed that the filters break the removing of the page separators with page numbers. The separators are removed only when the filters are disabled.

**Comment by revilheart** [comment]
If the beginning of the page is the end of the page, it is normal. Can you scroll? Are there errors in the console?

What do you mean by "removing of the page separators"?

**Comment by gizellos** [comment]
With the page separators I meant page divisors. They are removed only when filters are off.

I don't understand why you don't understand. It is easily visible in the screenshot in OP. So check these two screenshots.

One is normal behavior and the other is the bugged behavior. There are no errors in console and I can scroll. The problem is that the pagination doesn't update when I scroll up.

If you still think that it is normal behavior, then tell me what is the pagination for. Even clicking on the bugged pagination doesn't do anything.

![2017-08-29_145935](https://user-images.githubusercontent.com/2397851/29822424-b0fa8c90-8ccb-11e7-88fc-d0c69e0ea63a.png)
![2017-08-29_145954](https://user-images.githubusercontent.com/2397851/29822428-b57da216-8ccb-11e7-8ff8-7d03328e66b7.png)

**Comment by revilheart** [comment]
I still don't understand what you mean by "They are removed only when filters are off.". Separators are never removed.

Ah, so you can scroll, you didn't answer that question, so that's why I thought it was normal, I'll look into it.

**Comment by gizellos** [comment]
When I took the screenshot in OP, I already had the version with this news "The pages are no longer divided - it's now truly endless." and the problem was that the pages still were divided as you can see in the OP. When the filters were enabled, the pages were divided. When the filters were disabled, the pages were not divided. 

But it seems to work correctly in the latest version.

**Comment by gizellos** [comment]
Now I have errors in console while I am scrolling down.

```
Uncaught TypeError: Cannot read property 'offsetTop' of null
    at HTMLDocument.changePaginationNavigation (eval at E_c (:3:221), <anonymous>:31868:134)
```
