### ISSUE TITLE
Settings of ALT account - break the line after text input "using the nickname"

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#384]
The line of settings of ALT account is too wide and because of it the whole settings is too wide. Could you break the line after the text input "using the nickname"?

Also the color fields are too wide. They could be just 1/3 or 1/2. It would help the width of the settings too.

![2017-08-28_155522](https://user-images.githubusercontent.com/2397851/29776712-d15d913e-8c09-11e7-9bc4-81728b47782d.png)

**Comment by revilheart** [comment]
Done
