### ISSUE TITLE
Syncing stuck in "wishlisted/owned/ignored games"

### ISSUE THREAD

**Issue by StraussVanDor** [revilheart/ESGST#385]
Syncing (`/esgst/sync`) gets stuck at message _Syncing your wishlisted/owned/ignored games..._
Console shows:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at continueSyncStep4 (eval at E_c (:3:221), <anonymous>:5158:83)
    at saveHiddenGames (eval at E_c (:3:221), <anonymous>:5152:9)
    at <anonymous>:2:398
    at e.string.k.function.c.(anonymous function) (eval at exec_fn (:1:108), <anonymous>:54:352)
```

**Comment by revilheart** [comment]
Check the console for errors.

**Comment by StraussVanDor** [comment]
Hi! What I included in my original post is the only error related to the plugin.
Console also shows this, but I guess is normal:
`GET https://www.steamgifts.com/esgst/sync 404 (Not Found)`

**Comment by revilheart** [comment]
Ah, my bad, I didn't notice that you had posted the error. People often forget to do that when reporting bugs, so I've gotten in the habit of asking if they have checked the console. :P

I found the issue, will be fixed in the next version.

**Comment by revilheart** [comment]
Fixed
