### ISSUE TITLE
The estimated level after finishing all GAs was not correct

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#386]
I had level 8.01 and I made quite a long [train.](https://www.steamgifts.com/discussion/dIA6I/) The script told me that I will have level 8.02 after all the giveaways ends. They ended and I had level 8.05. It's quite a big difference. I don't know if some values of games changed but I doubt that they would raise and so much.

It's possible that it counts wrongly. It's hard to check all the GAs and to find out if the values changed or some bundled games changed to unbundled (which is not very probable).

**Comment by revilheart** [comment]
Hmm, hard to test this.

**Comment by gizellos** [comment]
Yeah, maybe you could write a post to your SG thread and ask if there are some willing people with low level to test it. Just to make a few giveaways. Some could be bundled and some free.

**Comment by gizellos** [comment]
I was the same situation a short while ago and I noticed that the incorrect number was fixed after the giveaways ended and I sent the keys (I didn't calculate it, though).

**Comment by gizellos** [comment]
I am closing this for now.
