### ISSUE TITLE
Refreshing from header not working

### ISSUE THREAD

**Issue by kostek00** [revilheart/ESGST#387]
"Refresh all pages" isn't refreshing anything in whishlist ga (don't know if anywhere else also). I need to refresh whole page.

And "refresh current page" takes so long that I don't if it's working (waited like 10 minutes and it still was going).

I'm using Firefox with tempermokney. It stopped working since you added second refresh icon.

**Comment by revilheart** [comment]
Are there errors in the console (Ctrl + Shift + J)?

**Comment by revilheart** [comment]
Check if it still happens in the latest version, I found nothing wrong in the code, and without errors in the console, I have no idea what could be happening.

**Comment by kostek00** [comment]
Still not working :/

**Comment by revilheart** [comment]
Are you using Firefox Containers? The script doesn't work 100% with that.

**Comment by kostek00** [comment]
I don't.

**Comment by revilheart** [comment]
I'll see if I can find some time today or tomorrow to use Firefox and test it myself so I can try to reproduce it.

**Comment by revilheart** [comment]
Just tested on Firefox, and there is actually an error in the console (you probably weren't able to see it because it has to be in the Ctrl + Shift + J console, not the Ctrl + Shift + I one. And I believe errors only appear if the console is open while you try to refresh, not if you open it afterwards. Working on it...

**Comment by revilheart** [comment]
Should be fixed.

**Comment by kostek00** [comment]
So that's why I didn't see error.

Yes it's working now. Thank you.
