### ISSUE TITLE
Option to open Steam page for activating CD-KEY instead of opening steam client

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#388]
It's great new that Steam finally made a [page](https://store.steampowered.com/account/registerkey) where people can activate their games. Maybe someone would prefer to use the website instead of the client. So I suggest to add a toggle to settings if people want to use Client or Steam Page for registering their games.

![2017-08-30_154625](https://user-images.githubusercontent.com/2397851/29875521-98b14578-8d9a-11e7-96a0-933b78bc6e0e.png)

**Comment by gizellos** [comment]
Allegedly, this works: https://store.steampowered.com/account/registerkey?key=AAAAA-BBBBB-CCCCC-DDDDD-EEEEE So the button could directly activate the game.

**Comment by revilheart** [comment]
Done

**Comment by ldeman** [comment]
just fyi, the old style activation window never did load in a linux build, so it's unlikely that the new style will work either.   all it would do prior was bring the steam client to focus, not actually bring the activation window up.

hardly any steam:// urls work properly inside linux.

**Comment by gizellos** [comment]
I also have a problem with the steam activation. It works but it takes several tens of seconds to open the steam client. If I use a similar function in another page with  another script (indiegala helper), it starts to open the steam immediately.

**Comment by revilheart** [comment]
@ldeman The new style is through browser though, so I don't see how that affects anything.

**Comment by revilheart** [comment]
@gizellos Nothing I can do about that, as far as I know.

**Comment by ldeman** [comment]
oh okay.  i assumed that http:// url just redirected to a steam:// url with the key pre-inserted, but i guess it's a totally different setup instead.

**Comment by revilheart** [comment]
@ldeman Nope, it allows you activate games through the browser. ^^ Do you happen to know how to fix the old one to make it work on Linux? Or is it a bug in Steam itself?

**Comment by ldeman** [comment]
i'm pretty sure it's a bug in the steam client linux version tbh.  upon the first time load it asks what to do with the mime type, and an xdm option is the default choice, which does properly load the steam client up out of minimized to system tray.   it just didn't load the actual activation window.   i'm pretty sure the same can be said for the steam://connect/65.25.23.1  (server connect) as well.  the linux version just doesn't know how to handle it properly.

**Comment by ldeman** [comment]
maybe its the mime setup, but i have no idea how to alter it.

inside /usr/share/applications/mimeinfo.cache

`x-scheme-handler/steam=steam.desktop;`

**Comment by ldeman** [comment]
the new browser option does indeed work fine with linux as well.  would it by chance be too much of a pain to add a disable client activation button since it doesn't work for linux, but still leave the browser activation link?

if not, it's no big deal.  the icons are clear enough anyways.  thanks for the new option btw!  =)

**Comment by revilheart** [comment]
Sure, I'll add an option to the settings menu later.

**Comment by revilheart** [comment]
@ldeman And yeah, I don't really understand any of that. :P I tried Linux once, but the incompatibility with stuff made me go back to Windows right away.

**Comment by ldeman** [comment]
sounds great, thanks.  ^^
hehe, np.. i understand what you mean.  i only understood it just barely enough to say it, and i even had the acronyms wrong at first.  all i really know about it, is that it doesn't work correctly "out of the box" for linux, which leads me to believe they just didn't complete that portion of the linux client.  valve seems to only concentrate on steamcmd for linux rather than the client.
