### ISSUE TITLE
Add Points Fulfillment Visualizer

### ISSUE THREAD

**Issue by StraussVanDor** [revilheart/ESGST#389]
Similar to how _Level Progress Visualizer_ works, I think it would be cool to have the progress bar fill according to how many points you have available. Sort of a battery power indicator. It will be completely full when you have 300 points. Of course, It could not be used at the same time as _Level Progress Visualizer_.

**Comment by revilheart** [comment]
Sorry, it's a cool idea, but the script is designed in a way that no features are mutually exclusive. And I don't see a place to put another bar that would look cool.
