### ISSUE TITLE
SG related game info popout

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#39]
I would love if rhSGST could show me some (mainly) SG related info about games from links. Script would look for links leading to games on steam and if it found some, it would put a icon (maybe there is a better way) beside the link. If a user clicked the icon, the script would show the info.

The info could be:
- How many giveaways of this game I have made so far (that's my main reason for it)
- How many CV I would get for 1 copy (it would count with the previous data)
- How many points the GA  is worth
- If it is bundled
- If I own the game (or if also my alts own it)
- If it is my wishlisted game

There could be also some stuff which is not related to SG, but it is not so important. It could be if it has cards, achievements, multiplayer, which tags does it have, price, best deal according to isthereadeal, and so on.

The important thing is that it would support all links to steam games - no matter if they are in a plain text in the forum, in (rachart) tables or in giveaway lists. 

I would rather to have it without the icon, because they icon would change the flow of text. Maybe to activate it by just hovering the links. The affected links could be a little different (for example a little different color). But it is also not ideal.

**Comment by revilheart** [comment]
That's quite a complex feature, so it might not come soon, but I'll consider it.

**Comment by revilheart** [comment]
Now that there is a Game Categories feature, this doesn't sound so complex anymore. I could easily expand the feature to work with discussion tables like RaChart, but adding the info to any link in the page would be quite ugly, as it would completely break posts.

**Comment by gizellos** [comment]
Yes, please make RaChart tables better . I suggested some useful things to Sighery but he didn't want to implement them. For example, to show if I wishlisted the game (yes I know some other scripted implement it  in their fork), to show how many copies of the game I gifted here or if the game is free on SG and support for alt accounts. 

You could also add an option to hid there the row "bundled" that says how many times it has been bundled, because it looks quite meaningless to me and there could be some more useful info instead of it. 

I believe there is quite a big potential in enhancing the tables. :)

**Comment by revilheart** [comment]
Not sure about alt accounts, though. I don't think the script is prepared to deal with that.

**Comment by gizellos** [comment]
Maybe it will be one day. I believe in you. :)

BTW: another enhancements could be better stats for bundles. I would like to see there, for example, CV/Value per 1 dollar/euro. It would tell us how convenient the bundle is for CV farming.  Also somebody may like to see price in their currency.

**Comment by revilheart** [comment]
So is alt account support the only thing missing from this issue?

Isn't the bundle CV something that the people who post them already include in the post? I don't like the idea of showing currency based on region, and I don't even know how I would do that, to be honest.

It would be better if you opened a new issue with your RaChart suggestions, this issue is starting to become too polluted with too many different suggestions.

**Comment by gizellos** [comment]
Yes, just the alt account support. I am closing this and I am going to make a special issue about the alt account in the tables.
