### ISSUE TITLE
Page navigation is not updating when I scroll up

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#390]
I already talked about this issue [here.](https://github.com/revilheart/ESGST/issues/383)

If I have GA filters enabled and I want to scroll up, the page navigation doesn't change. There is still the same number.

There is a suspicious error in the console:
`
Uncaught TypeError: Cannot read property 'offsetTop' of null
    at HTMLDocument.changePaginationNavigation (eval at E_c (:3:221), <anonymous>:31884:134)
`

![2017-08-29_145935](https://user-images.githubusercontent.com/2397851/29822424-b0fa8c90-8ccb-11e7-88fc-d0c69e0ea63a.png)
![2017-08-29_145954](https://user-images.githubusercontent.com/2397851/29822428-b57da216-8ccb-11e7-8ff8-7d03328e66b7.png)

**Comment by revilheart** [comment]
Should be fixed.
