### ISSUE TITLE
Table sorter works only on page 1 when I use endless scrolling

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#391]
Table sorter works only on page 1 when I use endless scrolling.

For example. If I sort whitelisted users by Last Online, it will only sort page 1 and the other pages are not sorted.  There is not even an possibility to sort the other pages manually, because the sorting links are only on the page 1 (which is normal).

I would be glad if the sorting automatically applied also to the new loaded pages through endless scrolling.

**Comment by revilheart** [comment]
Works fine for me. Can you try again in the latest version?

**Comment by gizellos** [comment]
It seems to work now, thanks.  :)

I just have quite a problem with the sorting arrows. I would rather see which sorting direction is currently applied and not which direction would be used if I clicked on it again. Could you please add it as an option to the settings?

I also suggest to hide all the empty pages after scrolling to the other pages. It would be better without them.

![2017-08-31_194559](https://user-images.githubusercontent.com/2397851/29937564-4941b1fc-8e86-11e7-9aba-925c4ada3b0a.png)

**Comment by revilheart** [comment]
That currently cannot be removed, as the page divisors are only visual. Only solution is to disable page divisors.

**Comment by gizellos** [comment]
Display: none should remove it without problems.

Please reopen this issue because the original issue happens again.

**Comment by revilheart** [comment]
I know, it just wasn't my priority at the moment, which is why I said "currently", especially when it's not a serious thing, so it can wait.

I cannot reopen the issue because I cannot reproduce it, can you please give me more details about what's happening? When you click on the button to sort the table nothing happens to the contents from page 2+?

**Comment by gizellos** [comment]
I made a gif, you can see it there. The results on page 2 are sorted correctly but on page 3+ they are not sorted at all.

![sorting whitelist](https://user-images.githubusercontent.com/2397851/30000699-c0a2a7c4-9075-11e7-9ccd-ba8922134a5c.gif)

**Comment by gizellos** [comment]
Or another longer gif. You can see here what happen if I scroll to top. There are not the page divisors but after I click to the sorting button again, they will appear.

![sorting whitelist 02](https://user-images.githubusercontent.com/2397851/30000817-4799b936-9079-11e7-8102-b61dfc1d645e.gif)

**Comment by revilheart** [comment]
It should now automatically sort the next pages.
