### ISSUE TITLE
New encrypted giveaways option - show them only for bumpers

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#392]
I would like to motivate people to bump my threads and nothing motivates more than giveaways, for sure. I have been thinking about it for a long time and I finally got an idea  how to do it.

1. The creator would put similar code like for classic encrypted giveaways to the page
2.   By default, people would see the giveaways in the list of encrypted giveaways in a way that the names of the games would not be visible and enter button or link would not be visible and instead of it, there would be written something like "Bumpers only".
3. If anyone posted anything to the topic, the names of giveaways, together with the enter button or link would appear in the list of decrypted giveaways.

**Comment by revilheart** [comment]
Too complex. Besides, anyone can look at the source code of the page and decode the giveaway link.
