### ISSUE TITLE
Filter group giveaways

### ISSUE THREAD

**Issue by GOBsNotOnBoard** [revilheart/ESGST#394]
Most of the groups I'm in have a ton of members, so the odds of winning a giveaway for one of those groups are always terrible. I would love it if I could filter out those groups and just see the giveaways from the smaller groups I'm in on the groups page.

**Comment by gizellos** [comment]
Yes, it would be good. Just to have a filter of excluded groups.

As a partial workaround you can use filters and set there the maximum entries per giveaway. I myself left all the big groups such as SG or Indiegala (you don't have to be in the IG group for their masive giveaways anymore).

**Comment by revilheart** [comment]
Would be too complex and slow, because the script would need to request those giveaways to find out their groups. Much better for you to play around with the chance/entries filters. That way you can make sure you only see giveaways with great chances of winning.
