### ISSUE TITLE
Train extractor ignores the first vagon if I start to extract it inside the vagon

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#397]
I am not sure if it is on purpose or not but I think it should not ignore it.

**Comment by revilheart** [comment]
Doesn't make sense to extract a wagon that you're already inside of.

**Comment by gizellos** [comment]
I think it has sense because I don't look at the first vagon when I want to extract all the train and apply some filters to it. It's easier to apply filters to all vagons once than to think about the first vagon and then to extract it and apply the filters.

**Comment by gizellos** [comment]
> if you don't look at the first wagon why not extract from the discussion page?

I didn't realized it until I made this issue. I will do it. Just it is not possible from SGTools so the small change will help, anyway. Thanks.
