### ISSUE TITLE
Confirmation window when clicking on the link for deleting a key

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#399]
It is quite a trap that if one clicks on the link delete, it will delete the key without a confirmation. I clicked on it by accident and I couldn't get it back.

Could you please add there a confirmation window?

![2017-09-04_162744](https://user-images.githubusercontent.com/2397851/30030719-e4af021a-918e-11e7-8fb1-fdf3d612157c.png)

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Thanks.
