### ISSUE TITLE
when i extracting train, have some error

### ISSUE THREAD

**Issue by youmeiro** [revilheart/ESGST#407]
![q1](https://user-images.githubusercontent.com/31191446/30189576-c7f28b86-946f-11e7-86ba-9ce9582cec5f.png)

https://www.steamgifts.com/discussion/dXLOv/old-keys-train-level-5

when i try to extract train,  some train returned error
just only first and second giveaway appeared again again ( to 50 extract )
in case, console doesn't output any error

**Comment by revilheart** [comment]
Fixed
