### ISSUE TITLE
Create giveaway button is not working

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#408]
I wanted  to create a giveaway using  the Create Giveaway button and it didn't create the giveaway. There is an error in console even after just reloading the Create Giveaway page. 

ERROR: Execution of script 'ESGST' failed! Cannot read property 'firstElementChild' of undefined
(anonymous) @ VM1690:3
(anonymous) @ VM1690:4
(anonymous) @ VM1690:38623
(anonymous) @ VM1617:2
E_c @ VM1617:3
E @ VM1687:60
create @ VM1687:69
e @ VM1687:17
setTimeout (async)
(anonymous) @ VM1617:2
c.safeWindow.(anonymous function) @ VM1617:8
(anonymous) @ VM1687:17
runListeners @ VM1687:17
la @ VM1687:17
run @ VM1687:18
(anonymous) @ VM1687:70
(anonymous) @ VM1617:2
b @ VM1617:2
(anonymous) @ VM1687:70
(anonymous) @ VM1687:70
TM_back @ VM1687:71
(anonymous) @ VM1687:71
(anonymous) @ VM1617:2
exec_fn @ VM1617:1
(anonymous) @ VM1617:11
aa @ VM1617:9
e @ content.js:6
send @ content.js:8
next @ content.js:13
(anonymous) @ content.js:26
(anonymous) @ content.js:24
sendResponseAndClearCallback @ VM1613 extensions::messaging:417
messageListener @ VM1613 extensions::messaging:449
EventImpl.dispatchToListener @ VM1606 extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ VM1612 extensions::utils:140
EventImpl.dispatch_ @ VM1606 extensions::event_bindings:387
EventImpl.dispatch @ VM1606 extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ VM1612 extensions::utils:140
dispatchOnMessage @ VM1613 extensions::messaging:390
VM1690:3 TypeError: Cannot read property 'firstElementChild' of undefined
    at setSggGiveawayGroups (eval at E_c (:3:221), <anonymous>:12578:31)
    at Array.loadSgg (eval at E_c (:3:221), <anonymous>:12567:13)
    at loadFeatures (eval at E_c (:3:221), <anonymous>:5053:31)
    at loadEsgst (eval at E_c (:3:221), <anonymous>:4172:25)
    at eval (eval at E_c (:3:221), <anonymous>:449:5)
    at Window.tms_eafecfdb_d33e_4713_8f83_75a77d76d21c (eval at E_c (:3:221), <anonymous>:38622:3)
    at <anonymous>:2:398
    at eval (eval at E_c (:3:221), <anonymous>:3:1)
    at eval (eval at E_c (:3:221), <anonymous>:4:3)
    at Object.eval (eval at E_c (:3:221), <anonymous>:38623:6)

**Comment by gizellos** [comment]
Maybe the error is related to [this news.](https://www.steamgifts.com/discussion/0X36E/country-restrictions)

**Comment by revilheart** [comment]
Should be fixed.
