### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by to-dr** [revilheart/ESGST#44]
Again, not sure if possible:
sorting columns after searching (like I searched Robot Rollerdery disco dodgeball - entered, and as I have 100, I would like to sort either number of entrance or probability of winning chance :P

**Comment by ldeman** [comment]
per page short is. idk about global sort though.

**Comment by ldeman** [comment]
i think what they want is to be able to sort the entire giveaway list by best odds of winning.   which really could only be done on a "per page" basis.   and imo would not actually give them what they really want since it would end up just being a mixture of reverse ending combined with newest to oldest creation with the exception of group GAs being towards the top.

i think the better solution would be filtering in general to filter out the low odds GA's leaving only the good odd ones visible.   filter>sorter

**Comment by gizellos** [comment]
Once I saw a userscript and it used a very complicate algorithm for calculating the odds (it counted also with the age of GAs). I haven't tried the script but I suppose that the results would be more usable in the sorting by odds since it would not put the newest one to the top.

**Comment by ldeman** [comment]
![image](https://cloud.githubusercontent.com/assets/10275898/23666223/0d1412a2-0320-11e7-87bb-4629ceddf7dc.png)

**Comment by gizellos** [comment]
Yes, that's, in fact, what I insinuated...

**Comment by revilheart** [comment]
I don't really see the point of sorting by chance, it's all relative anyway: you might have a great chance to win a giveaway right now, but later more people enter and your chance drops. You could just use Advanced Giveaway Search to limit the number of entries of the giveaway.

**Comment by to-dr** [comment]
umm I don;t need acvtive GA's sorting :) ended are enough
![image](https://cloud.githubusercontent.com/assets/25917318/23682745/b33133aa-03d8-11e7-9748-6e2a5e3b7286.png)

**Comment by revilheart** [comment]
Oh you mean in the Entered page. That's much easier then. I thought you wanted it in giveaways pages.

**Comment by to-dr** [comment]
yeah, sorry, wrote in not the clearest way ever, sorry for that  lol :) (but I mentioned entered in op)
kinda ranting purposes mostly of that enhancement, so low priority for that :P

**Comment by revilheart** [comment]
Added, hope it's the way you wanted.

**Comment by to-dr** [comment]
nice! thanks! 
just one note: with endless scrolling it sorts every page separately :) not sure if intended

**Comment by revilheart** [comment]
Intended, there's no way to sort everything together because endless scrolling handles each page separately.
