### ISSUE TITLE
[Enhancement] Sorting list of whitelists

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#46]
Could you please add sorting to [the list of whitelists?](https://www.steamgifts.com/account/manage/whitelist) I would love to have the possibility to sort it by date added.

**Comment by gizellos** [comment]
(I suppose it would be good also for blacklists but I don't care about it according to the fact I don't blacklist anyone.)

**Comment by ldeman** [comment]
again here too, i think it would have to be per page sort.

i don't think revil can take a user from page 2, and make them appear on page 1 because they were added before the people on page 1.  however this one sounds great still if you keep that in mind. ^^

**Comment by gizellos** [comment]
You are right, then the all pages would have to be all generated by the script. So the script would load all the data, hide the original list and replace it with its own list.

**Comment by revilheart** [comment]
I don't really like that (the script loading all pages and then presenting them). If I do this, it will be on a page by page basis. Or if you are happy with just a list of items containing "Username - Date" information being popped up, I can get that information from sync.

**Comment by gizellos** [comment]
All I need is to have the whitelist sorted by date added instead of user name. I don't know if there is an elegant way how to do it. If there is not, no problem.

**Comment by ldeman** [comment]
ahh yeah, that would work.  a sorted list off the data it's already collected anyways. ^^

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Cool, thanks.
