### ISSUE TITLE
[Enhancement] Show confirmation window after click on not received

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#48]
As we can [read here,](https://www.steamgifts.com/discussion/PGlwk/accidentaly-removing-feedback-maybe-a-confirmation-to-be-made) it is not so hard to accidentaly click on "not received" feedback and it cannot be change to received (before the thread I thought it was possible). 

Could you show as a confirmation window if we click on "not received" link?

**Comment by revilheart** [comment]
Umm what? I can change my feedbacks from received to not received and vice-versa any time I want. Or at least I could, did cg change something?

**Comment by revilheart** [comment]
Oh wait, I actually just unmarked received and marked it again. Will check this out.

**Comment by gizellos** [comment]
I don't know, I haven't tried it but the people in the topic seems to have this problem. I haven't read the topic all.

**Comment by revilheart** [comment]
I don't think this is true, you can change feedback of a giveaway any time you want. I think what the OP wanted was just a confirmation dialog when doing so, and I don't see the point of this, as you can change it, so if you made a mistake you can simply go there and fix it.
