### ISSUE TITLE
[Bug] Endless scrolling doesn't work if page 1 has all stuff hidden

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#50]
I think it influences all giveaway lists but I found it in _whitelist giveaway_so I will use it in the description. Quite hard to explain but I will try my best.

If one uses **hiding entered giveaways** feature and the only available GA in their whitelist is on page higher than 1, the page the page [wishlist giveaway](https://www.steamgifts.com/giveaways/search?type=wishlist) will show **empty page** and I cannot scroll to the page 2. So it looks as if there was no available GA. Scrolling doesn't do anything.

So there are two problems:
1.  It should show empty first page and below it page 2 with the GA. (maybe it doesn't show because the height of all sg page is too short with all the GAs hidden).
2. Even if the page 2 is not shown, one should be able to scroll the base page to page 2, anyway.

I also have a suggestion. If the script hides all content on a page, it should write something like "No new giveaways" to the place where was the content. Now it doesn't show anything and it is quite confusing.

![endless scrolling bug](https://cloud.githubusercontent.com/assets/2397851/23754344/e924f2b2-04dc-11e7-8292-d6b55ae1b88f.png)

**Comment by revilheart** [comment]
Yeah, someone reported this on the thread a while ago, but since bug reports are hard to keep track of on the thread, I forgot about it. The next page is only activated during scroll, and since the page is too short, you can't scroll, which causes the next page not to load. I'll fix it in the next version.

**Comment by gizellos** [comment]
I see, thanks in advance.

**Comment by revilheart** [comment]
Fixed
