### ISSUE TITLE
[Feature request] Hiding all user's posts/threads/GAs

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#51]
I believe many users would appreciate to have an possibility to block posts, threads or GAs of some other users (for example shit posters). 

This feature could be made in two ways.

1.  Simple one: There would be one button on user's profile and you it would marked the user as ignored.
Then there would be some settings in my settings:

- Ignore all posts
- Ignore all threads
- Ignore all giveaways
- apply also to blacklisted users

2. better one: There would be also the button on user's profile, but the settings would be also on user's profile (except the one about blacklisted users) so you could set what you want to each user.

**Comment by revilheart** [comment]
Doesn't Sighery have a script for that?

**Comment by gizellos** [comment]
There is a script but it hides only posts and it is really long time ago when someone asked him to also hide threads.

**Comment by gizellos** [comment]
LOL, just one hours ago Sighery posted [a new version of that script](https://www.steamgifts.com/discussion/WrWU3/userscript-sgignore-wip-hides-comments-giveaways-discussions) after hundred years. What a coincidence. :D

But the script doesn't do it in a way I mean so it doesn't matter.

I want the script completely hide the posts - it means whole posts even with replies to it, not just "censor" the content as in his script. I want it to work like on facebook.

**Comment by revilheart** [comment]
Added
