### ISSUE TITLE
[Enhancement] Sizes of elements and placement in GA templates

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#52]
Hi, 
I have few suggestions for the GA templates feature:
- the list of templates is too tiny. I believe it should be a bit bigger. I just made 40+ GAs from templates and it was not too enjoyable even if I have a (good) mouse. Users with laptops without mouse could have quite problems to use it since the button for choosing the template is so tiny and just few pixels further is the delete button.
-  the placement of the delete template button is very "dangerous". It is too easy to click on it and accidentally delete the template. A confirmation button would be useful.
- It would be better if the names of the templates were links. Links are much more visible and accessible even from the laptops. You could remove the button that applies the templates. I kinda expected the links were clickable, anyway.
- on the contrary, the input for the name of a new template is too wide. It is not such a big problem, but it is not very standard and it would looks better if it was smaller. You can ignore this suggestion, though. (I enclosed a comparison picture, it's quite funny when you see it like that when you realize that you use the big input window just once and you use the tiny window with list very often.)
- could you put the "Review giveaway" button somewhere to the top of the page? One would not have to scroll so much every time they need to confirm it.
- I would like to have the possibility create the templated giveaways without the preview window. Is possible to skip it somehow?
- I would like to see the settings of the templates when I hover them (or a new button).
- Edit button for templates would be good too.

![template features comparison](https://cloud.githubusercontent.com/assets/2397851/23801791/adf59a7c-05b1-11e7-990a-03e98c3f51b2.png)

**Comment by revilheart** [comment]
* The popup size is because I made it 75% of the user's screen size, because some people were complaining g about how small it was for the checkers, but I guess popups with an input area don't need to be that wide. Will see what I can do.
* I don't like the idea of moving the review button. Maybe only after someone applies a template. I'll think about it.
* What preview window?
* You can currently edit templates by applying them, making your changes and saving it with the same name.

**Comment by gizellos** [comment]
> I don't like the idea of moving the review button. Maybe only after someone applies a template. I'll think about it.

Yes, it would be good only hide it after applying the template, you are right. Without templates it needs to be at the bottom, I didn't realize it.

> What preview window?
Maybe it is called just review window, sorry. When you fill all fields on the GA creation page, you have to click on the "Review Giveaway" button and it will take you to the (p)review window, where you have to confirm it. 

The preview window is a good thing because you can check what you chose for the giveaway. But it is one step more than it is necessary. Sometimes I would rather the page created the GA without the preview window. For example, when I use the templates and I know they work, it is the time I don't need.

On the main GA creation page, there could be just another button and it would directly create the GA - without the review window.

**Comment by gizellos** [comment]
This is what I called a preview page.

![2017-03-11_084608](https://cloud.githubusercontent.com/assets/2397851/23821649/94b8f8aa-0639-11e7-9266-79d48db7d519.png)

**Comment by revilheart** [comment]
I believe Beta.10.3 suits all your needs, but let me know if not.

**Comment by ldeman** [comment]
tiny typo:  "rveryone"
![image](https://user-images.githubusercontent.com/10275898/27363569-f42e928e-55fa-11e7-8395-12b9a78f23b4.png)

love the revamp though, thanks!  =)
