### ISSUE TITLE
Fetching wrong list wl/bl checker

### ISSUE THREAD

**Issue by to-dr** [revilheart/ESGST#57]
Hya,

again, not sure if bug or I am misunderstanding the tool : 
![image](https://cloud.githubusercontent.com/assets/25917318/23844104/7df31666-0803-11e7-97fd-2deb6a1d362d.png)
Wrong list of users?

**Comment by ldeman** [comment]
it probably ran across a name-change.  if someone changes their name while/before/as you are starting the list scan (unsure when), it will default the scanner to scan all GA creators because it loops it back over to /giveaways.

**Comment by revilheart** [comment]
@ldeman It seems to be stuck on retrieving users though, and that part doesn't care about username changes, it just goes through the pages getting the users. So this is very odd.

@to-dr Does it happen in other pages or only on this one? And did you load a page with endless scrolling before enabling the check?

**Comment by to-dr** [comment]
removing # from url works :)

**Comment by revilheart** [comment]
Fixed
