### ISSUE TITLE
[Enhancement] When I use  Blacklist/Whitelist return, the script could save a note to permanent notes

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#59]
When I check a place for users who whitelisted/blacklisted me and I mark the "Return whitelists." or "Return blacklist.", the script could save a permanent note for the users. I mean something like "Whitelist return", "Automatic whitelist counter", or something like that.

It would be quite handy when someone ask us why we WLed/BLed them. 

This feature would be optional of course.

**Comment by revilheart** [comment]
Finally added this.
