### ISSUE TITLE
[Enhancement] Automatic Game Tags

### ISSUE THREAD

**Issue by Mieekaserra** [revilheart/ESGST#60]
As requested on the forum post, the ability for game tags to automatically generate based on the Games Genre or Popular user defined tags.

**Comment by gizellos** [comment]
There is a script that does it but the script disconnect me from steam, so if you are going to implement it, Revil, be cautious.

I would love to have the possibility to filter GAs with the tags. It would be best feature ever. <3

**Comment by ldeman** [comment]
@gizellos don't forget about daerpens version of it tho.  that one isn't as good looking as alpes, but doesn't cause issues.
https://github.com/Daerphen/sgscripts/raw/master/sgtags.user.js

**Comment by gizellos** [comment]
@ldeman But it does a different thing. I use it too, but it shows just if a game is bundled, has cards, achievements, and so on. OP means showing tags such as RPG, Adventure, Puzzle, and so on.

**Comment by ldeman** [comment]
@gizellos the one i linked does just this.  you're thinking of ruphines tags instead.  xD
![image](https://cloud.githubusercontent.com/assets/10275898/23952283/01dc2d94-095f-11e7-882e-a8f60931f058.png)

**Comment by gizellos** [comment]
Aww, sorry I mistook it. I use both. But I would rather to see the tags directly in the GA lists like in the bugged script that disconnects. This is good just for trains.

The idea with the filtering is that I, for example, play mostly just RPG games, so I would set the filter to show me only games that contains RPG tag.

What is the problem with the original version of the SG Augmented Gamelist? It works normally for me.

**Comment by gizellos** [comment]
But I would rather to see something better than steam tags since the tags are not very good. Some alternative source...

**Comment by ldeman** [comment]
honestly i have no idea why the change or if there was something wrong with it.  i haven't used it in a very long time, but i thought it was more like a popout style last time i used it.

i preferred alpes version of it except that dumb logout of steam problem that constantly occurred.  i used daerphens augmented one for a while after that but then just quit using both of them entirely.

**Comment by revilheart** [comment]
Closing this because of the new Game Categories feature, although there is no current support for user defined tags and I'm not sure if there will be.
