### ISSUE TITLE
Support ticet sorting

### ISSUE THREAD

**Issue by to-dr** [revilheart/ESGST#61]
Support tickets are sorted by creation date. While for active that is fine, but when resolved they jump down and still sorted by creation date. Would be fine, if they would be resolved by creation dates, but they are not, hard to track. Is it possible to sort them on resolve/close date? (Fading of visited is working there, but, umm not fully solves the issue. so maybe additional mark/highlight for new resolved until visited)

**Comment by to-dr** [comment]
oh, and ticket counter maybe ? :P

**Comment by to-dr** [comment]
counter is already there, dummy me lol

**Comment by revilheart** [comment]
That is not possible, as the resolved date is not visible from the tickets page. Don't you get a message when a ticket is resolved? Can't you track resolved tickets with that?
