### ISSUE TITLE
[Bug] Stickied icon of a new group doesn't appear in group list

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#66]
I entered a new group, stickied it in Create giveaway page, made some giveaways for it, then enter the [Group list](https://www.steamgifts.com/account/steam/groups) and found the stickied icon doesn't appear for this group.

![2017-03-15_211405](https://cloud.githubusercontent.com/assets/2397851/23968854/c11fb670-09c4-11e7-9edc-8eac81194238.png)

**Comment by ldeman** [comment]
resync wl/bl/groups data, it relies on that sync for that page.  i almost reported this too.

**Comment by ldeman** [comment]
np, if it were apart of the site it would make sense to just load.  but forcing a resync upon loading that page would be a pain.  leave this open though for revil to see, cause i think there should be a manual sync button on that page to basically show people it needs the sync in order to be updated.

_Click here to Sync Group Stickies_

**Comment by gizellos** [comment]
It seems to be bugged, anyway. All the icons sometimes disappear.

I made the resync - all icons disappeared (refresh didn't help).
I went to another page and went back - icons were there.
I went to another page and after a few minutes returned and the icons were gone again.

![2017-03-15_214711](https://cloud.githubusercontent.com/assets/2397851/23970141/27ba8884-09c9-11e7-9a74-9e13ce6fd205.png)

**Comment by gizellos** [comment]
This time it was Create New Giveaway, but I am not sure if it was not just a coincidence.

**Comment by gizellos** [comment]
Now I have them all there and I don't know how to make the disappear again to do some tests.

**Comment by revilheart** [comment]
Yes, visiting the new giveaway page would probably fix it because every time you visit it, it checks the groups in the storage. Let me know if they disappear again.

**Comment by revilheart** [comment]
Should work fine now.
