### ISSUE TITLE
[Bug] Too little width of Avatar popout when the user's icon is on the right side

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#67]
The Avatar popout works good but only if there is enough room to the right side. It means if the icons of the users are on the left side of the web pages. If the icon is on the right side - for example, in the Active Discussions, the popout is too narrow.

I suggest to set something like fixed width to the element always had the default width and set it to move a bit to the left side, instead of the changing its weight.

![avartar popout](https://cloud.githubusercontent.com/assets/2397851/24004812/9de7ad22-0a67-11e7-921c-402623d7096f.png)

**Comment by gizellos** [comment]
Or you can align the right side of the element to the right side of the page.

**Comment by revilheart** [comment]
I'd rather not set a fixed width to it because of the new features. I'll see if I can do something else some other time.

**Comment by gizellos** [comment]
Yes, do anything. Thanks.

**Comment by ldeman** [comment]
@revilheart talk to squished on how he did it imo.  it looks great in dark theme by having it popout to the leftside and depending how low or high it is on the scrollbar it pops up or down.
![peek 2017-03-16 11-53](https://cloud.githubusercontent.com/assets/10275898/24008361/6b8cede2-0a3f-11e7-8efa-a2df22860b8a.gif)

**Comment by revilheart** [comment]
All he did was set a fixed width, which is what I want to avoid.

**Comment by revilheart** [comment]
And it popping up up or down is a feature of the script itself, not the dark theme. :P

**Comment by revilheart** [comment]
Should not be a problem anymore.

**Comment by gizellos** [comment]
Yep, it's OK now. Thanks.
