### ISSUE TITLE
[Bug] Giveaway Data / Stats are not updating as intended for me

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#68]
just as a test i made an additional level 10 giveaway since it was an easy one to notice the change from 1 level 10 giveaway created to two, and it's been a full week since my 2nd level 10 giveaway was accepted yet the data stats are not reflecting that still.

edit: in fact, i just compared to my screenshot from day1 stats and there has been no change when i've given away an additional ~100 games.  :(

**Comment by rafaelgs18** [comment]
I think this might have something to do with having an active giveaway. Have you tried re-checking when all your giveaways have ended?

**Comment by ldeman** [comment]
>Have you tried re-checking when all your giveaways have ended and you don't have a single one active?

that never happens.  ^^ lol

**Comment by rafaelgs18** [comment]
I'll change it later.

**Comment by revilheart** [comment]
Should be fixed.
