### ISSUE TITLE
Strange behavior of Send Unsent Gifts feature after reroll

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#69]
After a gift was rerolled, I clicked to Send Unsent Gifts and it said me that there is no gift for sending. I tried it again and it tried to send the gift to the one person twice.

So there are two issues, it cannot send gifts in specific cases and it tries to send one gift twice in specific cases.

![2017-03-17_194332](https://cloud.githubusercontent.com/assets/2397851/24058191/715f56e0-0b4a-11e7-8bfc-efeb09510c8b.png)

**Comment by gizellos** [comment]
Another bug I found. It seems that the feature doesn't work if the unsent gifts are on page 2+. It says "You have no unsent gifts." although there is one on the page 2.

**Comment by rafaelgs18** [comment]
The image doesn't show any bugs, it is supposed to work that way. Because you asked for a reroll on that user in one of the giveaways, it will try to send the gift on that giveaway and fail.

**Comment by gizellos** [comment]
Ok, but it does the same even without reroll. It tries to send it twice.

![2017-03-20_220406](https://cloud.githubusercontent.com/assets/2397851/24121615/38fe4fba-0db9-11e7-93dd-6f177d054b20.png)

**Comment by gizellos** [comment]
I found that the problem with "You have no unsent gifts." was caused because I didn't scroll up to load the page 2. Maybe you could force to load it in case users haven't do it and they have an unsent keys.

So the only problem is the double sending.

BTW: could you refresh the icons after sending the keys? The icon "Giveaway created" show the number...

**Comment by rafaelgs18** [comment]
Are you maybe loading the pages with endless scrolling? No checkers work well with endless scrolling at the moment, as far as I know.

**Comment by gizellos** [comment]
Yes, I use it.

**Comment by rafaelgs18** [comment]
And does it happen without using it?

**Comment by gizellos** [comment]
I don't know, I have never tried it. But I will try it today, so I will tell you then.

**Comment by gizellos** [comment]
BTW the endless scrolling cannot be disabled for the created giveaway page. I tried  to disable it via "Enable in main / giveaways pages." and "Enable in the rest of the pages." and it didn't disable it, so I have to disable it completely.

**Comment by gizellos** [comment]
I just tried it without the Endless Scrolling and it is the same or worse because I am not able to send the gift even after a time. I tried also url with page=2 and it is the same.

**Comment by gizellos** [comment]
Another try and another results. I had 5 giveaways finished. Two on page 2 and 3 on page 2. The sending worked normally.

**Comment by rafaelgs18** [comment]
I didn't really mean for you to disable endless scrolling, just to run the sender without scrolling down. But yes, the endless scrolling in the giveaways created page should be affected by the rest of the pages setting.

**Comment by gizellos** [comment]
Aha, I see. It doesn't work without scrolling.

**Comment by revilheart** [comment]
Should be fixed, let me know if not.
