### ISSUE TITLE
[Enhancement] bigger and responsible table creator

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#70]
When I add some columns in the table creator, a scrollbar appears. It would not be such a problem if the pop out was not so tiny. Also the cells for values could be bigger. I suggest this:

1.  make the pop out bigger (according to the screen resolution?)
2. make it responsible - increase width of the pop out if more room is required

![2017-03-17_201744](https://cloud.githubusercontent.com/assets/2397851/24059523/b3e2a526-0b4f-11e7-8440-93a2c3a443b9.png)

**Comment by rafaelgs18** [comment]
The nature of popouts doesn't allow it to be adjusted according to the screen resolution, because they have to pop out either above or below the element. Maybe I'll change the popout to a popup.

**Comment by gizellos** [comment]
To tell the truth, I don't know that they are two different things. What is the difference between them?

**Comment by rafaelgs18** [comment]
Popout is what happens when you click on someone's avatar. Popup is what happens when you click on Whitelist / Blacklist Checker button.

**Comment by revilheart** [comment]
Hope it's better now.
