### ISSUE TITLE
[Bug] SteamTrades thread bump tag

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#72]
i rarely ever trade anymore, but noticed this screen when trying to bump too early just too see how long ago it was since i bumped.

![image](https://cloud.githubusercontent.com/assets/10275898/24072963/4f6787ec-0bbd-11e7-947a-162ae865ae64.png)

not really sure what taging the bump would do.  lol ^^

**Comment by rafaelgs18** [comment]
Did that happen before or after tagging an user? It would be helpful if you took a screenshot of the console after right-clicking on the popup and inspecting it.

**Comment by ldeman** [comment]
no, user tagging is disabled actually too. i don't actually have that topic open any more, but i'll edit an old one for a test environment and see what i can do.  ^^

**Comment by ldeman** [comment]
right after opening it up
![screenshot from 2017-03-20 12-18-56](https://cloud.githubusercontent.com/assets/10275898/24112418/73d6be6c-0d67-11e7-822e-40c0899672cc.png)
a few things opened up in case what you need isn't in that shot
![screenshot from 2017-03-20 12-17-57](https://cloud.githubusercontent.com/assets/10275898/24112435/809d5688-0d67-11e7-9574-09f333961c26.png)

**Comment by revilheart** [comment]
Finally fixed this.
