### ISSUE TITLE
[BUG] Unable to click close on pop up after entering GA from list

### ISSUE THREAD

**Issue by to-dr** [revilheart/ESGST#83]
AS above, might be issue if someone have enabled auto showing images. The ;close; button is there, but automatically scrolling so it is out of reach (escape key still works). Minor one 

http://i.imgur.com/zur1TgA.png

**Comment by rafaelgs18** [comment]
Is that giveaway public or already ended so I can test it?

**Comment by to-dr** [comment]
do not remember which one was it, but it happens for me whenever there is image attached, like in this one https://www.steamgifts.com/giveaway/RMwaR/doom

**Comment by rafaelgs18** [comment]
Is this really being caused by this script? Automatically showing images doesn't seem to work in the giveaway description popup to me.

**Comment by to-dr** [comment]
oh,it is not connected to auto showing image, I just cannot close by button after myself clicking to show image, have to use escape

**Comment by ldeman** [comment]
maybe add an X in the corner like a window for circumstances like that.  but also, it can just be clicked out of if resolution permits, without the need for a keyboard. xD

**Comment by revilheart** [comment]
The popups are now repositioned when clicking on them. I hope this helps.

**Comment by to-dr** [comment]
yeah, thanks!
