### ISSUE TITLE
[enhancement] New feature that allow to hide the highlighted giveaways

### ISSUE THREAD

**Issue by Gittino** [revilheart/ESGST#87]
Hi I would like to suggest a new feature. 
The change of the behavior of the button that expands/collapses the highlighted giveaways (the ones in the gray box located on the top of the page).
Currently SG shows only two of them and provides a button to expand the box to show them all. 
Once the box is expanded there is no way to collapse it (the page has to be reloaded).

It would be nice If ESGST implements an option that changes this behavior so that the button allows always to switch between three mode of view of this box: see 2 giveaways, see all giveaways, see no giveaways. 

 

![example](https://cloud.githubusercontent.com/assets/13353503/24828041/35263eca-1c55-11e7-9e75-859dabb84dc3.png)

It would be nice if a similar mechanism will be added also to the discussion box when they are put on top of the giveaway main page by ESGST. 
In this way it is possible to keep collapsed both of the panel and have all of the space for the giveaways list and expand them only when we want.

**Comment by rafaelgs18** [comment]
Yep, that always annoys me and I don't know why I haven't made a feature for it yet. Working on it...

**Comment by Gittino** [comment]
Hi rafaelgs,
thanks for your quick answer and obviously for your great script! 
You are doing a great job, please keep to maintain ESGST updated and to add new cool features!!!
Thanks a lot! 👍

**Comment by Gittino** [comment]
Hi rafaelgs, I have some problem caused by the pinned giveaway button feature. From about 2 days ESGST doesn't work anymore (no endless scroll, no enter button in the giveaway list, no hide entered giveaways etc). Today I discover that it is caused by the pinned giveaway button feature. Disabling it the problems don't occur. 

In the browser console I see this error:
"PGBButton is undefined  PinnedGiveawaysButton.v5.0.js:18:5" 

Hope that it could help. 
Thanks have a nice evening!

**Comment by rafaelgs18** [comment]
Could it be a conflict with another script?

**Comment by Laurvin** [comment]
I guess I should have checked this thread earlier. Just for completion's sake, I described the issue here: [https://www.steamgifts.com/discussion/TDyzv/userscript-esgst-v53-new-giveaway-error-search-links-pinned-giveaways-button/search?page=23#AdP4X0y](url)

**Comment by revilheart** [comment]
The undefined problem has been fixed. I won't be adding your 3-state suggestion (only show 2, show all, show none) because that would be way too complex. I think the current 2-state behavior (expand/collapse) is better.
