### ISSUE TITLE
[Enhancement] EDIT:Auto load images(Solved)/youtube, giveaway filter, separate winning "chance" and "ratio" and  make "not enough point" block smaller

### ISSUE THREAD

**Issue by AxJ11** [revilheart/ESGST#89]
Totally like and recommend this script!!!

There are only two reasons I still keep "Extended Steamgifts" script:
EDIT:1. Comment features (embedded youtube & vimeo videos, gleam.io giveaways)
(auto load images)(Solved)
2. Giveaway filter (levels, percetage, points...etc.)

And some improvement could be made I think:
1.To separate "winning chance" and "winning ratio" to different block and make "ratio" more clear to see(color?).
2. To make "not enough point" block smaller or some icon instead. It's too long right now.

I am looking forward to see these features implemented.

**Comment by gizellos** [comment]
It has "auto load images" - it is a new feature. You might not enabled it or your script is not up-to-date.

ESGST is not very compatible with giveaway filters in ESG (more preciselly they work but you cannot use endless scrolling with it). I had this problem too. I suggest you to use [SteamGifts v2 Giveaway Filter](https://github.com/GarionCZ/sgv2-filter/raw/release/sgv2-filter.user.js) instead of that from ESG. It is fully compatible with ESGST and the script is much better, anyway.

Hopefully, ESGST  will have its own filters too someday.

**Comment by ldeman** [comment]
like gizellos said on the auto-load (or more accurately "auto-formatting"), it should handle youtube links just fine when enabled. (last button of formatting options is enable/disable the auto formatting)

&& i agree on that GA filter, it's a really good filter script that (no offense rafael) i doubt could be built any better.  (with the exception of a small exclusion bug i reported) ^^

**Comment by Royalgamer06** [comment]
Maybe we could merge together one day. Like I am doing now with my scripts (WiP).

**Comment by gizellos** [comment]
Ideman: I believe Rafaelgs would think up some nice enhancements, anyway. Almost all features he made was better than the ones we knew from the other scripts. :) Maybe to add filtering by user tags, or filtering by its own whitelist, or to show only whitelisted giveaways.

**Comment by rafaelgs18** [comment]
I agree that the Not Enough Points button is very long. Maybe I can just rename it to "Error"?

**Comment by rafaelgs18** [comment]
By the way, what's the point of separating Winning Chance from Winning Rate?

**Comment by AxJ11** [comment]
@rafaelgs18 
1. "Error" is fine to me. But will it be confusing if someone not realize what error it refers to?
     Maybe a "Point" word and a "/" sign on it? Just an idea. *_*!
2. Maybe it's just me, I like to look at "Winning Rate" to decide whether or not to attend a giveaway.
    It's clearer and easier than "Winning Chance" to read for me. I used to look at "number of entries"  for 
    reference before I use your script.  It's fine when it is just one copy in a giveaway. But when there are two 
    or more copies in one giveaway, the "Winning Rate" is the best solution.  And now, the "Winning 
    Chance" and "Winning Rate" are side by side in one block.  It makes people not easier to read at first 
    time. I hope you know what I mean. Thanks.

**Comment by AxJ11** [comment]
@gizellos 
1. "Auto load images" : Really? ESGST has the feature?  Oh, I maybe found the problem. The version of  
     ESGST I use is 4.21.3. But I can't update it from the setting menu of SteamGifts nor the installation page 
     of ESGST on GitHub.  They all showed "404 page" Why???!  ~><~ 
2. Filters: I use "SteamGifts v2 Giveaway Filter" too when the filter of "Extended Steamgifts" does work 
    properly.  I agree it's more powerful than the filter of "Extended Steamgifts."  But there is no "chance(%)" 
    filter in "SteamGifts v2 Giveaway Filter." And I found it's better than "Max # of entries" filter. By the way, I 
    think I can use "endless scrolling" of ESGST with the filter of "Extended Steamgifts." *_*?

**Comment by rafaelgs18** [comment]
You're not even using ESGST then. :P ESGST was named rhSGST before v5.0. Have you tried updating through Tampermonkey?

**Comment by AxJ11** [comment]
@rafaelgs18 
Yes, I think I am using rhSGST not ESGST.  I did try update through Tampermonkey. No Luck. It showed "no update found: 26d." Maybe there's something wrong with my browser or computer.  I'll try to figure it out later.

**Comment by rafaelgs18** [comment]
Try updating @name, @namespace, @downloadURL and @updateURL at the header of the script to the ones in the current version, and also the "Update URL" field on Tampermonkey. If you don't know how to do it, I can help you.

**Comment by AxJ11** [comment]
@rafaelgs18 
Where can I find the current version? 
I changed @name, @downloadURL, @updateURL and "Update URL" field on Tampermonkey like you said. 
"@namespace" I don't know what to change.
I am not sure I'm doing right.  ><~

=========================================================
"Update URL":https://github.com/revilheart/ESGST/raw/master/ESGST.user.js
// ==UserScript==
// @name ESGST
// @namespace revilheart
// @author revilheart
// @description Adds some cool features to SteamGifts.
// @version 4.21.3
// @downloadURL https://github.com/revilheart/ESGST/raw/master/ESGST.user.js
// @updateURL https://github.com/revilheart/ESGST/raw/master/ESGST.meta.js
// @match https://www.steamgifts.com/*
// @match https://www.steamtrades.com/*
// @grant GM_setValue
// @grant GM_getValue
// @grant GM_deleteValue
// @grant GM_listValues
// @grant GM_xmlhttpRequest
// @grant GM_addStyle
// @connect steamgifts.com
// @connect script.google.com
// @connect script.googleusercontent.com
// @connect sgtools.info
// @connect steamcommunity.com
// @connect api.steampowered.com
// @require https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js
// @require https://greasyfork.org/scripts/26575-bpopup/code/bPopup.js?version=169515
// @require https://cdn.steamgifts.com/js/highcharts.js
// @run-at document-end
// ==/UserScript==

**Comment by ldeman** [comment]
namespace = 
// @namespace ESGST

then have tampermonkey check for updates.  all your other edits, looked proper to me.

**Comment by rafaelgs18** [comment]
It's rafaelgs18, not revilheart, and namespace is what Ideman said.

**Comment by AxJ11** [comment]
Oh, thank you.  At first rhSGST still didn't update through tampermonkey after I changed @namespace.
So I reboot my computer and Win10 ran some kind of update.
And I tried update ESGST from its page on SteamGifts. Then BOOM!  It CAN update from there. WOW~ 🤘

I'm not sure what happened but I'm happy right now.

I see very nice tweaks and improvements.  Awesome!  
Now, a auto-load youtube video feature would be great.

About "not enough point" thing, I think just delete "not enough" and keep "! Point" will do the same thing.
And right, the filter of ESG doesn't work properly when "endless scrolling" enable afterward second page.

**Comment by rafaelgs18** [comment]
It looks like the link on GitHub is broken, I'll have to fix it.

**Comment by gizellos** [comment]
> But there is no "chance(%)"
> filter in "SteamGifts v2 Giveaway Filter." 

AxJ11:
I am afraid that the chance filter in ESG doesn't work as you would wish. Let's imagine two giveaways: First one is public lvl 0 set for 3 weeks, it has 10 entries  and it is old 30 seconds, the other is lvl 5 set for an hour, has 100 entries and it is old 55 minutes. ESG will show you the first GA as first but in fact, the giveaway chance to win will be maybe 0,01 when it ends. Do you understand the problem? The ESG algorithm is too simple to tell you which GA is worth because of its high chance. It doesn't work with time at all and all fresh giveaways have high chance to win when they are just few seconds or minutes old.

**Comment by AxJ11** [comment]
Wait, what?
But the chance filter ESG does show me the giveaway by ending-time order then sort by the chances.
Though I don't use ESG right now because it doesn't work afterward page 2 with or without endless scrolling.

**Comment by gizellos** [comment]
AxJ11: It's long time since I tried it, it is possible. Then it is not so bad.

If you want to win as many GAs as possible, try to set low points range (0 - 5 points, for example) and the highest possible level requirements. If there are too few giveaways for you, then try to add a lower level. I think it works well like that and you wouldn't have to use the chance filter.

**Comment by AxJ11** [comment]
Yes, I did won much more giveaways since I use filter scripts. (They are low CV value, of course. ^_^b)
Right now I set level 3 and  Max 200-400 of entries. 
But it has blind spot when there are 2 or more copies of gifts in a giveaway. 
That's where the chance filter comes in.
If I don't use chance filter, I won't see a 800 entries with 2 copies of gifts in a giveaway.
But it has the same chance with 400 entries with only 1 gift in a giveaway.

If possible, maybe I would like to suggest the author of SteamGifts v2 Giveaway Filter these features.

**Comment by revilheart** [comment]
Added Embedded Videos.

**Comment by AxJ11** [comment]
Thank you!!!

Now,  I officially retire ESG~

**Comment by revilheart** [comment]
The only thing missing to be implemented in this issue is gleam.io giveaways. I'll look into it later.

**Comment by AxJ11** [comment]
Hi, I just want to say "THANK YOU."
You add every feature I want!
(youbube link auto load, giveaway filter, ratio block, not enough point block..etc)

You are AWESOME!

**Comment by revilheart** [comment]
I don't see how to embed Gleam.io giveaways and I don't have any to test. I also don't see those on the forum a lot, and I believe there is something against them in the TOS? So I won't be implementing that part.

**Comment by ldeman** [comment]
>&& i agree on that GA filter, it's a really good filter script that (no offense rafael) i doubt could be built any better. (with the exception of a small exclusion bug i reported) ^^

i luv that u proved me wrong.  xD
it's way better!  ^^
