### ISSUE TITLE
[Enhancement] Exclude this giveaway from the Unsent Gift Sender

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#90]
I suck at making a good example pic, but it gets the point across ^^
![image](https://cloud.githubusercontent.com/assets/10275898/25096885/d2f25ce2-2367-11e7-8f94-2c0a4edac743.png)

**Comment by gizellos** [comment]
Sounds good. I am for it. :)

**Comment by ldeman** [comment]
> Sounds good. I am for it. :)

yeah without it i barely get the chance to utilize the sender.  i have to make sure people are still inside the unlucky-7 group prior to sending it cause after a winners 8th win they get kicked to prevent a 9th+ win.  (unless they qualify and request gifter status).

i guess the other alternative would be to add group exceptions for the sender (on the gift pages have tickboxes to exclude certain groups from the unsent gift sender)

**Comment by revilheart** [comment]
I could just implement a function that checks if the winner is still in one of the groups of the giveaway.

**Comment by revilheart** [comment]
Added the function mentioned above, let me know if it works well. It ran correctly in my testings.

**Comment by ldeman** [comment]
thanks, that should do perfectly for that situation.  ^^
ill let you know if any issues occur
