### ISSUE TITLE
[Enhancement] SG Tags "Bundled" Replacement

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#93]
I've been happy with SG Game Tags, so much so that I've always recommended it when anything of the sort comes up relating to tags, however..   as long as Ruphine has been gone, and as little as the database for the bundled tags has been updated, it is starting to need a replacement.

As far as I can tell, all the other parts of that script still work fine without the need for database updates..  maybe there could be a "hotfix/patch" inside this script that could change the other script from a database check, to live checking the bundle list instead?

Or alternatively, just create a feature to specify games that are contained in the bundle list, and people can disable that portion of Ruphines script?

If Ruphine starts showing signs of return, then this entire suggestion can be ignored, but it's really starting to look like they won't be returning to the site anytime soon anyways.

**Comment by revilheart** [comment]
Live checking the bundle list wouldn't be a good idea, lots of requests would have to be made. I could use a Google Sheet as database like I do with Username History, just not sure if it would be able to handle it (I don't think many users use Username History).

**Comment by ldeman** [comment]
that's what i was thinking on live checking too, way too many requests per pageload.  if a google sheet could work that would be amazing, but i too am not sure it could handle the bandwidth that would come with it.

sighery would know better, but if i remb correctly ruphine ran into a few problems trying something similar and had to give up going that route and purchase a hosting plan specifically for it.

anything to help identify whether it's considered SG bundled or not would be helpful if there is any other way of doing it you can think of though.  ruphine has given permission (top of her sg tags thread) to take whatever portions of code you want to save some of the workload if you decided to try and implement something though, but it's going on about 3months since the last database update, so i fear some alt is needed at this point.

**Comment by revilheart** [comment]
The alternative for Google Sheets is to have the database on each user's storage. That would of course be a waste of requests and space, but it's already done with the checker features anyway. Considering there are 322 pages of bundle games, each user would have to make 322 requests every time the database needs to be updated. But that doesn't seem much, cg complained about 700+ requests per minute if I remember correctly. The problem would be time: 322 requests (2 per second) would take about 5 minutes.

**Comment by ldeman** [comment]
that sounds plenty reasonable to me and worth the update time imo.  i'd probably make it a manual only update and not mandatory as apart of the rest of the sync options personally though since shobo only adds stuff to the bundle list around 1-2 times a week & some people would want to sync the rest of the stuff more frequently then that.

either way sounds great to me though if google sheets can handle the load.  ^^

**Comment by revilheart** [comment]
What would be way better is if shobo kept a list of recently added bundles.

**Comment by ldeman** [comment]
maybe it could combine a one-time scan with a fairly regular check against http://www.sgtools.info/lastbundled (this page) for changes rather then a full rescan of all pages?

**Comment by revilheart** [comment]
Doesn't seem very reliable if there were more than 50 games added since the last time checked. I'll work something out.

**Comment by ldeman** [comment]
yeah i thought about that after i sent.  good luck on test-runs.  ^^

**Comment by revilheart** [comment]
Added

**Comment by ldeman** [comment]
thanks, i tested it working great for me.
i can now turn of ruphines bundle tag and enable yours and it works perfectly right along with the rest of ruphines other tags.  ^^

**Comment by revilheart** [comment]
Glad to hear it. ^^

**Comment by ldeman** [comment]
mhh, actually i just saw one more place i'd like to have it (also to match ruphines tagging setup for others, as i turned it off personally).

if it's not too much trouble could you add that same red identifying tag approximately here?  (i suck at photo editing) 
![image](https://cloud.githubusercontent.com/assets/10275898/26289742/0bbae43e-3e68-11e7-97f3-4c5bbc2b5a5d.png)

**Comment by ldeman** [comment]
actually no, the arrow is in the wrong place.. here's a photo of ruphines tags though if you could match the location that would be awesome.  ^^
![image](https://cloud.githubusercontent.com/assets/10275898/26289782/4fcea796-3e68-11e7-99e6-274654008adb.png)

**Comment by revilheart** [comment]
Sure thing.
