### ISSUE TITLE
[Bug] Sometimes topics in Active Discussions cannot be set as visited

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#95]
As title says "Sometimes topics in Active Discussions cannot be set as visited." I don't know why but if I go to discussion and then back to main page, it works normally.

![2017-05-08_175248](https://cloud.githubusercontent.com/assets/2397851/25812731/822094f8-3417-11e7-8f86-dfeea90c1ef3.png)

**Comment by revilheart** [comment]
Fixed
