### ISSUE TITLE
[Bug] Icon of users I whitelisted/blacklisted doesn't appear

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#96]
Hi,
the icon of users I whitelisted/blacklisted doesn't appear beside the names. Only the icons of users who whitelisted/blacklisted me appear.

I also think you mixed up two features in the description of the featrure [Whitelist/Blacklist Highlighter](https://github.com/revilheart/ESGST#whitelistblacklist-highlighter) here on Github. It looks as if I had to scan something for this heart but it is not true.

**Comment by gizellos** [comment]
![2017-05-21_114946](https://cloud.githubusercontent.com/assets/2397851/26282912/a261204e-3e1b-11e7-841b-77b3c34c0e85.png)

**Comment by revilheart** [comment]
Could the feature have been disabled with the update?

**Comment by gizellos** [comment]
It doesn't matter if I enable or disable the feature it always shows only the icon that indcicated that you WLed me.

**Comment by gizellos** [comment]
Also Groups Highlighter stopped to work for me since last update. It looks as if I had some stuff disabled.

**Comment by gizellos** [comment]
Sorry, the sync really helped it. I will close this.

**Comment by revilheart** [comment]
Can you try syncing through the settings menu? Groups Highlighter is not working everywhere? Are there errors in the console?

**Comment by revilheart** [comment]
Oh I see. I think it wasn't showing that you whitelisted me because I changed usernames (I'm assuming it was only happening with me).

What about the Groups Highlighter issue?

**Comment by gizellos** [comment]
No, It didn't show anyone. The group highlighter is working as well. It looks everything is normal after the script resync.
