### ISSUE TITLE
[BUG] Creating a giveaway gives a "games category" error

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#98]
![image](https://cloud.githubusercontent.com/assets/10275898/26316665/9e993748-3eda-11e7-8d60-bc8f55d2c785.png)

all 5 of them i just created gave this error.

**Comment by revilheart** [comment]
Ah, forgot the confirm page is also "/giveaways/new". Will fix it in the next version.

**Comment by ldeman** [comment]
sounds great, thanks ^^

**Comment by revilheart** [comment]
Should be fixed.
