### ISSUE TITLE
[Bug] Status doesn't update after Sync Bundle List

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#99]
After my first sync of Bundle list, I noticed that there was still written " Never synced.". I had to refresh the page to see the correct "Last synced 22. 5. 2017 17:46:55.".

You should force to refresh the status.

**Comment by revilheart** [comment]
I wouldn't really call this a bug, it's more of a behavior, but will change it in the next version.

**Comment by revilheart** [comment]
Fixed

**Comment by gizellos** [comment]
Cool!
